{-
   SimpleBilly API
   Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

   The version of the OpenAPI document: 0.1.0
   Contact: support@simplebilly.com

   NOTE: This file is auto generated by the openapi-generator.
   https://github.com/openapitools/openapi-generator.git

   DO NOT EDIT THIS FILE MANUALLY.

   For more info on generating Elm code, see https://eriktim.github.io/openapi-elm/
-}


module Api.Request.Activity exposing
    ( createActivity
    , deleteActivity
    , getActivity
    , listActivities
    , updateActivity
    , updateActivityStatus
    )

import Api
import Api.Data exposing (..)
import Dict
import Http
import Json.Decode
import Json.Encode


createActivity : Api.Data.Activity -> String -> Api.Request Api.Data.Activity
createActivity activity_body auth_token =
    Api.request
        "POST"
        "/api/v1/activities"
        []
        []
        []
        (Maybe.map Http.jsonBody (Just (Api.Data.encodeActivity activity_body)))
        Api.Data.activityDecoder
        |> Api.withBearerToken auth_token

deleteActivity : String -> String -> Api.Request ()
deleteActivity activityId_path auth_token =
    Api.request
        "DELETE"
        "/api/v1/activities/{activity_id}"
        [ ( "activity_id", identity activityId_path ) ]
        []
        []
        Nothing
        (Json.Decode.succeed ())
        |> Api.withBearerToken auth_token

getActivity : String -> String -> Api.Request Api.Data.Activity
getActivity activityId_path auth_token =
    Api.request
        "GET"
        "/api/v1/activities/{activity_id}"
        [ ( "activity_id", identity activityId_path ) ]
        []
        []
        Nothing
        Api.Data.activityDecoder
        |> Api.withBearerToken auth_token

listActivities : Maybe Int -> Maybe Int -> Maybe String -> Maybe String -> Maybe String -> Maybe String -> Maybe Bool -> String -> Api.Request (List Api.Data.Activity)
listActivities page_query pageSize_query contactId_query activityType_query status_query assignedTo_query overdueOnly_query auth_token =
    Api.request
        "GET"
        "/api/v1/activities/"
        []
        [ ( "page", Maybe.map String.fromInt page_query ), ( "pageSize", Maybe.map String.fromInt pageSize_query ), ( "contactId", Maybe.map identity contactId_query ), ( "activityType", Maybe.map identity activityType_query ), ( "status", Maybe.map identity status_query ), ( "assignedTo", Maybe.map identity assignedTo_query ), ( "overdueOnly", Maybe.map (\val -> if val then "true" else "false") overdueOnly_query ) ]
        []
        Nothing
        (Json.Decode.list Api.Data.activityDecoder)
        |> Api.withBearerToken auth_token

updateActivity : String -> Api.Data.AnyType -> String -> Api.Request Api.Data.Activity
updateActivity activityId_path body_body auth_token =
    Api.request
        "PUT"
        "/api/v1/activities/{activity_id}"
        [ ( "activity_id", identity activityId_path ) ]
        []
        []
        (Maybe.map Http.jsonBody (Just (encodeAnyType body_body)))
        Api.Data.activityDecoder
        |> Api.withBearerToken auth_token

updateActivityStatus : String -> Api.Data.ActivityStatusUpdate -> String -> Api.Request Api.Data.Activity
updateActivityStatus activityId_path activityStatusUpdate_body auth_token =
    Api.request
        "PUT"
        "/api/v1/activities/{activity_id}/status"
        [ ( "activity_id", identity activityId_path ) ]
        []
        []
        (Maybe.map Http.jsonBody (Just (Api.Data.encodeActivityStatusUpdate activityStatusUpdate_body)))
        Api.Data.activityDecoder
        |> Api.withBearerToken auth_token
