{-
   SimpleBilly API
   Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

   The version of the OpenAPI document: 0.1.0
   Contact: support@simplebilly.com

   NOTE: This file is auto generated by the openapi-generator.
   https://github.com/openapitools/openapi-generator.git

   DO NOT EDIT THIS FILE MANUALLY.

   For more info on generating Elm code, see https://eriktim.github.io/openapi-elm/
-}


module Api.Request.Ai exposing
    ( aiSuggestApi
    , createWorkerApi
    , listWorkersApi
    , runWorkerApi
    )

import Api
import Api.Data exposing (..)
import Dict
import Http
import Json.Decode
import Json.Encode
import Uuid exposing (Uuid)


aiSuggestApi : Api.Data.AiSuggestionRequest -> String -> Api.Request Api.Data.AiSuggestion
aiSuggestApi aiSuggestionRequest_body auth_token =
    Api.request
        "POST"
        "/api/v1/support/ai/suggest"
        []
        []
        []
        (Maybe.map Http.jsonBody (Just (Api.Data.encodeAiSuggestionRequest aiSuggestionRequest_body)))
        Api.Data.aiSuggestionDecoder
        |> Api.withBearerToken auth_token

createWorkerApi : Api.Data.AiConfigDto -> String -> Api.Request Api.Data.AiWorkerConfig
createWorkerApi aiConfigDto_body auth_token =
    Api.request
        "POST"
        "/api/v1/support/ai/workers"
        []
        []
        []
        (Maybe.map Http.jsonBody (Just (Api.Data.encodeAiConfigDto aiConfigDto_body)))
        Api.Data.aiWorkerConfigDecoder
        |> Api.withBearerToken auth_token

listWorkersApi : String -> Api.Request (List Api.Data.AiWorkerConfig)
listWorkersApi auth_token =
    Api.request
        "GET"
        "/api/v1/support/ai/workers"
        []
        []
        []
        Nothing
        (Json.Decode.list Api.Data.aiWorkerConfigDecoder)
        |> Api.withBearerToken auth_token

runWorkerApi : Uuid -> Api.Data.AiSuggestionRequest -> String -> Api.Request Api.Data.AiSuggestion
runWorkerApi workerId_path aiSuggestionRequest_body auth_token =
    Api.request
        "POST"
        "/api/v1/support/ai/workers/{worker_id}/run"
        [ ( "worker_id", Uuid.toString workerId_path ) ]
        []
        []
        (Maybe.map Http.jsonBody (Just (Api.Data.encodeAiSuggestionRequest aiSuggestionRequest_body)))
        Api.Data.aiSuggestionDecoder
        |> Api.withBearerToken auth_token
