{-
   SimpleBilly API
   Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

   The version of the OpenAPI document: 0.1.0
   Contact: support@simplebilly.com

   NOTE: This file is auto generated by the openapi-generator.
   https://github.com/openapitools/openapi-generator.git

   DO NOT EDIT THIS FILE MANUALLY.

   For more info on generating Elm code, see https://eriktim.github.io/openapi-elm/
-}


module Api.Request.Attachment exposing
    ( attachmentRestore
    , createAttachment
    , deleteAttachment
    , getAttachment
    , listAttachments
    , saveAttachmentOcrText
    )

import Api
import Api.Data exposing (..)
import Dict
import Http
import Json.Decode
import Json.Encode
import Uuid exposing (Uuid)


attachmentRestore : Uuid -> String -> Api.Request Api.Data.Attachment
attachmentRestore id_path auth_token =
    Api.request
        "POST"
        "/api/v1/attachments/{id}/restore"
        [ ( "id", Uuid.toString id_path ) ]
        []
        []
        Nothing
        Api.Data.attachmentDecoder
        |> Api.withBearerToken auth_token

createAttachment : Api.Data.AttachmentCreate -> String -> Api.Request Api.Data.Attachment
createAttachment attachmentCreate_body auth_token =
    Api.request
        "POST"
        "/api/v1/attachments"
        []
        []
        []
        (Maybe.map Http.jsonBody (Just (Api.Data.encodeAttachmentCreate attachmentCreate_body)))
        Api.Data.attachmentDecoder
        |> Api.withBearerToken auth_token

deleteAttachment : Uuid -> String -> Api.Request ()
deleteAttachment id_path auth_token =
    Api.request
        "DELETE"
        "/api/v1/attachments/{id}"
        [ ( "id", Uuid.toString id_path ) ]
        []
        []
        Nothing
        (Json.Decode.succeed ())
        |> Api.withBearerToken auth_token

getAttachment : Uuid -> String -> Api.Request Api.Data.Attachment
getAttachment id_path auth_token =
    Api.request
        "GET"
        "/api/v1/attachments/{id}"
        [ ( "id", Uuid.toString id_path ) ]
        []
        []
        Nothing
        Api.Data.attachmentDecoder
        |> Api.withBearerToken auth_token

listAttachments : Maybe Int -> Maybe Int -> Maybe String -> String -> Api.Request (List Api.Data.Attachment)
listAttachments page_query pageSize_query contactId_query auth_token =
    Api.request
        "GET"
        "/api/v1/attachments/"
        []
        [ ( "page", Maybe.map String.fromInt page_query ), ( "pageSize", Maybe.map String.fromInt pageSize_query ), ( "contactId", Maybe.map identity contactId_query ) ]
        []
        Nothing
        (Json.Decode.list Api.Data.attachmentDecoder)
        |> Api.withBearerToken auth_token

{-| Persist client-side OCR output for an attachment.
-}
saveAttachmentOcrText : Uuid -> Api.Data.OcrTextRequest -> String -> Api.Request Api.Data.Attachment
saveAttachmentOcrText attachmentId_path ocrTextRequest_body auth_token =
    Api.request
        "PUT"
        "/api/v1/attachments/{attachment_id}/ocr-text"
        [ ( "attachment_id", Uuid.toString attachmentId_path ) ]
        []
        []
        (Maybe.map Http.jsonBody (Just (Api.Data.encodeOcrTextRequest ocrTextRequest_body)))
        Api.Data.attachmentDecoder
        |> Api.withBearerToken auth_token
