{-
   SimpleBilly API
   Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

   The version of the OpenAPI document: 0.1.0
   Contact: support@simplebilly.com

   NOTE: This file is auto generated by the openapi-generator.
   https://github.com/openapitools/openapi-generator.git

   DO NOT EDIT THIS FILE MANUALLY.

   For more info on generating Elm code, see https://eriktim.github.io/openapi-elm/
-}


module Api.Request.AttachmentVersion exposing
    ( createAttachmentVersion
    , listAttachmentVersions
    , restoreAttachmentVersion
    )

import Api
import Api.Data exposing (..)
import Dict
import Http
import Json.Decode
import Json.Encode
import Uuid exposing (Uuid)


createAttachmentVersion : Uuid -> Api.Data.NewVersionRequest -> String -> Api.Request Api.Data.AttachmentVersion
createAttachmentVersion attachmentId_path newVersionRequest_body auth_token =
    Api.request
        "POST"
        "/api/v1/attachments/{attachment_id}/versions"
        [ ( "attachment_id", Uuid.toString attachmentId_path ) ]
        []
        []
        (Maybe.map Http.jsonBody (Just (Api.Data.encodeNewVersionRequest newVersionRequest_body)))
        Api.Data.attachmentVersionDecoder
        |> Api.withBearerToken auth_token

listAttachmentVersions : Uuid -> String -> Api.Request (List Api.Data.AttachmentVersion)
listAttachmentVersions attachmentId_path auth_token =
    Api.request
        "GET"
        "/api/v1/attachments/{attachment_id}/versions"
        [ ( "attachment_id", Uuid.toString attachmentId_path ) ]
        []
        []
        Nothing
        (Json.Decode.list Api.Data.attachmentVersionDecoder)
        |> Api.withBearerToken auth_token

restoreAttachmentVersion : Uuid -> Uuid -> String -> Api.Request Api.Data.Attachment
restoreAttachmentVersion attachmentId_path versionId_path auth_token =
    Api.request
        "POST"
        "/api/v1/attachments/{attachment_id}/versions/{version_id}/restore"
        [ ( "attachment_id", Uuid.toString attachmentId_path ), ( "version_id", Uuid.toString versionId_path ) ]
        []
        []
        Nothing
        Api.Data.attachmentDecoder
        |> Api.withBearerToken auth_token
