{-
   SimpleBilly API
   Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

   The version of the OpenAPI document: 0.1.0
   Contact: support@simplebilly.com

   NOTE: This file is auto generated by the openapi-generator.
   https://github.com/openapitools/openapi-generator.git

   DO NOT EDIT THIS FILE MANUALLY.

   For more info on generating Elm code, see https://eriktim.github.io/openapi-elm/
-}


module Api.Request.Auth exposing
    ( acceptInvite
    , forgotPassword
    , login
    , logout
    , magicLinkLogin
    , magicLinkVerify
    , register
    , resetPassword
    , totpEnable
    , totpSetup
    , verifyEmail
    )

import Api
import Api.Data exposing (..)
import Dict
import Http
import Json.Decode
import Json.Encode


{-| Accept an invite: create the account (or reuse an existing one) and join the inviting tenant. The invite token proves control of the mailbox.
-}
acceptInvite : Api.Data.AcceptInviteRequest -> String -> Api.Request ()
acceptInvite acceptInviteRequest_body auth_token =
    Api.request
        "POST"
        "/auth/accept-invite"
        []
        []
        []
        (Maybe.map Http.jsonBody (Just (Api.Data.encodeAcceptInviteRequest acceptInviteRequest_body)))
        (Json.Decode.succeed ())
        |> Api.withBearerToken auth_token

{-| Send a password reset email to the user
-}
forgotPassword : Api.Data.ForgotPasswordRequest -> String -> Api.Request ()
forgotPassword forgotPasswordRequest_body auth_token =
    Api.request
        "POST"
        "/auth/forgot-password"
        []
        []
        []
        (Maybe.map Http.jsonBody (Just (Api.Data.encodeForgotPasswordRequest forgotPasswordRequest_body)))
        (Json.Decode.succeed ())
        |> Api.withBearerToken auth_token

{-| Authenticate a user with email + password (optional TOTP)
-}
login : Api.Data.LoginRequest -> String -> Api.Request Api.Data.AuthResponse
login loginRequest_body auth_token =
    Api.request
        "POST"
        "/auth/login"
        []
        []
        []
        (Maybe.map Http.jsonBody (Just (Api.Data.encodeLoginRequest loginRequest_body)))
        Api.Data.authResponseDecoder
        |> Api.withBearerToken auth_token

{-| Log out the current user (kills the assay session)
-}
logout : String -> Api.Request ()
logout auth_token =
    Api.request
        "POST"
        "/auth/logout"
        []
        []
        []
        Nothing
        (Json.Decode.succeed ())
        |> Api.withBearerToken auth_token

{-| Request a magic link login (sends an email with a one-time link)
-}
magicLinkLogin : Api.Data.MagicLinkRequest -> String -> Api.Request ()
magicLinkLogin magicLinkRequest_body auth_token =
    Api.request
        "POST"
        "/auth/magic-link"
        []
        []
        []
        (Maybe.map Http.jsonBody (Just (Api.Data.encodeMagicLinkRequest magicLinkRequest_body)))
        (Json.Decode.succeed ())
        |> Api.withBearerToken auth_token

{-| Verify a magic link token and log the user in
-}
magicLinkVerify : Api.Data.MagicLinkVerifyRequest -> String -> Api.Request Api.Data.AuthResponse
magicLinkVerify magicLinkVerifyRequest_body auth_token =
    Api.request
        "POST"
        "/auth/magic-link/verify"
        []
        []
        []
        (Maybe.map Http.jsonBody (Just (Api.Data.encodeMagicLinkVerifyRequest magicLinkVerifyRequest_body)))
        Api.Data.authResponseDecoder
        |> Api.withBearerToken auth_token

{-| Register a new user account
-}
register : Api.Data.RegisterRequest -> String -> Api.Request Api.Data.AuthResponse
register registerRequest_body auth_token =
    Api.request
        "POST"
        "/auth/register"
        []
        []
        []
        (Maybe.map Http.jsonBody (Just (Api.Data.encodeRegisterRequest registerRequest_body)))
        Api.Data.authResponseDecoder
        |> Api.withBearerToken auth_token

{-| Reset the user's password using a reset token
-}
resetPassword : Api.Data.ResetPasswordRequest -> String -> Api.Request ()
resetPassword resetPasswordRequest_body auth_token =
    Api.request
        "POST"
        "/auth/reset-password"
        []
        []
        []
        (Maybe.map Http.jsonBody (Just (Api.Data.encodeResetPasswordRequest resetPasswordRequest_body)))
        (Json.Decode.succeed ())
        |> Api.withBearerToken auth_token

{-| Enable TOTP two-factor authentication by verifying a code
-}
totpEnable : Api.Data.TotpEnableRequest -> String -> Api.Request ()
totpEnable totpEnableRequest_body auth_token =
    Api.request
        "POST"
        "/auth/totp/enable"
        []
        []
        []
        (Maybe.map Http.jsonBody (Just (Api.Data.encodeTotpEnableRequest totpEnableRequest_body)))
        (Json.Decode.succeed ())
        |> Api.withBearerToken auth_token

{-| Set up TOTP two-factor authentication (generates secret + backup codes)
-}
totpSetup : String -> Api.Request Api.Data.TotpSetupResponse
totpSetup auth_token =
    Api.request
        "GET"
        "/auth/totp/setup"
        []
        []
        []
        Nothing
        Api.Data.totpSetupResponseDecoder
        |> Api.withBearerToken auth_token

{-| Verify a user's email address using a verification token
-}
verifyEmail : Api.Data.VerifyEmailRequest -> String -> Api.Request ()
verifyEmail verifyEmailRequest_body auth_token =
    Api.request
        "POST"
        "/auth/verify-email"
        []
        []
        []
        (Maybe.map Http.jsonBody (Just (Api.Data.encodeVerifyEmailRequest verifyEmailRequest_body)))
        (Json.Decode.succeed ())
        |> Api.withBearerToken auth_token
