{-
   SimpleBilly API
   Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

   The version of the OpenAPI document: 0.1.0
   Contact: support@simplebilly.com

   NOTE: This file is auto generated by the openapi-generator.
   https://github.com/openapitools/openapi-generator.git

   DO NOT EDIT THIS FILE MANUALLY.

   For more info on generating Elm code, see https://eriktim.github.io/openapi-elm/
-}


module Api.Request.Automations exposing
    ( listAutomations
    , triggerAutomation
    , updateAutomation
    )

import Api
import Api.Data exposing (..)
import Dict
import Http
import Json.Decode
import Json.Encode


listAutomations : String -> Api.Request (List Api.Data.AutomationDto)
listAutomations auth_token =
    Api.request
        "GET"
        "/api/v1/automations"
        []
        []
        []
        Nothing
        (Json.Decode.list Api.Data.automationDtoDecoder)
        |> Api.withBearerToken auth_token

triggerAutomation : String -> String -> Api.Request (Dict.Dict String Api.Data.Object)
triggerAutomation key_path auth_token =
    Api.request
        "POST"
        "/api/v1/automations/{key}/trigger"
        [ ( "key", identity key_path ) ]
        []
        []
        Nothing
        (Json.Decode.dict )
        |> Api.withBearerToken auth_token

updateAutomation : String -> Api.Data.UpdateAutomation -> String -> Api.Request Api.Data.AutomationDto
updateAutomation key_path updateAutomation_body auth_token =
    Api.request
        "PUT"
        "/api/v1/automations/{key}"
        [ ( "key", identity key_path ) ]
        []
        []
        (Maybe.map Http.jsonBody (Just (Api.Data.encodeUpdateAutomation updateAutomation_body)))
        Api.Data.automationDtoDecoder
        |> Api.withBearerToken auth_token
