{-
   SimpleBilly API
   Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

   The version of the OpenAPI document: 0.1.0
   Contact: support@simplebilly.com

   NOTE: This file is auto generated by the openapi-generator.
   https://github.com/openapitools/openapi-generator.git

   DO NOT EDIT THIS FILE MANUALLY.

   For more info on generating Elm code, see https://eriktim.github.io/openapi-elm/
-}


module Api.Request.Banking exposing
    ( bankLookupApi
    , bankTransactionsApi
    , hebesatzLookupApi
    )

import Api
import Api.Data exposing (..)
import Dict
import Http
import Json.Decode
import Json.Encode


bankLookupApi : String -> String -> Api.Request Api.Data.BankLookup
bankLookupApi iban_query auth_token =
    Api.request
        "GET"
        "/api/v1/bookkeeping/banking/lookup"
        []
        [ ( "iban", Just <| identity iban_query ) ]
        []
        Nothing
        Api.Data.bankLookupDecoder
        |> Api.withBearerToken auth_token

bankTransactionsApi : String -> Api.Request ()
bankTransactionsApi auth_token =
    Api.request
        "GET"
        "/api/v1/bookkeeping/banking/transactions"
        []
        []
        []
        Nothing
        (Json.Decode.succeed ())
        |> Api.withBearerToken auth_token

hebesatzLookupApi : Maybe String -> Maybe String -> Maybe String -> Maybe String -> Maybe String -> String -> Api.Request (List Api.Data.HebesatzLookup)
hebesatzLookupApi gemeindeschluessel_query plz_query name_query stichtag_query countryCode_query auth_token =
    Api.request
        "GET"
        "/api/v1/bookkeeping/hebesatz"
        []
        [ ( "gemeindeschluessel", Maybe.map identity gemeindeschluessel_query ), ( "plz", Maybe.map identity plz_query ), ( "name", Maybe.map identity name_query ), ( "stichtag", Maybe.map identity stichtag_query ), ( "country_code", Maybe.map identity countryCode_query ) ]
        []
        Nothing
        (Json.Decode.list Api.Data.hebesatzLookupDecoder)
        |> Api.withBearerToken auth_token
