{-
   SimpleBilly API
   Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

   The version of the OpenAPI document: 0.1.0
   Contact: support@simplebilly.com

   NOTE: This file is auto generated by the openapi-generator.
   https://github.com/openapitools/openapi-generator.git

   DO NOT EDIT THIS FILE MANUALLY.

   For more info on generating Elm code, see https://eriktim.github.io/openapi-elm/
-}


module Api.Request.Billing exposing
    ( getPlans
    , getQuotaApi
    , getSubscriptionApi
    , getUsageApi
    , paddleSubscriptionWebhook
    , putQuotaApi
    )

import Api
import Api.Data exposing (..)
import Dict
import Http
import Json.Decode
import Json.Encode


{-| All canonical plans (free/starter/business/enterprise) — the single source of truth lives in `crate::saasy::plans`, matching marketing.
-}
getPlans : String -> Api.Request Api.Data.ApiResponseVecPlan
getPlans auth_token =
    Api.request
        "GET"
        "/api/v1/plans"
        []
        []
        []
        Nothing
        Api.Data.apiResponseVecPlanDecoder
        |> Api.withBearerToken auth_token

{-| Effective limits + current usage for the calling tenant.
-}
getQuotaApi : String -> Api.Request ()
getQuotaApi auth_token =
    Api.request
        "GET"
        "/api/v1/quota"
        []
        []
        []
        Nothing
        (Json.Decode.succeed ())
        |> Api.withBearerToken auth_token

getSubscriptionApi : String -> Api.Request Api.Data.ApiResponseSubscriptionOverview
getSubscriptionApi auth_token =
    Api.request
        "GET"
        "/api/v1/subscription"
        []
        []
        []
        Nothing
        Api.Data.apiResponseSubscriptionOverviewDecoder
        |> Api.withBearerToken auth_token

getUsageApi : Maybe String -> String -> Api.Request ()
getUsageApi meter_query auth_token =
    Api.request
        "GET"
        "/api/v1/usage"
        []
        [ ( "meter", Maybe.map identity meter_query ) ]
        []
        Nothing
        (Json.Decode.succeed ())
        |> Api.withBearerToken auth_token

{-| Paddle Billing subscription webhook. Verifies the `Paddle-Signature` header (HMAC-SHA256 over `\"{ts}:{raw_body}\"` with the webhook secret), then updates `billing_info` and `tenants.plan` for the tenant identified by the subscription `custom_data` (JSON `{\"tenant_id\": \"...\"}` or a bare tenant UUID).
-}
paddleSubscriptionWebhook : String -> Api.Request ()
paddleSubscriptionWebhook auth_token =
    Api.request
        "POST"
        "/api/webhooks/paddle/subscription"
        []
        []
        []
        Nothing
        (Json.Decode.succeed ())
        |> Api.withBearerToken auth_token

{-| Write the per-tenant quota override (`admin:settings`). An empty object clears the override.
-}
putQuotaApi : Api.Data.QuotaOverride -> String -> Api.Request ()
putQuotaApi quotaOverride_body auth_token =
    Api.request
        "PUT"
        "/api/v1/quota"
        []
        []
        []
        (Maybe.map Http.jsonBody (Just (Api.Data.encodeQuotaOverride quotaOverride_body)))
        (Json.Decode.succeed ())
        |> Api.withBearerToken auth_token
