{-
   SimpleBilly API
   Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

   The version of the OpenAPI document: 0.1.0
   Contact: support@simplebilly.com

   NOTE: This file is auto generated by the openapi-generator.
   https://github.com/openapitools/openapi-generator.git

   DO NOT EDIT THIS FILE MANUALLY.

   For more info on generating Elm code, see https://eriktim.github.io/openapi-elm/
-}


module Api.Request.Bom exposing
    ( createBom
    , deleteBom
    , getBom
    , listBoms
    , updateBom
    )

import Api
import Api.Data exposing (..)
import Dict
import Http
import Json.Decode
import Json.Encode
import Uuid exposing (Uuid)


createBom : Api.Data.BomCreate -> String -> Api.Request Api.Data.Bom
createBom bomCreate_body auth_token =
    Api.request
        "POST"
        "/api/v1/boms"
        []
        []
        []
        (Maybe.map Http.jsonBody (Just (Api.Data.encodeBomCreate bomCreate_body)))
        Api.Data.bomDecoder
        |> Api.withBearerToken auth_token

deleteBom : Uuid -> String -> Api.Request ()
deleteBom bomId_path auth_token =
    Api.request
        "DELETE"
        "/api/v1/boms/{bom_id}"
        [ ( "bom_id", Uuid.toString bomId_path ) ]
        []
        []
        Nothing
        (Json.Decode.succeed ())
        |> Api.withBearerToken auth_token

getBom : Uuid -> String -> Api.Request Api.Data.Bom
getBom bomId_path auth_token =
    Api.request
        "GET"
        "/api/v1/boms/{bom_id}"
        [ ( "bom_id", Uuid.toString bomId_path ) ]
        []
        []
        Nothing
        Api.Data.bomDecoder
        |> Api.withBearerToken auth_token

listBoms : Maybe Int -> Maybe Int -> Maybe String -> Maybe Uuid -> String -> Api.Request (List Api.Data.Bom)
listBoms page_query pageSize_query search_query productId_query auth_token =
    Api.request
        "GET"
        "/api/v1/boms/"
        []
        [ ( "page", Maybe.map String.fromInt page_query ), ( "pageSize", Maybe.map String.fromInt pageSize_query ), ( "search", Maybe.map identity search_query ), ( "productId", Maybe.map Uuid.toString productId_query ) ]
        []
        Nothing
        (Json.Decode.list Api.Data.bomDecoder)
        |> Api.withBearerToken auth_token

updateBom : Uuid -> Api.Data.BomUpdate -> String -> Api.Request Api.Data.Bom
updateBom bomId_path bomUpdate_body auth_token =
    Api.request
        "PUT"
        "/api/v1/boms/{bom_id}"
        [ ( "bom_id", Uuid.toString bomId_path ) ]
        []
        []
        (Maybe.map Http.jsonBody (Just (Api.Data.encodeBomUpdate bomUpdate_body)))
        Api.Data.bomDecoder
        |> Api.withBearerToken auth_token
