{-
   SimpleBilly API
   Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

   The version of the OpenAPI document: 0.1.0
   Contact: support@simplebilly.com

   NOTE: This file is auto generated by the openapi-generator.
   https://github.com/openapitools/openapi-generator.git

   DO NOT EDIT THIS FILE MANUALLY.

   For more info on generating Elm code, see https://eriktim.github.io/openapi-elm/
-}


module Api.Request.Bookkeeping exposing
    ( allocatePaymentApi
    , bwaReportApi
    , elsterStatusApi
    , elsterValidateApi
    , elsterXmlApi
    , getCashflow
    , getLiquidity
    , getOpenInvoicesApi
    , getVerfahrensdokumentation
    , runDunningApi
    )

import Api
import Api.Data exposing (..)
import Dict
import Http
import Json.Decode
import Json.Encode


{-| Allocate a payment to an invoice
-}
allocatePaymentApi : Api.Data.AllocatePaymentRequest -> String -> Api.Request ()
allocatePaymentApi allocatePaymentRequest_body auth_token =
    Api.request
        "POST"
        "/api/v1/payments/allocate"
        []
        []
        []
        (Maybe.map Http.jsonBody (Just (Api.Data.encodeAllocatePaymentRequest allocatePaymentRequest_body)))
        (Json.Decode.succeed ())
        |> Api.withBearerToken auth_token

{-| Get BWA (Betriebswirtschaftliche Auswertung) report
-}
bwaReportApi : Maybe Int -> Maybe Int -> String -> Api.Request Api.Data.BWAReport
bwaReportApi year_query month_query auth_token =
    Api.request
        "GET"
        "/api/v1/bookkeeping/bwa"
        []
        [ ( "year", Maybe.map String.fromInt year_query ), ( "month", Maybe.map String.fromInt month_query ) ]
        []
        Nothing
        Api.Data.bWAReportDecoder
        |> Api.withBearerToken auth_token

elsterStatusApi : String -> Api.Request Api.Data.ElsterStatus
elsterStatusApi auth_token =
    Api.request
        "GET"
        "/api/v1/bookkeeping/elster/status"
        []
        []
        []
        Nothing
        Api.Data.elsterStatusDecoder
        |> Api.withBearerToken auth_token

elsterValidateApi : String -> String -> Api.Request ()
elsterValidateApi zeitraum_query auth_token =
    Api.request
        "POST"
        "/api/v1/bookkeeping/ustva/elster-validate"
        []
        [ ( "zeitraum", Just <| identity zeitraum_query ) ]
        []
        Nothing
        (Json.Decode.succeed ())
        |> Api.withBearerToken auth_token

elsterXmlApi : String -> String -> Api.Request ()
elsterXmlApi zeitraum_query auth_token =
    Api.request
        "GET"
        "/api/v1/bookkeeping/ustva/elster-xml"
        []
        [ ( "zeitraum", Just <| identity zeitraum_query ) ]
        []
        Nothing
        (Json.Decode.succeed ())
        |> Api.withBearerToken auth_token

{-| GET /api/v1/bookkeeping/cashflow Returns operating, investing, and financing cashflow for the given period.
-}
getCashflow : Maybe Int -> Maybe Int -> String -> Api.Request Api.Data.CashflowReport
getCashflow year_query month_query auth_token =
    Api.request
        "GET"
        "/api/v1/bookkeeping/cashflow"
        []
        [ ( "year", Maybe.map String.fromInt year_query ), ( "month", Maybe.map String.fromInt month_query ) ]
        []
        Nothing
        Api.Data.cashflowReportDecoder
        |> Api.withBearerToken auth_token

{-| GET /api/v1/bookkeeping/liquidity Returns current liquidity position with ratios.
-}
getLiquidity : String -> Api.Request Api.Data.LiquidityPosition
getLiquidity auth_token =
    Api.request
        "GET"
        "/api/v1/bookkeeping/liquidity"
        []
        []
        []
        Nothing
        Api.Data.liquidityPositionDecoder
        |> Api.withBearerToken auth_token

{-| Get open invoices for a customer
-}
getOpenInvoicesApi : String -> String -> Api.Request (List Api.Data.Invoice)
getOpenInvoicesApi customerId_path auth_token =
    Api.request
        "GET"
        "/api/v1/payments/open-invoices/{customer_id}"
        [ ( "customer_id", identity customerId_path ) ]
        []
        []
        Nothing
        (Json.Decode.list Api.Data.invoiceDecoder)
        |> Api.withBearerToken auth_token

{-| GET /api/v1/bookkeeping/verfahrensdokumentation Returns the complete compliance catalog of all documented modules.
-}
getVerfahrensdokumentation : String -> Api.Request Api.Data.Verfahrensdokumentation
getVerfahrensdokumentation auth_token =
    Api.request
        "GET"
        "/api/v1/bookkeeping/verfahrensdokumentation"
        []
        []
        []
        Nothing
        Api.Data.verfahrensdokumentationDecoder
        |> Api.withBearerToken auth_token

runDunningApi : String -> Api.Request Api.Data.DunningResult
runDunningApi auth_token =
    Api.request
        "POST"
        "/api/v1/bookkeeping/dunning"
        []
        []
        []
        Nothing
        Api.Data.dunningResultDecoder
        |> Api.withBearerToken auth_token
