{-
   SimpleBilly API
   Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

   The version of the OpenAPI document: 0.1.0
   Contact: support@simplebilly.com

   NOTE: This file is auto generated by the openapi-generator.
   https://github.com/openapitools/openapi-generator.git

   DO NOT EDIT THIS FILE MANUALLY.

   For more info on generating Elm code, see https://eriktim.github.io/openapi-elm/
-}


module Api.Request.Contact exposing
    ( contactSchema
    , contactTimeline
    , createContact
    , deleteContact
    , getContact
    , listContacts
    , salesVolume
    , updateContact
    )

import Api
import Api.Data exposing (..)
import Dict
import Http
import Json.Decode
import Json.Encode


{-| Serve JSON Schema for client-side validation
-}
contactSchema : String -> Api.Request Api.Data.AnyType
contactSchema auth_token =
    Api.request
        "GET"
        "/api/v1/contacts/schema"
        []
        []
        []
        Nothing
        Api.Data.anyTypeDecoder
        |> Api.withBearerToken auth_token

{-| Get the full per-contact timeline (Xentral §4.6/4.7).

Aggregates communications, quotations, orders, invoices and uploaded documents for a contact, merged into a single reverse-chronological feed.

-}
contactTimeline : String -> String -> Api.Request Api.Data.ContactTimelineResponse
contactTimeline contactId_path auth_token =
    Api.request
        "GET"
        "/api/v1/contacts/{contact_id}/timeline"
        [ ( "contact_id", identity contactId_path ) ]
        []
        []
        Nothing
        Api.Data.contactTimelineResponseDecoder
        |> Api.withBearerToken auth_token

{-| Create contact
-}
createContact : Api.Data.AnyType -> String -> Api.Request Api.Data.Contact
createContact body_body auth_token =
    Api.request
        "POST"
        "/api/v1/contacts"
        []
        []
        []
        (Maybe.map Http.jsonBody (Just (encodeAnyType body_body)))
        Api.Data.contactDecoder
        |> Api.withBearerToken auth_token

{-| Soft-delete contact
-}
deleteContact : String -> String -> Api.Request ()
deleteContact contactId_path auth_token =
    Api.request
        "DELETE"
        "/api/v1/contacts/{contact_id}"
        [ ( "contact_id", identity contactId_path ) ]
        []
        []
        Nothing
        (Json.Decode.succeed ())
        |> Api.withBearerToken auth_token

{-| Get single contact
-}
getContact : String -> String -> Api.Request Api.Data.Contact
getContact contactId_path auth_token =
    Api.request
        "GET"
        "/api/v1/contacts/{contact_id}"
        [ ( "contact_id", identity contactId_path ) ]
        []
        []
        Nothing
        Api.Data.contactDecoder
        |> Api.withBearerToken auth_token

{-| List contacts with search, type filter, and pagination
-}
listContacts : Maybe Int -> Maybe Int -> Maybe String -> Maybe String -> Maybe String -> String -> Api.Request (List Api.Data.Contact)
listContacts page_query pageSize_query search_query contactType_query tag_query auth_token =
    Api.request
        "GET"
        "/api/v1/contacts"
        []
        [ ( "page", Maybe.map String.fromInt page_query ), ( "page_size", Maybe.map String.fromInt pageSize_query ), ( "search", Maybe.map identity search_query ), ( "contact_type", Maybe.map identity contactType_query ), ( "tag", Maybe.map identity tag_query ) ]
        []
        Nothing
        (Json.Decode.list Api.Data.contactDecoder)
        |> Api.withBearerToken auth_token

{-| Sales volume per contact
-}
salesVolume : Maybe Int -> Maybe Int -> Maybe String -> Maybe String -> Maybe String -> String -> Api.Request Api.Data.SalesVolumeReport
salesVolume page_query pageSize_query search_query contactType_query tag_query auth_token =
    Api.request
        "GET"
        "/api/v1/contacts/sales-volume"
        []
        [ ( "page", Maybe.map String.fromInt page_query ), ( "page_size", Maybe.map String.fromInt pageSize_query ), ( "search", Maybe.map identity search_query ), ( "contact_type", Maybe.map identity contactType_query ), ( "tag", Maybe.map identity tag_query ) ]
        []
        Nothing
        Api.Data.salesVolumeReportDecoder
        |> Api.withBearerToken auth_token

{-| Update contact
-}
updateContact : String -> Api.Data.AnyType -> String -> Api.Request Api.Data.Contact
updateContact contactId_path body_body auth_token =
    Api.request
        "PUT"
        "/api/v1/contacts/{contact_id}"
        [ ( "contact_id", identity contactId_path ) ]
        []
        []
        (Maybe.map Http.jsonBody (Just (encodeAnyType body_body)))
        Api.Data.contactDecoder
        |> Api.withBearerToken auth_token
