{-
   SimpleBilly API
   Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

   The version of the OpenAPI document: 0.1.0
   Contact: support@simplebilly.com

   NOTE: This file is auto generated by the openapi-generator.
   https://github.com/openapitools/openapi-generator.git

   DO NOT EDIT THIS FILE MANUALLY.

   For more info on generating Elm code, see https://eriktim.github.io/openapi-elm/
-}


module Api.Request.Coupon exposing
    ( couponRestore
    , createCoupon
    , deleteCoupon
    , getCoupon
    , listCoupons
    , updateCoupon
    )

import Api
import Api.Data exposing (..)
import Dict
import Http
import Json.Decode
import Json.Encode


couponRestore : String -> String -> Api.Request Api.Data.Coupon
couponRestore couponId_path auth_token =
    Api.request
        "POST"
        "/api/v1/coupons/{coupon_id}/restore"
        [ ( "coupon_id", identity couponId_path ) ]
        []
        []
        Nothing
        Api.Data.couponDecoder
        |> Api.withBearerToken auth_token

createCoupon : Api.Data.CouponCreate -> String -> Api.Request Api.Data.Coupon
createCoupon couponCreate_body auth_token =
    Api.request
        "POST"
        "/api/v1/coupons"
        []
        []
        []
        (Maybe.map Http.jsonBody (Just (Api.Data.encodeCouponCreate couponCreate_body)))
        Api.Data.couponDecoder
        |> Api.withBearerToken auth_token

deleteCoupon : String -> String -> Api.Request ()
deleteCoupon couponId_path auth_token =
    Api.request
        "DELETE"
        "/api/v1/coupons/{coupon_id}"
        [ ( "coupon_id", identity couponId_path ) ]
        []
        []
        Nothing
        (Json.Decode.succeed ())
        |> Api.withBearerToken auth_token

getCoupon : String -> String -> Api.Request Api.Data.Coupon
getCoupon couponId_path auth_token =
    Api.request
        "GET"
        "/api/v1/coupons/{coupon_id}"
        [ ( "coupon_id", identity couponId_path ) ]
        []
        []
        Nothing
        Api.Data.couponDecoder
        |> Api.withBearerToken auth_token

listCoupons : Maybe Int -> Maybe Int -> Maybe Bool -> Maybe String -> Maybe String -> String -> Api.Request (List Api.Data.Coupon)
listCoupons page_query pageSize_query isActive_query code_query discountType_query auth_token =
    Api.request
        "GET"
        "/api/v1/coupons/"
        []
        [ ( "page", Maybe.map String.fromInt page_query ), ( "page_size", Maybe.map String.fromInt pageSize_query ), ( "is_active", Maybe.map (\val -> if val then "true" else "false") isActive_query ), ( "code", Maybe.map identity code_query ), ( "discount_type", Maybe.map identity discountType_query ) ]
        []
        Nothing
        (Json.Decode.list Api.Data.couponDecoder)
        |> Api.withBearerToken auth_token

updateCoupon : String -> Api.Data.CouponUpdate -> String -> Api.Request Api.Data.Coupon
updateCoupon couponId_path couponUpdate_body auth_token =
    Api.request
        "PUT"
        "/api/v1/coupons/{coupon_id}"
        [ ( "coupon_id", identity couponId_path ) ]
        []
        []
        (Maybe.map Http.jsonBody (Just (Api.Data.encodeCouponUpdate couponUpdate_body)))
        Api.Data.couponDecoder
        |> Api.withBearerToken auth_token
