{-
   SimpleBilly API
   Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

   The version of the OpenAPI document: 0.1.0
   Contact: support@simplebilly.com

   NOTE: This file is auto generated by the openapi-generator.
   https://github.com/openapitools/openapi-generator.git

   DO NOT EDIT THIS FILE MANUALLY.

   For more info on generating Elm code, see https://eriktim.github.io/openapi-elm/
-}


module Api.Request.CreateSepaDirectDebit exposing
    ( createSepaDirectDebitApi
    )

import Api
import Api.Data exposing (..)
import Dict
import Http
import Json.Decode
import Json.Encode


createSepaDirectDebitApi : String -> String -> String -> String -> String -> String -> String -> String -> String -> Maybe String -> Maybe String -> Maybe String -> String -> Api.Request Api.Data.SepaDirectDebitResponse
createSepaDirectDebitApi creditorName_query creditorIban_query creditorId_query mandateId_query mandateDate_query debtorName_query debtorIban_query amount_query collectionDate_query creditorBic_query debtorBic_query description_query auth_token =
    Api.request
        "POST"
        "/api/v1/bookkeeping/sepa-direct-debit"
        []
        [ ( "creditor_name", Just <| identity creditorName_query ), ( "creditor_iban", Just <| identity creditorIban_query ), ( "creditor_bic", Maybe.map identity creditorBic_query ), ( "creditor_id", Just <| identity creditorId_query ), ( "mandate_id", Just <| identity mandateId_query ), ( "mandate_date", Just <| identity mandateDate_query ), ( "debtor_name", Just <| identity debtorName_query ), ( "debtor_iban", Just <| identity debtorIban_query ), ( "debtor_bic", Maybe.map identity debtorBic_query ), ( "amount", Just <| identity amount_query ), ( "collection_date", Just <| identity collectionDate_query ), ( "description", Maybe.map identity description_query ) ]
        []
        Nothing
        Api.Data.sepaDirectDebitResponseDecoder
        |> Api.withBearerToken auth_token
