{-
   SimpleBilly API
   Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

   The version of the OpenAPI document: 0.1.0
   Contact: support@simplebilly.com

   NOTE: This file is auto generated by the openapi-generator.
   https://github.com/openapitools/openapi-generator.git

   DO NOT EDIT THIS FILE MANUALLY.

   For more info on generating Elm code, see https://eriktim.github.io/openapi-elm/
-}


module Api.Request.CreditNote exposing
    ( createCreditNote
    , downloadCreditNotePdf
    , getCreditNote
    , listCreditNotes
    )

import Api
import Api.Data exposing (..)
import Dict
import Http
import Json.Decode
import Json.Encode


createCreditNote : Api.Data.AnyType -> String -> Api.Request Api.Data.Invoice
createCreditNote body_body auth_token =
    Api.request
        "POST"
        "/api/v1/credit-notes"
        []
        []
        []
        (Maybe.map Http.jsonBody (Just (encodeAnyType body_body)))
        Api.Data.invoiceDecoder
        |> Api.withBearerToken auth_token

downloadCreditNotePdf : String -> String -> Api.Request ()
downloadCreditNotePdf creditNoteId_path auth_token =
    Api.request
        "GET"
        "/api/v1/credit-notes/{credit_note_id}/pdf"
        [ ( "credit_note_id", identity creditNoteId_path ) ]
        []
        []
        Nothing
        (Json.Decode.succeed ())
        |> Api.withBearerToken auth_token

getCreditNote : String -> String -> Api.Request Api.Data.Invoice
getCreditNote creditNoteId_path auth_token =
    Api.request
        "GET"
        "/api/v1/credit-notes/{credit_note_id}"
        [ ( "credit_note_id", identity creditNoteId_path ) ]
        []
        []
        Nothing
        Api.Data.invoiceDecoder
        |> Api.withBearerToken auth_token

listCreditNotes : Maybe Int -> Maybe Int -> Maybe String -> Maybe Bool -> String -> Api.Request (List Api.Data.Invoice)
listCreditNotes page_query pageSize_query search_query includeDeleted_query auth_token =
    Api.request
        "GET"
        "/api/v1/credit-notes/"
        []
        [ ( "page", Maybe.map String.fromInt page_query ), ( "page_size", Maybe.map String.fromInt pageSize_query ), ( "search", Maybe.map identity search_query ), ( "include_deleted", Maybe.map (\val -> if val then "true" else "false") includeDeleted_query ) ]
        []
        Nothing
        (Json.Decode.list Api.Data.invoiceDecoder)
        |> Api.withBearerToken auth_token
