{-
   SimpleBilly API
   Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

   The version of the OpenAPI document: 0.1.0
   Contact: support@simplebilly.com

   NOTE: This file is auto generated by the openapi-generator.
   https://github.com/openapitools/openapi-generator.git

   DO NOT EDIT THIS FILE MANUALLY.

   For more info on generating Elm code, see https://eriktim.github.io/openapi-elm/
-}


module Api.Request.CustomerCommunication exposing
    ( createCommunication
    , customercommunicationRestore
    , deleteCommunication
    , getCommunication
    , getContactHistory
    , listCommunications
    , updateCommunication
    )

import Api
import Api.Data exposing (..)
import Api.Time exposing (Posix)
import Dict
import Http
import Json.Decode
import Json.Encode


createCommunication : Api.Data.CustomerCommunicationCreate -> String -> Api.Request Api.Data.CustomerCommunication
createCommunication customerCommunicationCreate_body auth_token =
    Api.request
        "POST"
        "/api/v1/communications"
        []
        []
        []
        (Maybe.map Http.jsonBody (Just (Api.Data.encodeCustomerCommunicationCreate customerCommunicationCreate_body)))
        Api.Data.customerCommunicationDecoder
        |> Api.withBearerToken auth_token

customercommunicationRestore : String -> String -> Api.Request Api.Data.CustomerCommunication
customercommunicationRestore communicationId_path auth_token =
    Api.request
        "POST"
        "/api/v1/communications/{communication_id}/restore"
        [ ( "communication_id", identity communicationId_path ) ]
        []
        []
        Nothing
        Api.Data.customerCommunicationDecoder
        |> Api.withBearerToken auth_token

deleteCommunication : String -> String -> Api.Request ()
deleteCommunication communicationId_path auth_token =
    Api.request
        "DELETE"
        "/api/v1/communications/{communication_id}"
        [ ( "communication_id", identity communicationId_path ) ]
        []
        []
        Nothing
        (Json.Decode.succeed ())
        |> Api.withBearerToken auth_token

getCommunication : String -> String -> Api.Request Api.Data.CustomerCommunication
getCommunication communicationId_path auth_token =
    Api.request
        "GET"
        "/api/v1/communications/{communication_id}"
        [ ( "communication_id", identity communicationId_path ) ]
        []
        []
        Nothing
        Api.Data.customerCommunicationDecoder
        |> Api.withBearerToken auth_token

getContactHistory : String -> String -> Api.Request Api.Data.ContactHistoryResponse
getContactHistory contactId_path auth_token =
    Api.request
        "GET"
        "/api/v1/contacts/{contact_id}/communications"
        [ ( "contact_id", identity contactId_path ) ]
        []
        []
        Nothing
        Api.Data.contactHistoryResponseDecoder
        |> Api.withBearerToken auth_token

listCommunications : Maybe Int -> Maybe Int -> Maybe String -> Maybe Api.Data.CommunicationChannel -> Maybe Api.Data.CommunicationDirection -> Maybe Posix -> Maybe Posix -> String -> Api.Request (List Api.Data.CustomerCommunication)
listCommunications page_query pageSize_query contactId_query channel_query direction_query from_query to_query auth_token =
    Api.request
        "GET"
        "/api/v1/communications/"
        []
        [ ( "page", Maybe.map String.fromInt page_query ), ( "page_size", Maybe.map String.fromInt pageSize_query ), ( "contact_id", Maybe.map identity contactId_query ), ( "channel", Maybe.map Api.Data.stringFromCommunicationChannel channel_query ), ( "direction", Maybe.map Api.Data.stringFromCommunicationDirection direction_query ), ( "from", Maybe.map Api.Time.dateToString from_query ), ( "to", Maybe.map Api.Time.dateToString to_query ) ]
        []
        Nothing
        (Json.Decode.list Api.Data.customerCommunicationDecoder)
        |> Api.withBearerToken auth_token

updateCommunication : String -> Api.Data.CustomerCommunicationUpdate -> String -> Api.Request Api.Data.CustomerCommunication
updateCommunication communicationId_path customerCommunicationUpdate_body auth_token =
    Api.request
        "PUT"
        "/api/v1/communications/{communication_id}"
        [ ( "communication_id", identity communicationId_path ) ]
        []
        []
        (Maybe.map Http.jsonBody (Just (Api.Data.encodeCustomerCommunicationUpdate customerCommunicationUpdate_body)))
        Api.Data.customerCommunicationDecoder
        |> Api.withBearerToken auth_token
