{-
   SimpleBilly API
   Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

   The version of the OpenAPI document: 0.1.0
   Contact: support@simplebilly.com

   NOTE: This file is auto generated by the openapi-generator.
   https://github.com/openapitools/openapi-generator.git

   DO NOT EDIT THIS FILE MANUALLY.

   For more info on generating Elm code, see https://eriktim.github.io/openapi-elm/
-}


module Api.Request.CustomerGroup exposing
    ( addGroupMembers
    , createCustomerGroup
    , deleteCustomerGroup
    , getCustomerGroup
    , listCustomerGroups
    , updateCustomerGroup
    )

import Api
import Api.Data exposing (..)
import Dict
import Http
import Json.Decode
import Json.Encode


addGroupMembers : String -> Api.Data.AnyType -> String -> Api.Request Api.Data.CustomerGroup
addGroupMembers customerGroupId_path body_body auth_token =
    Api.request
        "POST"
        "/api/v1/customer-groups/{customer_group_id}/members"
        [ ( "customer_group_id", identity customerGroupId_path ) ]
        []
        []
        (Maybe.map Http.jsonBody (Just (encodeAnyType body_body)))
        Api.Data.customerGroupDecoder
        |> Api.withBearerToken auth_token

createCustomerGroup : Api.Data.CustomerGroupCreate -> String -> Api.Request Api.Data.CustomerGroup
createCustomerGroup customerGroupCreate_body auth_token =
    Api.request
        "POST"
        "/api/v1/customer-groups"
        []
        []
        []
        (Maybe.map Http.jsonBody (Just (Api.Data.encodeCustomerGroupCreate customerGroupCreate_body)))
        Api.Data.customerGroupDecoder
        |> Api.withBearerToken auth_token

deleteCustomerGroup : String -> String -> Api.Request ()
deleteCustomerGroup customerGroupId_path auth_token =
    Api.request
        "DELETE"
        "/api/v1/customer-groups/{customer_group_id}"
        [ ( "customer_group_id", identity customerGroupId_path ) ]
        []
        []
        Nothing
        (Json.Decode.succeed ())
        |> Api.withBearerToken auth_token

getCustomerGroup : String -> String -> Api.Request Api.Data.CustomerGroup
getCustomerGroup customerGroupId_path auth_token =
    Api.request
        "GET"
        "/api/v1/customer-groups/{customer_group_id}"
        [ ( "customer_group_id", identity customerGroupId_path ) ]
        []
        []
        Nothing
        Api.Data.customerGroupDecoder
        |> Api.withBearerToken auth_token

listCustomerGroups : Maybe Int -> Maybe Int -> Maybe String -> Maybe Bool -> String -> Api.Request (List Api.Data.CustomerGroup)
listCustomerGroups page_query pageSize_query search_query includeDeleted_query auth_token =
    Api.request
        "GET"
        "/api/v1/customer-groups/"
        []
        [ ( "page", Maybe.map String.fromInt page_query ), ( "page_size", Maybe.map String.fromInt pageSize_query ), ( "search", Maybe.map identity search_query ), ( "include_deleted", Maybe.map (\val -> if val then "true" else "false") includeDeleted_query ) ]
        []
        Nothing
        (Json.Decode.list Api.Data.customerGroupDecoder)
        |> Api.withBearerToken auth_token

updateCustomerGroup : String -> Api.Data.CustomerGroupUpdate -> String -> Api.Request Api.Data.CustomerGroup
updateCustomerGroup customerGroupId_path customerGroupUpdate_body auth_token =
    Api.request
        "PUT"
        "/api/v1/customer-groups/{customer_group_id}"
        [ ( "customer_group_id", identity customerGroupId_path ) ]
        []
        []
        (Maybe.map Http.jsonBody (Just (Api.Data.encodeCustomerGroupUpdate customerGroupUpdate_body)))
        Api.Data.customerGroupDecoder
        |> Api.withBearerToken auth_token
