{-
   SimpleBilly API
   Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

   The version of the OpenAPI document: 0.1.0
   Contact: support@simplebilly.com

   NOTE: This file is auto generated by the openapi-generator.
   https://github.com/openapitools/openapi-generator.git

   DO NOT EDIT THIS FILE MANUALLY.

   For more info on generating Elm code, see https://eriktim.github.io/openapi-elm/
-}


module Api.Request.Customer exposing
    ( createCustomer
    , customerRestore
    , deleteCustomer
    , getCustomer
    , getCustomers
    , updateCustomer
    )

import Api
import Api.Data exposing (..)
import Dict
import Http
import Json.Decode
import Json.Encode


createCustomer : Api.Data.CustomerCreate -> String -> Api.Request Api.Data.Customer
createCustomer customerCreate_body auth_token =
    Api.request
        "POST"
        "/api/v1/customers"
        []
        []
        []
        (Maybe.map Http.jsonBody (Just (Api.Data.encodeCustomerCreate customerCreate_body)))
        Api.Data.customerDecoder
        |> Api.withBearerToken auth_token

customerRestore : String -> String -> Api.Request Api.Data.Customer
customerRestore customerId_path auth_token =
    Api.request
        "POST"
        "/api/v1/customers/{customer_id}/restore"
        [ ( "customer_id", identity customerId_path ) ]
        []
        []
        Nothing
        Api.Data.customerDecoder
        |> Api.withBearerToken auth_token

deleteCustomer : String -> String -> Api.Request ()
deleteCustomer customerId_path auth_token =
    Api.request
        "DELETE"
        "/api/v1/customers/{customer_id}"
        [ ( "customer_id", identity customerId_path ) ]
        []
        []
        Nothing
        (Json.Decode.succeed ())
        |> Api.withBearerToken auth_token

getCustomer : String -> String -> Api.Request Api.Data.Customer
getCustomer customerId_path auth_token =
    Api.request
        "GET"
        "/api/v1/customers/{customer_id}"
        [ ( "customer_id", identity customerId_path ) ]
        []
        []
        Nothing
        Api.Data.customerDecoder
        |> Api.withBearerToken auth_token

getCustomers : Maybe Int -> Maybe Int -> Maybe String -> Maybe Bool -> String -> Api.Request (List Api.Data.Customer)
getCustomers page_query pageSize_query search_query includeDeleted_query auth_token =
    Api.request
        "GET"
        "/api/v1/customers/"
        []
        [ ( "page", Maybe.map String.fromInt page_query ), ( "page_size", Maybe.map String.fromInt pageSize_query ), ( "search", Maybe.map identity search_query ), ( "include_deleted", Maybe.map (\val -> if val then "true" else "false") includeDeleted_query ) ]
        []
        Nothing
        (Json.Decode.list Api.Data.customerDecoder)
        |> Api.withBearerToken auth_token

updateCustomer : String -> Api.Data.CustomerUpdate -> String -> Api.Request Api.Data.Customer
updateCustomer customerId_path customerUpdate_body auth_token =
    Api.request
        "PUT"
        "/api/v1/customers/{customer_id}"
        [ ( "customer_id", identity customerId_path ) ]
        []
        []
        (Maybe.map Http.jsonBody (Just (Api.Data.encodeCustomerUpdate customerUpdate_body)))
        Api.Data.customerDecoder
        |> Api.withBearerToken auth_token
