{-
   SimpleBilly API
   Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

   The version of the OpenAPI document: 0.1.0
   Contact: support@simplebilly.com

   NOTE: This file is auto generated by the openapi-generator.
   https://github.com/openapitools/openapi-generator.git

   DO NOT EDIT THIS FILE MANUALLY.

   For more info on generating Elm code, see https://eriktim.github.io/openapi-elm/
-}


module Api.Request.Datev exposing
    ( datevExportApi
    , datevPreviewApi
    )

import Api
import Api.Data exposing (..)
import Dict
import Http
import Json.Decode
import Json.Encode


{-| Export bookkeeping data as DATEV CSV
-}
datevExportApi : Maybe String -> Maybe String -> Maybe String -> Maybe Int -> Maybe Int -> String -> Api.Request Api.Data.DatevExportResponse
datevExportApi accountSchema_query dateFrom_query dateTo_query page_query pageSize_query auth_token =
    Api.request
        "GET"
        "/api/v1/bookkeeping/datev/export"
        []
        [ ( "account_schema", Maybe.map identity accountSchema_query ), ( "date_from", Maybe.map identity dateFrom_query ), ( "date_to", Maybe.map identity dateTo_query ), ( "page", Maybe.map String.fromInt page_query ), ( "page_size", Maybe.map String.fromInt pageSize_query ) ]
        []
        Nothing
        Api.Data.datevExportResponseDecoder
        |> Api.withBearerToken auth_token

{-| Exported_datev_bookings: returns formed bookings for review
-}
datevPreviewApi : Maybe String -> Maybe String -> Maybe String -> Maybe Int -> Maybe Int -> String -> Api.Request (List Api.Data.DatevBookingPreview)
datevPreviewApi accountSchema_query dateFrom_query dateTo_query page_query pageSize_query auth_token =
    Api.request
        "GET"
        "/api/v1/bookkeeping/datev/preview"
        []
        [ ( "account_schema", Maybe.map identity accountSchema_query ), ( "date_from", Maybe.map identity dateFrom_query ), ( "date_to", Maybe.map identity dateTo_query ), ( "page", Maybe.map String.fromInt page_query ), ( "page_size", Maybe.map String.fromInt pageSize_query ) ]
        []
        Nothing
        (Json.Decode.list Api.Data.datevBookingPreviewDecoder)
        |> Api.withBearerToken auth_token
