{-
   SimpleBilly API
   Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

   The version of the OpenAPI document: 0.1.0
   Contact: support@simplebilly.com

   NOTE: This file is auto generated by the openapi-generator.
   https://github.com/openapitools/openapi-generator.git

   DO NOT EDIT THIS FILE MANUALLY.

   For more info on generating Elm code, see https://eriktim.github.io/openapi-elm/
-}


module Api.Request.DeliveryAppointment exposing
    ( createDeliveryAppointment
    , deleteDeliveryAppointment
    , getDeliveryAppointment
    , getPublicDeliveryAppointmentStatus
    , listDeliveryAppointments
    , requestPublicDeliveryAppointment
    , updateDeliveryAppointment
    , updateDeliveryAppointmentStatus
    )

import Api
import Api.Data exposing (..)
import Api.Time exposing (Posix)
import Dict
import Http
import Json.Decode
import Json.Encode


createDeliveryAppointment : Api.Data.DeliveryAppointmentCreate -> String -> Api.Request Api.Data.DeliveryAppointment
createDeliveryAppointment deliveryAppointmentCreate_body auth_token =
    Api.request
        "POST"
        "/api/v1/delivery-appointments"
        []
        []
        []
        (Maybe.map Http.jsonBody (Just (Api.Data.encodeDeliveryAppointmentCreate deliveryAppointmentCreate_body)))
        Api.Data.deliveryAppointmentDecoder
        |> Api.withBearerToken auth_token

deleteDeliveryAppointment : String -> String -> Api.Request ()
deleteDeliveryAppointment appointmentId_path auth_token =
    Api.request
        "DELETE"
        "/api/v1/delivery-appointments/{appointment_id}"
        [ ( "appointment_id", identity appointmentId_path ) ]
        []
        []
        Nothing
        (Json.Decode.succeed ())
        |> Api.withBearerToken auth_token

getDeliveryAppointment : String -> String -> Api.Request Api.Data.DeliveryAppointment
getDeliveryAppointment appointmentId_path auth_token =
    Api.request
        "GET"
        "/api/v1/delivery-appointments/{appointment_id}"
        [ ( "appointment_id", identity appointmentId_path ) ]
        []
        []
        Nothing
        Api.Data.deliveryAppointmentDecoder
        |> Api.withBearerToken auth_token

{-| Supplier/carrier checks appointment status (public, no auth). The appointment is only revealed when email AND token match.
-}
getPublicDeliveryAppointmentStatus : String -> String -> String -> String -> Api.Request Api.Data.PublicDeliveryAppointmentStatusResponse
getPublicDeliveryAppointmentStatus appointmentId_query email_query token_query auth_token =
    Api.request
        "GET"
        "/api/v1/public/delivery-appointments/status"
        []
        [ ( "appointmentId", Just <| identity appointmentId_query ), ( "email", Just <| identity email_query ), ( "token", Just <| identity token_query ) ]
        []
        Nothing
        Api.Data.publicDeliveryAppointmentStatusResponseDecoder
        |> Api.withBearerToken auth_token

listDeliveryAppointments : Maybe Int -> Maybe Int -> Maybe String -> Maybe String -> Maybe Posix -> Maybe Posix -> String -> Api.Request (List Api.Data.DeliveryAppointment)
listDeliveryAppointments page_query pageSize_query status_query warehouseId_query from_query to_query auth_token =
    Api.request
        "GET"
        "/api/v1/delivery-appointments"
        []
        [ ( "page", Maybe.map String.fromInt page_query ), ( "page_size", Maybe.map String.fromInt pageSize_query ), ( "status", Maybe.map identity status_query ), ( "warehouse_id", Maybe.map identity warehouseId_query ), ( "from", Maybe.map Api.Time.dateToString from_query ), ( "to", Maybe.map Api.Time.dateToString to_query ) ]
        []
        Nothing
        (Json.Decode.list Api.Data.deliveryAppointmentDecoder)
        |> Api.withBearerToken auth_token

{-| Supplier/carrier requests an inbound delivery slot (public, no auth). The tenant is derived from the warehouse found by `code` — never from the request.
-}
requestPublicDeliveryAppointment : Api.Data.PublicDeliveryAppointmentRequest -> String -> Api.Request Api.Data.PublicDeliveryAppointmentResponse
requestPublicDeliveryAppointment publicDeliveryAppointmentRequest_body auth_token =
    Api.request
        "POST"
        "/api/v1/public/delivery-appointments/request"
        []
        []
        []
        (Maybe.map Http.jsonBody (Just (Api.Data.encodePublicDeliveryAppointmentRequest publicDeliveryAppointmentRequest_body)))
        Api.Data.publicDeliveryAppointmentResponseDecoder
        |> Api.withBearerToken auth_token

updateDeliveryAppointment : String -> Api.Data.AnyType -> String -> Api.Request Api.Data.DeliveryAppointment
updateDeliveryAppointment appointmentId_path body_body auth_token =
    Api.request
        "PUT"
        "/api/v1/delivery-appointments/{appointment_id}"
        [ ( "appointment_id", identity appointmentId_path ) ]
        []
        []
        (Maybe.map Http.jsonBody (Just (encodeAnyType body_body)))
        Api.Data.deliveryAppointmentDecoder
        |> Api.withBearerToken auth_token

updateDeliveryAppointmentStatus : String -> Api.Data.AppointmentStatusUpdate -> String -> Api.Request Api.Data.DeliveryAppointment
updateDeliveryAppointmentStatus appointmentId_path appointmentStatusUpdate_body auth_token =
    Api.request
        "PUT"
        "/api/v1/delivery-appointments/{appointment_id}/status"
        [ ( "appointment_id", identity appointmentId_path ) ]
        []
        []
        (Maybe.map Http.jsonBody (Just (Api.Data.encodeAppointmentStatusUpdate appointmentStatusUpdate_body)))
        Api.Data.deliveryAppointmentDecoder
        |> Api.withBearerToken auth_token
