{-
   SimpleBilly API
   Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

   The version of the OpenAPI document: 0.1.0
   Contact: support@simplebilly.com

   NOTE: This file is auto generated by the openapi-generator.
   https://github.com/openapitools/openapi-generator.git

   DO NOT EDIT THIS FILE MANUALLY.

   For more info on generating Elm code, see https://eriktim.github.io/openapi-elm/
-}


module Api.Request.DeliveryDate exposing
    ( createDeliveryDate
    , deleteDeliveryDate
    , getDeliveryDate
    , getDeliveryPerformance
    , listDeliveryDates
    , updateDeliveryDate
    , updateDeliveryDateStatus
    )

import Api
import Api.Data exposing (..)
import Api.Time exposing (Posix)
import Dict
import Http
import Json.Decode
import Json.Encode


createDeliveryDate : Api.Data.DeliveryDateCreate -> String -> Api.Request Api.Data.DeliveryDate
createDeliveryDate deliveryDateCreate_body auth_token =
    Api.request
        "POST"
        "/api/v1/delivery-dates"
        []
        []
        []
        (Maybe.map Http.jsonBody (Just (Api.Data.encodeDeliveryDateCreate deliveryDateCreate_body)))
        Api.Data.deliveryDateDecoder
        |> Api.withBearerToken auth_token

deleteDeliveryDate : String -> String -> Api.Request ()
deleteDeliveryDate deliveryDateId_path auth_token =
    Api.request
        "DELETE"
        "/api/v1/delivery-dates/{delivery_date_id}"
        [ ( "delivery_date_id", identity deliveryDateId_path ) ]
        []
        []
        Nothing
        (Json.Decode.succeed ())
        |> Api.withBearerToken auth_token

getDeliveryDate : String -> String -> Api.Request Api.Data.DeliveryDate
getDeliveryDate deliveryDateId_path auth_token =
    Api.request
        "GET"
        "/api/v1/delivery-dates/{delivery_date_id}"
        [ ( "delivery_date_id", identity deliveryDateId_path ) ]
        []
        []
        Nothing
        Api.Data.deliveryDateDecoder
        |> Api.withBearerToken auth_token

{-| On-time performance summary: how many promised delivery dates were met within a period.
-}
getDeliveryPerformance : Maybe Int -> Maybe Int -> Maybe String -> Maybe String -> Maybe Posix -> Maybe Posix -> String -> Api.Request Api.Data.AnyType
getDeliveryPerformance page_query pageSize_query orderNumber_query status_query from_query to_query auth_token =
    Api.request
        "GET"
        "/api/v1/delivery-dates/performance"
        []
        [ ( "page", Maybe.map String.fromInt page_query ), ( "pageSize", Maybe.map String.fromInt pageSize_query ), ( "orderNumber", Maybe.map identity orderNumber_query ), ( "status", Maybe.map identity status_query ), ( "from", Maybe.map Api.Time.dateToString from_query ), ( "to", Maybe.map Api.Time.dateToString to_query ) ]
        []
        Nothing
        Api.Data.anyTypeDecoder
        |> Api.withBearerToken auth_token

listDeliveryDates : Maybe Int -> Maybe Int -> Maybe String -> Maybe String -> Maybe Posix -> Maybe Posix -> String -> Api.Request (List Api.Data.DeliveryDate)
listDeliveryDates page_query pageSize_query orderNumber_query status_query from_query to_query auth_token =
    Api.request
        "GET"
        "/api/v1/delivery-dates/"
        []
        [ ( "page", Maybe.map String.fromInt page_query ), ( "pageSize", Maybe.map String.fromInt pageSize_query ), ( "orderNumber", Maybe.map identity orderNumber_query ), ( "status", Maybe.map identity status_query ), ( "from", Maybe.map Api.Time.dateToString from_query ), ( "to", Maybe.map Api.Time.dateToString to_query ) ]
        []
        Nothing
        (Json.Decode.list Api.Data.deliveryDateDecoder)
        |> Api.withBearerToken auth_token

updateDeliveryDate : String -> Api.Data.AnyType -> String -> Api.Request Api.Data.DeliveryDate
updateDeliveryDate deliveryDateId_path body_body auth_token =
    Api.request
        "PUT"
        "/api/v1/delivery-dates/{delivery_date_id}"
        [ ( "delivery_date_id", identity deliveryDateId_path ) ]
        []
        []
        (Maybe.map Http.jsonBody (Just (encodeAnyType body_body)))
        Api.Data.deliveryDateDecoder
        |> Api.withBearerToken auth_token

updateDeliveryDateStatus : String -> Api.Data.DeliveryDateStatusUpdate -> String -> Api.Request Api.Data.DeliveryDate
updateDeliveryDateStatus deliveryDateId_path deliveryDateStatusUpdate_body auth_token =
    Api.request
        "PUT"
        "/api/v1/delivery-dates/{delivery_date_id}/status"
        [ ( "delivery_date_id", identity deliveryDateId_path ) ]
        []
        []
        (Maybe.map Http.jsonBody (Just (Api.Data.encodeDeliveryDateStatusUpdate deliveryDateStatusUpdate_body)))
        Api.Data.deliveryDateDecoder
        |> Api.withBearerToken auth_token
