{-
   SimpleBilly API
   Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

   The version of the OpenAPI document: 0.1.0
   Contact: support@simplebilly.com

   NOTE: This file is auto generated by the openapi-generator.
   https://github.com/openapitools/openapi-generator.git

   DO NOT EDIT THIS FILE MANUALLY.

   For more info on generating Elm code, see https://eriktim.github.io/openapi-elm/
-}


module Api.Request.DeliveryNote exposing
    ( createDeliveryNote
    , deleteDeliveryNote
    , deliverynoteRestore
    , downloadDeliveryNotePdf
    , getDeliveryNote
    , listDeliveryNotes
    , pursueDeliveryNote
    )

import Api
import Api.Data exposing (..)
import Dict
import Http
import Json.Decode
import Json.Encode


createDeliveryNote : Api.Data.DeliveryNoteCreate -> String -> Api.Request Api.Data.DeliveryNote
createDeliveryNote deliveryNoteCreate_body auth_token =
    Api.request
        "POST"
        "/api/v1/delivery-notes"
        []
        []
        []
        (Maybe.map Http.jsonBody (Just (Api.Data.encodeDeliveryNoteCreate deliveryNoteCreate_body)))
        Api.Data.deliveryNoteDecoder
        |> Api.withBearerToken auth_token

deleteDeliveryNote : String -> String -> Api.Request ()
deleteDeliveryNote deliveryNoteId_path auth_token =
    Api.request
        "DELETE"
        "/api/v1/delivery-notes/{delivery_note_id}"
        [ ( "delivery_note_id", identity deliveryNoteId_path ) ]
        []
        []
        Nothing
        (Json.Decode.succeed ())
        |> Api.withBearerToken auth_token

deliverynoteRestore : String -> String -> Api.Request Api.Data.DeliveryNote
deliverynoteRestore deliveryNoteId_path auth_token =
    Api.request
        "POST"
        "/api/v1/delivery-notes/{delivery_note_id}/restore"
        [ ( "delivery_note_id", identity deliveryNoteId_path ) ]
        []
        []
        Nothing
        Api.Data.deliveryNoteDecoder
        |> Api.withBearerToken auth_token

downloadDeliveryNotePdf : String -> String -> Api.Request ()
downloadDeliveryNotePdf deliveryNoteId_path auth_token =
    Api.request
        "GET"
        "/api/v1/delivery-notes/{delivery_note_id}/pdf"
        [ ( "delivery_note_id", identity deliveryNoteId_path ) ]
        []
        []
        Nothing
        (Json.Decode.succeed ())
        |> Api.withBearerToken auth_token

getDeliveryNote : String -> String -> Api.Request Api.Data.DeliveryNote
getDeliveryNote deliveryNoteId_path auth_token =
    Api.request
        "GET"
        "/api/v1/delivery-notes/{delivery_note_id}"
        [ ( "delivery_note_id", identity deliveryNoteId_path ) ]
        []
        []
        Nothing
        Api.Data.deliveryNoteDecoder
        |> Api.withBearerToken auth_token

listDeliveryNotes : Maybe Int -> Maybe Int -> Maybe String -> Maybe Bool -> String -> Api.Request (List Api.Data.DeliveryNote)
listDeliveryNotes page_query pageSize_query search_query includeDeleted_query auth_token =
    Api.request
        "GET"
        "/api/v1/delivery-notes/"
        []
        [ ( "page", Maybe.map String.fromInt page_query ), ( "page_size", Maybe.map String.fromInt pageSize_query ), ( "search", Maybe.map identity search_query ), ( "include_deleted", Maybe.map (\val -> if val then "true" else "false") includeDeleted_query ) ]
        []
        Nothing
        (Json.Decode.list Api.Data.deliveryNoteDecoder)
        |> Api.withBearerToken auth_token

pursueDeliveryNote : String -> String -> Api.Request Api.Data.Invoice
pursueDeliveryNote deliveryNoteId_path auth_token =
    Api.request
        "POST"
        "/api/v1/delivery-notes/{delivery_note_id}/pursue"
        [ ( "delivery_note_id", identity deliveryNoteId_path ) ]
        []
        []
        Nothing
        Api.Data.invoiceDecoder
        |> Api.withBearerToken auth_token
