{-
   SimpleBilly API
   Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

   The version of the OpenAPI document: 0.1.0
   Contact: support@simplebilly.com

   NOTE: This file is auto generated by the openapi-generator.
   https://github.com/openapitools/openapi-generator.git

   DO NOT EDIT THIS FILE MANUALLY.

   For more info on generating Elm code, see https://eriktim.github.io/openapi-elm/
-}


module Api.Request.Ebilanz exposing
    ( ebilanzReportApi
    , ebilanzXbrlExportApi
    )

import Api
import Api.Data exposing (..)
import Dict
import Http
import Json.Decode
import Json.Encode


ebilanzReportApi : Maybe Int -> Maybe String -> Maybe String -> String -> Api.Request Api.Data.EBilanzReport
ebilanzReportApi year_query dateFrom_query dateTo_query auth_token =
    Api.request
        "GET"
        "/api/v1/bookkeeping/ebilanz"
        []
        [ ( "year", Maybe.map String.fromInt year_query ), ( "date_from", Maybe.map identity dateFrom_query ), ( "date_to", Maybe.map identity dateTo_query ) ]
        []
        Nothing
        Api.Data.eBilanzReportDecoder
        |> Api.withBearerToken auth_token

ebilanzXbrlExportApi : Maybe Int -> Maybe String -> Maybe String -> String -> Api.Request ()
ebilanzXbrlExportApi year_query dateFrom_query dateTo_query auth_token =
    Api.request
        "GET"
        "/api/v1/bookkeeping/ebilanz/xbrl"
        []
        [ ( "year", Maybe.map String.fromInt year_query ), ( "date_from", Maybe.map identity dateFrom_query ), ( "date_to", Maybe.map identity dateTo_query ) ]
        []
        Nothing
        (Json.Decode.succeed ())
        |> Api.withBearerToken auth_token
