{-
   SimpleBilly API
   Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

   The version of the OpenAPI document: 0.1.0
   Contact: support@simplebilly.com

   NOTE: This file is auto generated by the openapi-generator.
   https://github.com/openapitools/openapi-generator.git

   DO NOT EDIT THIS FILE MANUALLY.

   For more info on generating Elm code, see https://eriktim.github.io/openapi-elm/
-}


module Api.Request.EmailTemplate exposing
    ( createEmailTemplate
    , deleteEmailTemplate
    , getEmailTemplate
    , listEmailTemplates
    , renderEmailTemplate
    , updateEmailTemplate
    )

import Api
import Api.Data exposing (..)
import Dict
import Http
import Json.Decode
import Json.Encode


createEmailTemplate : Api.Data.EmailTemplateCreate -> String -> Api.Request Api.Data.EmailTemplate
createEmailTemplate emailTemplateCreate_body auth_token =
    Api.request
        "POST"
        "/api/v1/email-templates"
        []
        []
        []
        (Maybe.map Http.jsonBody (Just (Api.Data.encodeEmailTemplateCreate emailTemplateCreate_body)))
        Api.Data.emailTemplateDecoder
        |> Api.withBearerToken auth_token

deleteEmailTemplate : String -> String -> Api.Request ()
deleteEmailTemplate emailTemplateId_path auth_token =
    Api.request
        "DELETE"
        "/api/v1/email-templates/{email_template_id}"
        [ ( "email_template_id", identity emailTemplateId_path ) ]
        []
        []
        Nothing
        (Json.Decode.succeed ())
        |> Api.withBearerToken auth_token

getEmailTemplate : String -> String -> Api.Request Api.Data.EmailTemplate
getEmailTemplate emailTemplateId_path auth_token =
    Api.request
        "GET"
        "/api/v1/email-templates/{email_template_id}"
        [ ( "email_template_id", identity emailTemplateId_path ) ]
        []
        []
        Nothing
        Api.Data.emailTemplateDecoder
        |> Api.withBearerToken auth_token

listEmailTemplates : Maybe Int -> Maybe Int -> Maybe String -> Maybe String -> String -> Api.Request (List Api.Data.EmailTemplate)
listEmailTemplates page_query pageSize_query status_query search_query auth_token =
    Api.request
        "GET"
        "/api/v1/email-templates/"
        []
        [ ( "page", Maybe.map String.fromInt page_query ), ( "pageSize", Maybe.map String.fromInt pageSize_query ), ( "status", Maybe.map identity status_query ), ( "search", Maybe.map identity search_query ) ]
        []
        Nothing
        (Json.Decode.list Api.Data.emailTemplateDecoder)
        |> Api.withBearerToken auth_token

renderEmailTemplate : String -> Api.Data.AnyType -> String -> Api.Request Api.Data.AnyType
renderEmailTemplate emailTemplateId_path body_body auth_token =
    Api.request
        "POST"
        "/api/v1/email-templates/{email_template_id}/render"
        [ ( "email_template_id", identity emailTemplateId_path ) ]
        []
        []
        (Maybe.map Http.jsonBody (Just (encodeAnyType body_body)))
        Api.Data.anyTypeDecoder
        |> Api.withBearerToken auth_token

updateEmailTemplate : String -> Api.Data.EmailTemplateUpdate -> String -> Api.Request Api.Data.EmailTemplate
updateEmailTemplate emailTemplateId_path emailTemplateUpdate_body auth_token =
    Api.request
        "PUT"
        "/api/v1/email-templates/{email_template_id}"
        [ ( "email_template_id", identity emailTemplateId_path ) ]
        []
        []
        (Maybe.map Http.jsonBody (Just (Api.Data.encodeEmailTemplateUpdate emailTemplateUpdate_body)))
        Api.Data.emailTemplateDecoder
        |> Api.withBearerToken auth_token
