{-
   SimpleBilly API
   Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

   The version of the OpenAPI document: 0.1.0
   Contact: support@simplebilly.com

   NOTE: This file is auto generated by the openapi-generator.
   https://github.com/openapitools/openapi-generator.git

   DO NOT EDIT THIS FILE MANUALLY.

   For more info on generating Elm code, see https://eriktim.github.io/openapi-elm/
-}


module Api.Request.Emissions exposing
    ( createEmissionEntryApi
    , createEmissionTargetApi
    , deleteEmissionEntryApi
    , deleteEmissionTargetApi
    , emissionsEntriesApi
    , emissionsExportApi
    , emissionsFactorsApi
    , emissionsReportApi
    , emissionsTargetsApi
    )

import Api
import Api.Data exposing (..)
import Dict
import Http
import Json.Decode
import Json.Encode
import Uuid exposing (Uuid)


createEmissionEntryApi : Api.Data.CreateEmissionEntry -> String -> Api.Request Api.Data.EmissionEntry
createEmissionEntryApi createEmissionEntry_body auth_token =
    Api.request
        "POST"
        "/api/v1/bookkeeping/emissions/entries"
        []
        []
        []
        (Maybe.map Http.jsonBody (Just (Api.Data.encodeCreateEmissionEntry createEmissionEntry_body)))
        Api.Data.emissionEntryDecoder
        |> Api.withBearerToken auth_token

createEmissionTargetApi : Api.Data.CreateEmissionTarget -> String -> Api.Request Api.Data.EmissionTarget
createEmissionTargetApi createEmissionTarget_body auth_token =
    Api.request
        "POST"
        "/api/v1/bookkeeping/emissions/targets"
        []
        []
        []
        (Maybe.map Http.jsonBody (Just (Api.Data.encodeCreateEmissionTarget createEmissionTarget_body)))
        Api.Data.emissionTargetDecoder
        |> Api.withBearerToken auth_token

deleteEmissionEntryApi : Uuid -> String -> Api.Request ()
deleteEmissionEntryApi id_path auth_token =
    Api.request
        "DELETE"
        "/api/v1/bookkeeping/emissions/entries/{id}"
        [ ( "id", Uuid.toString id_path ) ]
        []
        []
        Nothing
        (Json.Decode.succeed ())
        |> Api.withBearerToken auth_token

deleteEmissionTargetApi : Uuid -> String -> Api.Request ()
deleteEmissionTargetApi id_path auth_token =
    Api.request
        "DELETE"
        "/api/v1/bookkeeping/emissions/targets/{id}"
        [ ( "id", Uuid.toString id_path ) ]
        []
        []
        Nothing
        (Json.Decode.succeed ())
        |> Api.withBearerToken auth_token

emissionsEntriesApi : Int -> String -> Api.Request (List Api.Data.EmissionEntry)
emissionsEntriesApi year_query auth_token =
    Api.request
        "GET"
        "/api/v1/bookkeeping/emissions/entries"
        []
        [ ( "year", Just <| String.fromInt year_query ) ]
        []
        Nothing
        (Json.Decode.list Api.Data.emissionEntryDecoder)
        |> Api.withBearerToken auth_token

emissionsExportApi : Int -> String -> Api.Request Api.Data.EmissionsExportResponse
emissionsExportApi year_query auth_token =
    Api.request
        "GET"
        "/api/v1/bookkeeping/emissions/export"
        []
        [ ( "year", Just <| String.fromInt year_query ) ]
        []
        Nothing
        Api.Data.emissionsExportResponseDecoder
        |> Api.withBearerToken auth_token

emissionsFactorsApi : String -> Api.Request (List Api.Data.EmissionFactorResponse)
emissionsFactorsApi auth_token =
    Api.request
        "GET"
        "/api/v1/bookkeeping/emissions/factors"
        []
        []
        []
        Nothing
        (Json.Decode.list Api.Data.emissionFactorResponseDecoder)
        |> Api.withBearerToken auth_token

emissionsReportApi : Int -> String -> Api.Request Api.Data.EmissionsReport
emissionsReportApi year_query auth_token =
    Api.request
        "GET"
        "/api/v1/bookkeeping/emissions/report"
        []
        [ ( "year", Just <| String.fromInt year_query ) ]
        []
        Nothing
        Api.Data.emissionsReportDecoder
        |> Api.withBearerToken auth_token

emissionsTargetsApi : String -> Api.Request (List Api.Data.EmissionTarget)
emissionsTargetsApi auth_token =
    Api.request
        "GET"
        "/api/v1/bookkeeping/emissions/targets"
        []
        []
        []
        Nothing
        (Json.Decode.list Api.Data.emissionTargetDecoder)
        |> Api.withBearerToken auth_token
