{-
   SimpleBilly API
   Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

   The version of the OpenAPI document: 0.1.0
   Contact: support@simplebilly.com

   NOTE: This file is auto generated by the openapi-generator.
   https://github.com/openapitools/openapi-generator.git

   DO NOT EDIT THIS FILE MANUALLY.

   For more info on generating Elm code, see https://eriktim.github.io/openapi-elm/
-}


module Api.Request.Employee exposing
    ( createEmployee
    , deleteEmployee
    , employeeRestore
    , getEmployee
    , getEmployeePayrollSummary
    , getEmployees
    , updateEmployee
    )

import Api
import Api.Data exposing (..)
import Dict
import Http
import Json.Decode
import Json.Encode
import Uuid exposing (Uuid)


createEmployee : Api.Data.EmployeeCreate -> String -> Api.Request Api.Data.Employee
createEmployee employeeCreate_body auth_token =
    Api.request
        "POST"
        "/api/v1/employees"
        []
        []
        []
        (Maybe.map Http.jsonBody (Just (Api.Data.encodeEmployeeCreate employeeCreate_body)))
        Api.Data.employeeDecoder
        |> Api.withBearerToken auth_token

deleteEmployee : Uuid -> String -> Api.Request ()
deleteEmployee id_path auth_token =
    Api.request
        "DELETE"
        "/api/v1/employees/{id}"
        [ ( "id", Uuid.toString id_path ) ]
        []
        []
        Nothing
        (Json.Decode.succeed ())
        |> Api.withBearerToken auth_token

employeeRestore : Uuid -> String -> Api.Request Api.Data.Employee
employeeRestore id_path auth_token =
    Api.request
        "POST"
        "/api/v1/employees/{id}/restore"
        [ ( "id", Uuid.toString id_path ) ]
        []
        []
        Nothing
        Api.Data.employeeDecoder
        |> Api.withBearerToken auth_token

getEmployee : Uuid -> String -> Api.Request Api.Data.Employee
getEmployee id_path auth_token =
    Api.request
        "GET"
        "/api/v1/employees/{id}"
        [ ( "id", Uuid.toString id_path ) ]
        []
        []
        Nothing
        Api.Data.employeeDecoder
        |> Api.withBearerToken auth_token

getEmployeePayrollSummary : Uuid -> Maybe Int -> String -> Api.Request Api.Data.PayrollSummary
getEmployeePayrollSummary id_path year_query auth_token =
    Api.request
        "GET"
        "/api/v1/employees/{id}/payroll-summary"
        [ ( "id", Uuid.toString id_path ) ]
        [ ( "year", Maybe.map String.fromInt year_query ) ]
        []
        Nothing
        Api.Data.payrollSummaryDecoder
        |> Api.withBearerToken auth_token

getEmployees : Maybe Int -> Maybe Int -> Maybe String -> Maybe Bool -> String -> Api.Request (List Api.Data.Employee)
getEmployees page_query pageSize_query search_query includeDeleted_query auth_token =
    Api.request
        "GET"
        "/api/v1/employees/"
        []
        [ ( "page", Maybe.map String.fromInt page_query ), ( "page_size", Maybe.map String.fromInt pageSize_query ), ( "search", Maybe.map identity search_query ), ( "include_deleted", Maybe.map (\val -> if val then "true" else "false") includeDeleted_query ) ]
        []
        Nothing
        (Json.Decode.list Api.Data.employeeDecoder)
        |> Api.withBearerToken auth_token

updateEmployee : Uuid -> Api.Data.EmployeeUpdate -> String -> Api.Request Api.Data.Employee
updateEmployee id_path employeeUpdate_body auth_token =
    Api.request
        "PUT"
        "/api/v1/employees/{id}"
        [ ( "id", Uuid.toString id_path ) ]
        []
        []
        (Maybe.map Http.jsonBody (Just (Api.Data.encodeEmployeeUpdate employeeUpdate_body)))
        Api.Data.employeeDecoder
        |> Api.withBearerToken auth_token
