{-
   SimpleBilly API
   Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

   The version of the OpenAPI document: 0.1.0
   Contact: support@simplebilly.com

   NOTE: This file is auto generated by the openapi-generator.
   https://github.com/openapitools/openapi-generator.git

   DO NOT EDIT THIS FILE MANUALLY.

   For more info on generating Elm code, see https://eriktim.github.io/openapi-elm/
-}


module Api.Request.EventSubscription exposing
    ( createEventSubscription
    , deleteEventSubscription
    , listEventSubscriptions
    )

import Api
import Api.Data exposing (..)
import Dict
import Http
import Json.Decode
import Json.Encode


createEventSubscription : Api.Data.AnyType -> String -> Api.Request Api.Data.EventSubscription
createEventSubscription body_body auth_token =
    Api.request
        "POST"
        "/api/v1/event-subscriptions"
        []
        []
        []
        (Maybe.map Http.jsonBody (Just (encodeAnyType body_body)))
        Api.Data.eventSubscriptionDecoder
        |> Api.withBearerToken auth_token

deleteEventSubscription : String -> String -> Api.Request ()
deleteEventSubscription subscriptionId_path auth_token =
    Api.request
        "DELETE"
        "/api/v1/event-subscriptions/{subscription_id}"
        [ ( "subscription_id", identity subscriptionId_path ) ]
        []
        []
        Nothing
        (Json.Decode.succeed ())
        |> Api.withBearerToken auth_token

listEventSubscriptions : String -> Api.Request (List Api.Data.EventSubscription)
listEventSubscriptions auth_token =
    Api.request
        "GET"
        "/api/v1/event-subscriptions/"
        []
        []
        []
        Nothing
        (Json.Decode.list Api.Data.eventSubscriptionDecoder)
        |> Api.withBearerToken auth_token
