{-
   SimpleBilly API
   Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

   The version of the OpenAPI document: 0.1.0
   Contact: support@simplebilly.com

   NOTE: This file is auto generated by the openapi-generator.
   https://github.com/openapitools/openapi-generator.git

   DO NOT EDIT THIS FILE MANUALLY.

   For more info on generating Elm code, see https://eriktim.github.io/openapi-elm/
-}


module Api.Request.Fristen exposing
    ( fristenApi
    )

import Api
import Api.Data exposing (..)
import Dict
import Http
import Json.Decode
import Json.Encode


fristenApi : Maybe String -> Maybe String -> Maybe Bool -> Maybe Bool -> Maybe Bool -> Maybe Int -> String -> Api.Request Api.Data.FristenErgebnis
fristenApi bundesland_query voranmeldungsrhythmus_query dauerfristverlaengerung_query estAktiv_query gewstAktiv_query monate_query auth_token =
    Api.request
        "GET"
        "/api/v1/bookkeeping/fristen"
        []
        [ ( "bundesland", Maybe.map identity bundesland_query ), ( "voranmeldungsrhythmus", Maybe.map identity voranmeldungsrhythmus_query ), ( "dauerfristverlaengerung", Maybe.map (\val -> if val then "true" else "false") dauerfristverlaengerung_query ), ( "est_aktiv", Maybe.map (\val -> if val then "true" else "false") estAktiv_query ), ( "gewst_aktiv", Maybe.map (\val -> if val then "true" else "false") gewstAktiv_query ), ( "monate", Maybe.map String.fromInt monate_query ) ]
        []
        Nothing
        Api.Data.fristenErgebnisDecoder
        |> Api.withBearerToken auth_token
