{-
   SimpleBilly API
   Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

   The version of the OpenAPI document: 0.1.0
   Contact: support@simplebilly.com

   NOTE: This file is auto generated by the openapi-generator.
   https://github.com/openapitools/openapi-generator.git

   DO NOT EDIT THIS FILE MANUALLY.

   For more info on generating Elm code, see https://eriktim.github.io/openapi-elm/
-}


module Api.Request.Gdpr exposing
    ( acceptDpa
    , accountErasure
    , erasureContact
    , exportContactData
    , exportGdpr
    , getDpa
    )

import Api
import Api.Data exposing (..)
import Dict
import Http
import Json.Decode
import Json.Encode


{-| Record DPA acceptance: sets dpa_accepted_at/by/version on the tenant settings row (created with company-type defaults if missing).
-}
acceptDpa : Api.Data.DpaAcceptRequest -> String -> Api.Request Api.Data.DpaStatus
acceptDpa dpaAcceptRequest_body auth_token =
    Api.request
        "PUT"
        "/api/v1/gdpr/dpa"
        []
        []
        []
        (Maybe.map Http.jsonBody (Just (Api.Data.encodeDpaAcceptRequest dpaAcceptRequest_body)))
        Api.Data.dpaStatusDecoder
        |> Api.withBearerToken auth_token

{-| Erase ALL personal data of the tenant (TOS §11: deletion 90 days after termination).

Anonymizes every contact, anonymizes personal fields on bookkeeping records (orders/invoices/payments keep amounts and dates for GoBD), removes the tenant linkage of the (global, saasy-framework) users and marks the erasure on `tenant_settings.gdpr_erased_at`. No row is physically deleted. The audit triggers on the touched tables record who/when.

-}
accountErasure : String -> Api.Request Api.Data.AnyType
accountErasure auth_token =
    Api.request
        "POST"
        "/api/v1/gdpr/account-erasure"
        []
        []
        []
        Nothing
        Api.Data.anyTypeDecoder
        |> Api.withBearerToken auth_token

{-| Anonymize + soft-delete a contact: personal attributes are cleared, the record itself is kept for GoBD retention (Art. 17(3)(e) DSGVO). The audit trigger on `contacts` already records who/when.
-}
erasureContact : String -> String -> Api.Request Api.Data.AnyType
erasureContact contactId_path auth_token =
    Api.request
        "POST"
        "/api/v1/gdpr/erasure/{contact_id}"
        [ ( "contact_id", identity contactId_path ) ]
        []
        []
        Nothing
        Api.Data.anyTypeDecoder
        |> Api.withBearerToken auth_token

{-| Art. 15 data-subject access export for a contact.

Returns the contact itself plus the tenant-scoped rows linked to it.  ## Relations The `customers`/`orders`/`invoices`/`payments` tables have no FK to `contacts`; they are linked through the `customer_id` column, which per the app's conventions holds one of: - the admin customer's `customer_id` (a UUID, often the same value as   the contact's `contact_id`/`customer_number`), - the buyer's email for shop orders, or - the marketplace's external customer id for plugin orders.  The export therefore matches the contact's identifiers (`contact_id`, `customer_number`, `external_id`, `email`) plus any resolved customer ids against `customer_id`. `delivery_notes` and `customer_communications` reference contacts directly via `contact_id`. Soft-deleted rows are included (their data is still processed and retained for GoBD). Relations that genuinely do not exist for a contact stay empty but the key is always present.

-}
exportContactData : String -> String -> Api.Request Api.Data.AnyType
exportContactData contactId_path auth_token =
    Api.request
        "GET"
        "/api/v1/gdpr/export/{contact_id}"
        [ ( "contact_id", identity contactId_path ) ]
        []
        []
        Nothing
        Api.Data.anyTypeDecoder
        |> Api.withBearerToken auth_token

{-| Export the current user's personal data (GDPR Art. 15/20).

No admin permission required: a user always exports their own data.

-}
exportGdpr : String -> Api.Request Api.Data.ApiResponseGdprExport
exportGdpr auth_token =
    Api.request
        "GET"
        "/api/v1/gdpr/export"
        []
        []
        []
        Nothing
        Api.Data.apiResponseGdprExportDecoder
        |> Api.withBearerToken auth_token

{-| Current DPA acceptance status (from tenant_settings).
-}
getDpa : String -> Api.Request Api.Data.DpaStatus
getDpa auth_token =
    Api.request
        "GET"
        "/api/v1/gdpr/dpa"
        []
        []
        []
        Nothing
        Api.Data.dpaStatusDecoder
        |> Api.withBearerToken auth_token
