{-
   SimpleBilly API
   Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

   The version of the OpenAPI document: 0.1.0
   Contact: support@simplebilly.com

   NOTE: This file is auto generated by the openapi-generator.
   https://github.com/openapitools/openapi-generator.git

   DO NOT EDIT THIS FILE MANUALLY.

   For more info on generating Elm code, see https://eriktim.github.io/openapi-elm/
-}


module Api.Request.GenerateXrechnung exposing
    ( generateXrechnungApi
    )

import Api
import Api.Data exposing (..)
import Dict
import Http
import Json.Decode
import Json.Encode


generateXrechnungApi : String -> Maybe String -> Maybe String -> Maybe String -> Maybe String -> Maybe String -> Maybe String -> String -> Api.Request Api.Data.XRechnungResponse
generateXrechnungApi id_path supplierName_query supplierStreet_query supplierCity_query supplierZip_query supplierCountry_query supplierVatId_query auth_token =
    Api.request
        "GET"
        "/api/v1/invoices/{id}/xrechnung"
        [ ( "id", identity id_path ) ]
        [ ( "supplier_name", Maybe.map identity supplierName_query ), ( "supplier_street", Maybe.map identity supplierStreet_query ), ( "supplier_city", Maybe.map identity supplierCity_query ), ( "supplier_zip", Maybe.map identity supplierZip_query ), ( "supplier_country", Maybe.map identity supplierCountry_query ), ( "supplier_vat_id", Maybe.map identity supplierVatId_query ) ]
        []
        Nothing
        Api.Data.xRechnungResponseDecoder
        |> Api.withBearerToken auth_token
