{-
   SimpleBilly API
   Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

   The version of the OpenAPI document: 0.1.0
   Contact: support@simplebilly.com

   NOTE: This file is auto generated by the openapi-generator.
   https://github.com/openapitools/openapi-generator.git

   DO NOT EDIT THIS FILE MANUALLY.

   For more info on generating Elm code, see https://eriktim.github.io/openapi-elm/
-}


module Api.Request.GenerateQrcode exposing
    ( generateQrcodeApi
    )

import Api
import Api.Data exposing (..)
import Dict
import Http
import Json.Decode
import Json.Encode


generateQrcodeApi : String -> String -> Maybe String -> Maybe String -> Maybe String -> Maybe String -> Maybe String -> String -> Api.Request Api.Data.QRCodeResponse
generateQrcodeApi id_path iban_query holderName_query bic_query amount_query reference_query purpose_query auth_token =
    Api.request
        "GET"
        "/api/v1/invoices/{id}/qrcode"
        [ ( "id", identity id_path ) ]
        [ ( "iban", Just <| identity iban_query ), ( "holder_name", Maybe.map identity holderName_query ), ( "bic", Maybe.map identity bic_query ), ( "amount", Maybe.map identity amount_query ), ( "reference", Maybe.map identity reference_query ), ( "purpose", Maybe.map identity purpose_query ) ]
        []
        Nothing
        Api.Data.qRCodeResponseDecoder
        |> Api.withBearerToken auth_token
