{-
   SimpleBilly API
   Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

   The version of the OpenAPI document: 0.1.0
   Contact: support@simplebilly.com

   NOTE: This file is auto generated by the openapi-generator.
   https://github.com/openapitools/openapi-generator.git

   DO NOT EDIT THIS FILE MANUALLY.

   For more info on generating Elm code, see https://eriktim.github.io/openapi-elm/
-}


module Api.Request.Gez exposing
    ( gezApi
    )

import Api
import Api.Data exposing (..)
import Dict
import Http
import Json.Decode
import Json.Encode


gezApi : Maybe Int -> Maybe String -> Maybe Int -> Maybe Int -> Maybe Int -> String -> Api.Request Api.Data.GezReport
gezApi jahr_query betriebsstaetten_query kfz_query hotelzimmer_query beschaefigte_query auth_token =
    Api.request
        "GET"
        "/api/v1/bookkeeping/gez"
        []
        [ ( "jahr", Maybe.map String.fromInt jahr_query ), ( "betriebsstaetten", Maybe.map identity betriebsstaetten_query ), ( "kfz", Maybe.map String.fromInt kfz_query ), ( "hotelzimmer", Maybe.map String.fromInt hotelzimmer_query ), ( "beschaefigte", Maybe.map String.fromInt beschaefigte_query ) ]
        []
        Nothing
        Api.Data.gezReportDecoder
        |> Api.withBearerToken auth_token
