{-
   SimpleBilly API
   Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

   The version of the OpenAPI document: 0.1.0
   Contact: support@simplebilly.com

   NOTE: This file is auto generated by the openapi-generator.
   https://github.com/openapitools/openapi-generator.git

   DO NOT EDIT THIS FILE MANUALLY.

   For more info on generating Elm code, see https://eriktim.github.io/openapi-elm/
-}


module Api.Request.GobdExport exposing
    ( buchhalterCsvApi
    , gobdExportApi
    )

import Api
import Api.Data exposing (..)
import Dict
import Http
import Json.Decode
import Json.Encode


buchhalterCsvApi : String -> String -> String -> Api.Request Api.Data.GoBDExportResponse
buchhalterCsvApi dateFrom_query dateTo_query auth_token =
    Api.request
        "GET"
        "/api/v1/bookkeeping/buchhalter-csv"
        []
        [ ( "date_from", Just <| identity dateFrom_query ), ( "date_to", Just <| identity dateTo_query ) ]
        []
        Nothing
        Api.Data.goBDExportResponseDecoder
        |> Api.withBearerToken auth_token

{-| GoBD/GDPdU export. Default: ZIP archive (`index.xml` + CSV tables, IDEA format). `?format=csv` returns the legacy single-journal CSV as JSON.
-}
gobdExportApi : Int -> Maybe String -> String -> Api.Request ()
gobdExportApi year_query format_query auth_token =
    Api.request
        "GET"
        "/api/v1/bookkeeping/gobd"
        []
        [ ( "year", Just <| String.fromInt year_query ), ( "format", Maybe.map identity format_query ) ]
        []
        Nothing
        (Json.Decode.succeed ())
        |> Api.withBearerToken auth_token
