{-
   SimpleBilly API
   Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

   The version of the OpenAPI document: 0.1.0
   Contact: support@simplebilly.com

   NOTE: This file is auto generated by the openapi-generator.
   https://github.com/openapitools/openapi-generator.git

   DO NOT EDIT THIS FILE MANUALLY.

   For more info on generating Elm code, see https://eriktim.github.io/openapi-elm/
-}


module Api.Request.GoodsReceipt exposing
    ( createGoodsReceipt
    , deleteGoodsReceipt
    , getGoodsReceipt
    , listGoodsReceipts
    )

import Api
import Api.Data exposing (..)
import Dict
import Http
import Json.Decode
import Json.Encode


createGoodsReceipt : Api.Data.GoodsReceipt -> String -> Api.Request Api.Data.GoodsReceipt
createGoodsReceipt goodsReceipt_body auth_token =
    Api.request
        "POST"
        "/api/v1/goods-receipts"
        []
        []
        []
        (Maybe.map Http.jsonBody (Just (Api.Data.encodeGoodsReceipt goodsReceipt_body)))
        Api.Data.goodsReceiptDecoder
        |> Api.withBearerToken auth_token

deleteGoodsReceipt : String -> String -> Api.Request ()
deleteGoodsReceipt goodsReceiptId_path auth_token =
    Api.request
        "DELETE"
        "/api/v1/goods-receipts/{goods_receipt_id}"
        [ ( "goods_receipt_id", identity goodsReceiptId_path ) ]
        []
        []
        Nothing
        (Json.Decode.succeed ())
        |> Api.withBearerToken auth_token

getGoodsReceipt : String -> String -> Api.Request Api.Data.GoodsReceipt
getGoodsReceipt goodsReceiptId_path auth_token =
    Api.request
        "GET"
        "/api/v1/goods-receipts/{goods_receipt_id}"
        [ ( "goods_receipt_id", identity goodsReceiptId_path ) ]
        []
        []
        Nothing
        Api.Data.goodsReceiptDecoder
        |> Api.withBearerToken auth_token

listGoodsReceipts : Maybe Int -> Maybe Int -> Maybe String -> Maybe String -> Maybe String -> String -> Api.Request (List Api.Data.GoodsReceipt)
listGoodsReceipts page_query pageSize_query purchaseOrderId_query supplierName_query warehouseId_query auth_token =
    Api.request
        "GET"
        "/api/v1/goods-receipts/"
        []
        [ ( "page", Maybe.map String.fromInt page_query ), ( "page_size", Maybe.map String.fromInt pageSize_query ), ( "purchase_order_id", Maybe.map identity purchaseOrderId_query ), ( "supplier_name", Maybe.map identity supplierName_query ), ( "warehouse_id", Maybe.map identity warehouseId_query ) ]
        []
        Nothing
        (Json.Decode.list Api.Data.goodsReceiptDecoder)
        |> Api.withBearerToken auth_token
