{-
   SimpleBilly API
   Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

   The version of the OpenAPI document: 0.1.0
   Contact: support@simplebilly.com

   NOTE: This file is auto generated by the openapi-generator.
   https://github.com/openapitools/openapi-generator.git

   DO NOT EDIT THIS FILE MANUALLY.

   For more info on generating Elm code, see https://eriktim.github.io/openapi-elm/
-}


module Api.Request.GroupFigure exposing
    ( createGroupFigure
    , deleteGroupFigure
    , getGroupFigure
    , getGroupFigures
    , updateGroupFigure
    )

import Api
import Api.Data exposing (..)
import Dict
import Http
import Json.Decode
import Json.Encode


createGroupFigure : Api.Data.GroupFigureCreate -> String -> Api.Request Api.Data.GroupFigure
createGroupFigure groupFigureCreate_body auth_token =
    Api.request
        "POST"
        "/api/v1/group-figures"
        []
        []
        []
        (Maybe.map Http.jsonBody (Just (Api.Data.encodeGroupFigureCreate groupFigureCreate_body)))
        Api.Data.groupFigureDecoder
        |> Api.withBearerToken auth_token

deleteGroupFigure : Int -> String -> Api.Request ()
deleteGroupFigure year_path auth_token =
    Api.request
        "DELETE"
        "/api/v1/group-figures/{year}"
        [ ( "year", String.fromInt year_path ) ]
        []
        []
        Nothing
        (Json.Decode.succeed ())
        |> Api.withBearerToken auth_token

getGroupFigure : Int -> String -> Api.Request Api.Data.GroupFigure
getGroupFigure year_path auth_token =
    Api.request
        "GET"
        "/api/v1/group-figures/{year}"
        [ ( "year", String.fromInt year_path ) ]
        []
        []
        Nothing
        Api.Data.groupFigureDecoder
        |> Api.withBearerToken auth_token

getGroupFigures : Maybe Int -> Maybe Int -> Maybe String -> Maybe Bool -> String -> Api.Request (List Api.Data.GroupFigure)
getGroupFigures page_query pageSize_query search_query includeDeleted_query auth_token =
    Api.request
        "GET"
        "/api/v1/group-figures/"
        []
        [ ( "page", Maybe.map String.fromInt page_query ), ( "page_size", Maybe.map String.fromInt pageSize_query ), ( "search", Maybe.map identity search_query ), ( "include_deleted", Maybe.map (\val -> if val then "true" else "false") includeDeleted_query ) ]
        []
        Nothing
        (Json.Decode.list Api.Data.groupFigureDecoder)
        |> Api.withBearerToken auth_token

updateGroupFigure : Int -> Api.Data.GroupFigureUpdate -> String -> Api.Request Api.Data.GroupFigure
updateGroupFigure year_path groupFigureUpdate_body auth_token =
    Api.request
        "PUT"
        "/api/v1/group-figures/{year}"
        [ ( "year", String.fromInt year_path ) ]
        []
        []
        (Maybe.map Http.jsonBody (Just (Api.Data.encodeGroupFigureUpdate groupFigureUpdate_body)))
        Api.Data.groupFigureDecoder
        |> Api.withBearerToken auth_token
