{-
   SimpleBilly API
   Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

   The version of the OpenAPI document: 0.1.0
   Contact: support@simplebilly.com

   NOTE: This file is auto generated by the openapi-generator.
   https://github.com/openapitools/openapi-generator.git

   DO NOT EDIT THIS FILE MANUALLY.

   For more info on generating Elm code, see https://eriktim.github.io/openapi-elm/
-}


module Api.Request.ImportRunner exposing
    ( getImportStatus
    , startImport
    , testImportConnection
    )

import Api
import Api.Data exposing (..)
import Dict
import Http
import Json.Decode
import Json.Encode


getImportStatus : String -> String -> Api.Request Api.Data.ImportJobStatus
getImportStatus jobId_path auth_token =
    Api.request
        "GET"
        "/api/v1/import/{job_id}"
        [ ( "job_id", identity jobId_path ) ]
        []
        []
        Nothing
        Api.Data.importJobStatusDecoder
        |> Api.withBearerToken auth_token

startImport : Api.Data.ImportStartRequest -> String -> Api.Request Api.Data.ImportStartResponse
startImport importStartRequest_body auth_token =
    Api.request
        "POST"
        "/api/v1/import/start"
        []
        []
        []
        (Maybe.map Http.jsonBody (Just (Api.Data.encodeImportStartRequest importStartRequest_body)))
        Api.Data.importStartResponseDecoder
        |> Api.withBearerToken auth_token

testImportConnection : Api.Data.ImportTestRequest -> String -> Api.Request Api.Data.ImportTestResponse
testImportConnection importTestRequest_body auth_token =
    Api.request
        "POST"
        "/api/v1/import/test"
        []
        []
        []
        (Maybe.map Http.jsonBody (Just (Api.Data.encodeImportTestRequest importTestRequest_body)))
        Api.Data.importTestResponseDecoder
        |> Api.withBearerToken auth_token
