{-
   SimpleBilly API
   Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

   The version of the OpenAPI document: 0.1.0
   Contact: support@simplebilly.com

   NOTE: This file is auto generated by the openapi-generator.
   https://github.com/openapitools/openapi-generator.git

   DO NOT EDIT THIS FILE MANUALLY.

   For more info on generating Elm code, see https://eriktim.github.io/openapi-elm/
-}


module Api.Request.InstituteProfile exposing
    ( getInstituteProfile
    , updateInstituteProfile
    )

import Api
import Api.Data exposing (..)
import Dict
import Http
import Json.Decode
import Json.Encode


{-| Current institute profile (created with defaults when missing).
-}
getInstituteProfile : String -> Api.Request Api.Data.InstituteProfile
getInstituteProfile auth_token =
    Api.request
        "GET"
        "/api/v1/institute-profile"
        []
        []
        []
        Nothing
        Api.Data.instituteProfileDecoder
        |> Api.withBearerToken auth_token

{-| Update the institute profile (institute_type and/or kapitalmarktorientiert).
-}
updateInstituteProfile : Api.Data.InstituteProfileUpdate -> String -> Api.Request Api.Data.InstituteProfile
updateInstituteProfile instituteProfileUpdate_body auth_token =
    Api.request
        "PUT"
        "/api/v1/institute-profile"
        []
        []
        []
        (Maybe.map Http.jsonBody (Just (Api.Data.encodeInstituteProfileUpdate instituteProfileUpdate_body)))
        Api.Data.instituteProfileDecoder
        |> Api.withBearerToken auth_token
