{-
   SimpleBilly API
   Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

   The version of the OpenAPI document: 0.1.0
   Contact: support@simplebilly.com

   NOTE: This file is auto generated by the openapi-generator.
   https://github.com/openapitools/openapi-generator.git

   DO NOT EDIT THIS FILE MANUALLY.

   For more info on generating Elm code, see https://eriktim.github.io/openapi-elm/
-}


module Api.Request.InventoryCount exposing
    ( createInventoryCount
    , deleteInventoryCount
    , generateInventoryCount
    , getInventoryCount
    , listInventoryCounts
    , updateInventoryCount
    , updateInventoryCountStatus
    )

import Api
import Api.Data exposing (..)
import Dict
import Http
import Json.Decode
import Json.Encode


createInventoryCount : Api.Data.InventoryCount -> String -> Api.Request Api.Data.InventoryCount
createInventoryCount inventoryCount_body auth_token =
    Api.request
        "POST"
        "/api/v1/inventory-counts"
        []
        []
        []
        (Maybe.map Http.jsonBody (Just (Api.Data.encodeInventoryCount inventoryCount_body)))
        Api.Data.inventoryCountDecoder
        |> Api.withBearerToken auth_token

deleteInventoryCount : String -> String -> Api.Request ()
deleteInventoryCount inventoryCountId_path auth_token =
    Api.request
        "DELETE"
        "/api/v1/inventory-counts/{inventory_count_id}"
        [ ( "inventory_count_id", identity inventoryCountId_path ) ]
        []
        []
        Nothing
        (Json.Decode.succeed ())
        |> Api.withBearerToken auth_token

generateInventoryCount : Api.Data.GenerateCountRequest -> String -> Api.Request Api.Data.InventoryCount
generateInventoryCount generateCountRequest_body auth_token =
    Api.request
        "POST"
        "/api/v1/inventory-counts/generate"
        []
        []
        []
        (Maybe.map Http.jsonBody (Just (Api.Data.encodeGenerateCountRequest generateCountRequest_body)))
        Api.Data.inventoryCountDecoder
        |> Api.withBearerToken auth_token

getInventoryCount : String -> String -> Api.Request Api.Data.InventoryCount
getInventoryCount inventoryCountId_path auth_token =
    Api.request
        "GET"
        "/api/v1/inventory-counts/{inventory_count_id}"
        [ ( "inventory_count_id", identity inventoryCountId_path ) ]
        []
        []
        Nothing
        Api.Data.inventoryCountDecoder
        |> Api.withBearerToken auth_token

listInventoryCounts : Maybe Int -> Maybe Int -> Maybe String -> Maybe String -> String -> Api.Request (List Api.Data.InventoryCount)
listInventoryCounts page_query pageSize_query status_query warehouseId_query auth_token =
    Api.request
        "GET"
        "/api/v1/inventory-counts/"
        []
        [ ( "page", Maybe.map String.fromInt page_query ), ( "page_size", Maybe.map String.fromInt pageSize_query ), ( "status", Maybe.map identity status_query ), ( "warehouse_id", Maybe.map identity warehouseId_query ) ]
        []
        Nothing
        (Json.Decode.list Api.Data.inventoryCountDecoder)
        |> Api.withBearerToken auth_token

updateInventoryCount : String -> Api.Data.AnyType -> String -> Api.Request Api.Data.InventoryCount
updateInventoryCount inventoryCountId_path body_body auth_token =
    Api.request
        "PUT"
        "/api/v1/inventory-counts/{inventory_count_id}"
        [ ( "inventory_count_id", identity inventoryCountId_path ) ]
        []
        []
        (Maybe.map Http.jsonBody (Just (encodeAnyType body_body)))
        Api.Data.inventoryCountDecoder
        |> Api.withBearerToken auth_token

updateInventoryCountStatus : String -> Api.Data.InventoryCountStatusUpdate -> String -> Api.Request Api.Data.InventoryCount
updateInventoryCountStatus inventoryCountId_path inventoryCountStatusUpdate_body auth_token =
    Api.request
        "PUT"
        "/api/v1/inventory-counts/{inventory_count_id}/status"
        [ ( "inventory_count_id", identity inventoryCountId_path ) ]
        []
        []
        (Maybe.map Http.jsonBody (Just (Api.Data.encodeInventoryCountStatusUpdate inventoryCountStatusUpdate_body)))
        Api.Data.inventoryCountDecoder
        |> Api.withBearerToken auth_token
