{-
   SimpleBilly API
   Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

   The version of the OpenAPI document: 0.1.0
   Contact: support@simplebilly.com

   NOTE: This file is auto generated by the openapi-generator.
   https://github.com/openapitools/openapi-generator.git

   DO NOT EDIT THIS FILE MANUALLY.

   For more info on generating Elm code, see https://eriktim.github.io/openapi-elm/
-}


module Api.Request.Invoice exposing
    ( createInvoice
    , deleteInvoice
    , downloadInvoicePdf
    , getInvoice
    , getInvoicePdfUrl
    , getInvoices
    , invoiceRestore
    , updateInvoice
    )

import Api
import Api.Data exposing (..)
import Dict
import Http
import Json.Decode
import Json.Encode


createInvoice : Api.Data.InvoiceCreate -> String -> Api.Request Api.Data.Invoice
createInvoice invoiceCreate_body auth_token =
    Api.request
        "POST"
        "/api/v1/invoices"
        []
        []
        []
        (Maybe.map Http.jsonBody (Just (Api.Data.encodeInvoiceCreate invoiceCreate_body)))
        Api.Data.invoiceDecoder
        |> Api.withBearerToken auth_token

deleteInvoice : String -> String -> Api.Request ()
deleteInvoice id_path auth_token =
    Api.request
        "DELETE"
        "/api/v1/invoices/{id}"
        [ ( "id", identity id_path ) ]
        []
        []
        Nothing
        (Json.Decode.succeed ())
        |> Api.withBearerToken auth_token

downloadInvoicePdf : String -> String -> Api.Request ()
downloadInvoicePdf id_path auth_token =
    Api.request
        "GET"
        "/api/v1/invoices/{id}/pdf"
        [ ( "id", identity id_path ) ]
        []
        []
        Nothing
        (Json.Decode.succeed ())
        |> Api.withBearerToken auth_token

getInvoice : String -> String -> Api.Request Api.Data.Invoice
getInvoice id_path auth_token =
    Api.request
        "GET"
        "/api/v1/invoices/{id}"
        [ ( "id", identity id_path ) ]
        []
        []
        Nothing
        Api.Data.invoiceDecoder
        |> Api.withBearerToken auth_token

getInvoicePdfUrl : String -> String -> Api.Request Api.Data.InvoicePdfUrlResponse
getInvoicePdfUrl id_path auth_token =
    Api.request
        "GET"
        "/api/v1/invoices/{id}/pdf-url"
        [ ( "id", identity id_path ) ]
        []
        []
        Nothing
        Api.Data.invoicePdfUrlResponseDecoder
        |> Api.withBearerToken auth_token

getInvoices : Maybe Int -> Maybe Int -> Maybe String -> Maybe Bool -> String -> Api.Request (List Api.Data.Invoice)
getInvoices page_query pageSize_query search_query includeDeleted_query auth_token =
    Api.request
        "GET"
        "/api/v1/invoices/"
        []
        [ ( "page", Maybe.map String.fromInt page_query ), ( "page_size", Maybe.map String.fromInt pageSize_query ), ( "search", Maybe.map identity search_query ), ( "include_deleted", Maybe.map (\val -> if val then "true" else "false") includeDeleted_query ) ]
        []
        Nothing
        (Json.Decode.list Api.Data.invoiceDecoder)
        |> Api.withBearerToken auth_token

invoiceRestore : String -> String -> Api.Request Api.Data.Invoice
invoiceRestore id_path auth_token =
    Api.request
        "POST"
        "/api/v1/invoices/{id}/restore"
        [ ( "id", identity id_path ) ]
        []
        []
        Nothing
        Api.Data.invoiceDecoder
        |> Api.withBearerToken auth_token

updateInvoice : String -> Api.Data.AnyType -> String -> Api.Request Api.Data.Invoice
updateInvoice id_path body_body auth_token =
    Api.request
        "PUT"
        "/api/v1/invoices/{id}"
        [ ( "id", identity id_path ) ]
        []
        []
        (Maybe.map Http.jsonBody (Just (encodeAnyType body_body)))
        Api.Data.invoiceDecoder
        |> Api.withBearerToken auth_token
