{-
   SimpleBilly API
   Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

   The version of the OpenAPI document: 0.1.0
   Contact: support@simplebilly.com

   NOTE: This file is auto generated by the openapi-generator.
   https://github.com/openapitools/openapi-generator.git

   DO NOT EDIT THIS FILE MANUALLY.

   For more info on generating Elm code, see https://eriktim.github.io/openapi-elm/
-}


module Api.Request.JobApplication exposing
    ( applyPublic
    , deleteJobApplication
    , downloadCv
    , getJobApplication
    , inboundEmail
    , listJobApplications
    , listPublicPostings
    , scoreJobApplication
    , updateJobApplicationStatus
    )

import Api
import Api.Data exposing (..)
import Dict
import Http
import Json.Decode
import Json.Encode
import Uuid exposing (Uuid)


applyPublic : Uuid -> String -> Api.Request ()
applyPublic postingId_path auth_token =
    Api.request
        "POST"
        "/api/v1/public/jobs/{posting_id}/apply"
        [ ( "posting_id", Uuid.toString postingId_path ) ]
        []
        []
        Nothing
        (Json.Decode.succeed ())
        |> Api.withBearerToken auth_token

deleteJobApplication : Uuid -> String -> Api.Request Api.Data.JobApplication
deleteJobApplication applicationId_path auth_token =
    Api.request
        "DELETE"
        "/api/v1/job-applications/{application_id}"
        [ ( "application_id", Uuid.toString applicationId_path ) ]
        []
        []
        Nothing
        Api.Data.jobApplicationDecoder
        |> Api.withBearerToken auth_token

downloadCv : Uuid -> String -> Api.Request ()
downloadCv applicationId_path auth_token =
    Api.request
        "GET"
        "/api/v1/job-applications/{application_id}/cv"
        [ ( "application_id", Uuid.toString applicationId_path ) ]
        []
        []
        Nothing
        (Json.Decode.succeed ())
        |> Api.withBearerToken auth_token

getJobApplication : Uuid -> String -> Api.Request Api.Data.JobApplication
getJobApplication applicationId_path auth_token =
    Api.request
        "GET"
        "/api/v1/job-applications/{application_id}"
        [ ( "application_id", Uuid.toString applicationId_path ) ]
        []
        []
        Nothing
        Api.Data.jobApplicationDecoder
        |> Api.withBearerToken auth_token

{-| Inbound CV email, mailgun/sendgrid inbound-parse style: multipart form with `from`, `subject`, `body-plain` and one or more `attachment-N` file fields. The subject may reference a posting as `[JOB-<posting_id>]`; without one the application lands in the general inbox.
-}
inboundEmail : String -> Api.Request ()
inboundEmail auth_token =
    Api.request
        "POST"
        "/api/v1/public/jobs/inbound-email"
        []
        []
        []
        Nothing
        (Json.Decode.succeed ())
        |> Api.withBearerToken auth_token

listJobApplications : Maybe Uuid -> Maybe String -> Maybe Int -> Maybe Int -> String -> Api.Request (List Api.Data.JobApplication)
listJobApplications postingId_query status_query page_query pageSize_query auth_token =
    Api.request
        "GET"
        "/api/v1/job-applications"
        []
        [ ( "postingId", Maybe.map Uuid.toString postingId_query ), ( "status", Maybe.map identity status_query ), ( "page", Maybe.map String.fromInt page_query ), ( "pageSize", Maybe.map String.fromInt pageSize_query ) ]
        []
        Nothing
        (Json.Decode.list Api.Data.jobApplicationDecoder)
        |> Api.withBearerToken auth_token

listPublicPostings : String -> Api.Request (List Api.Data.PublicPosting)
listPublicPostings auth_token =
    Api.request
        "GET"
        "/api/v1/public/jobs"
        []
        []
        []
        Nothing
        (Json.Decode.list Api.Data.publicPostingDecoder)
        |> Api.withBearerToken auth_token

scoreJobApplication : Uuid -> String -> Api.Request Api.Data.JobApplication
scoreJobApplication applicationId_path auth_token =
    Api.request
        "POST"
        "/api/v1/job-applications/{application_id}/score"
        [ ( "application_id", Uuid.toString applicationId_path ) ]
        []
        []
        Nothing
        Api.Data.jobApplicationDecoder
        |> Api.withBearerToken auth_token

updateJobApplicationStatus : Uuid -> Api.Data.ApplicationStatusDto -> String -> Api.Request Api.Data.JobApplication
updateJobApplicationStatus applicationId_path applicationStatusDto_body auth_token =
    Api.request
        "PATCH"
        "/api/v1/job-applications/{application_id}/status"
        [ ( "application_id", Uuid.toString applicationId_path ) ]
        []
        []
        (Maybe.map Http.jsonBody (Just (Api.Data.encodeApplicationStatusDto applicationStatusDto_body)))
        Api.Data.jobApplicationDecoder
        |> Api.withBearerToken auth_token
