{-
   SimpleBilly API
   Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

   The version of the OpenAPI document: 0.1.0
   Contact: support@simplebilly.com

   NOTE: This file is auto generated by the openapi-generator.
   https://github.com/openapitools/openapi-generator.git

   DO NOT EDIT THIS FILE MANUALLY.

   For more info on generating Elm code, see https://eriktim.github.io/openapi-elm/
-}


module Api.Request.JobPosting exposing
    ( createJobPosting
    , deleteJobPosting
    , getJobPosting
    , listJobPostings
    , updateJobPosting
    )

import Api
import Api.Data exposing (..)
import Dict
import Http
import Json.Decode
import Json.Encode
import Uuid exposing (Uuid)


createJobPosting : Api.Data.JobPostingCreate -> String -> Api.Request Api.Data.JobPosting
createJobPosting jobPostingCreate_body auth_token =
    Api.request
        "POST"
        "/api/v1/job-postings"
        []
        []
        []
        (Maybe.map Http.jsonBody (Just (Api.Data.encodeJobPostingCreate jobPostingCreate_body)))
        Api.Data.jobPostingDecoder
        |> Api.withBearerToken auth_token

deleteJobPosting : Uuid -> String -> Api.Request ()
deleteJobPosting id_path auth_token =
    Api.request
        "DELETE"
        "/api/v1/job-postings/{id}"
        [ ( "id", Uuid.toString id_path ) ]
        []
        []
        Nothing
        (Json.Decode.succeed ())
        |> Api.withBearerToken auth_token

getJobPosting : Uuid -> String -> Api.Request Api.Data.JobPosting
getJobPosting id_path auth_token =
    Api.request
        "GET"
        "/api/v1/job-postings/{id}"
        [ ( "id", Uuid.toString id_path ) ]
        []
        []
        Nothing
        Api.Data.jobPostingDecoder
        |> Api.withBearerToken auth_token

listJobPostings : Maybe String -> Maybe Int -> Maybe Int -> String -> Api.Request (List Api.Data.JobPosting)
listJobPostings status_query page_query pageSize_query auth_token =
    Api.request
        "GET"
        "/api/v1/job-postings"
        []
        [ ( "status", Maybe.map identity status_query ), ( "page", Maybe.map String.fromInt page_query ), ( "pageSize", Maybe.map String.fromInt pageSize_query ) ]
        []
        Nothing
        (Json.Decode.list Api.Data.jobPostingDecoder)
        |> Api.withBearerToken auth_token

updateJobPosting : Uuid -> Api.Data.JobPostingUpdate -> String -> Api.Request Api.Data.JobPosting
updateJobPosting id_path jobPostingUpdate_body auth_token =
    Api.request
        "PUT"
        "/api/v1/job-postings/{id}"
        [ ( "id", Uuid.toString id_path ) ]
        []
        []
        (Maybe.map Http.jsonBody (Just (Api.Data.encodeJobPostingUpdate jobPostingUpdate_body)))
        Api.Data.jobPostingDecoder
        |> Api.withBearerToken auth_token
