{-
   SimpleBilly API
   Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

   The version of the OpenAPI document: 0.1.0
   Contact: support@simplebilly.com

   NOTE: This file is auto generated by the openapi-generator.
   https://github.com/openapitools/openapi-generator.git

   DO NOT EDIT THIS FILE MANUALLY.

   For more info on generating Elm code, see https://eriktim.github.io/openapi-elm/
-}


module Api.Request.KostenVorschau exposing
    ( kostenVorschauApi
    )

import Api
import Api.Data exposing (..)
import Dict
import Http
import Json.Decode
import Json.Encode


kostenVorschauApi : Int -> Int -> String -> Api.Request Api.Data.KostenVorschau
kostenVorschauApi year_query month_query auth_token =
    Api.request
        "GET"
        "/api/v1/bookkeeping/kosten-vorschau"
        []
        [ ( "year", Just <| String.fromInt year_query ), ( "month", Just <| String.fromInt month_query ) ]
        []
        Nothing
        Api.Data.kostenVorschauDecoder
        |> Api.withBearerToken auth_token
