{-
   SimpleBilly API
   Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

   The version of the OpenAPI document: 0.1.0
   Contact: support@simplebilly.com

   NOTE: This file is auto generated by the openapi-generator.
   https://github.com/openapitools/openapi-generator.git

   DO NOT EDIT THIS FILE MANUALLY.

   For more info on generating Elm code, see https://eriktim.github.io/openapi-elm/
-}


module Api.Request.Lead exposing
    ( listLeadsApi
    , updateLeadApi
    )

import Api
import Api.Data exposing (..)
import Dict
import Http
import Json.Decode
import Json.Encode
import Uuid exposing (Uuid)


listLeadsApi : Maybe String -> Maybe String -> Maybe String -> Maybe Int -> Maybe Int -> String -> Api.Request (List Api.Data.Lead)
listLeadsApi status_query source_query search_query page_query pageSize_query auth_token =
    Api.request
        "GET"
        "/api/v1/support/leads"
        []
        [ ( "status", Maybe.map identity status_query ), ( "source", Maybe.map identity source_query ), ( "search", Maybe.map identity search_query ), ( "page", Maybe.map String.fromInt page_query ), ( "page_size", Maybe.map String.fromInt pageSize_query ) ]
        []
        Nothing
        (Json.Decode.list Api.Data.leadDecoder)
        |> Api.withBearerToken auth_token

updateLeadApi : Uuid -> Api.Data.LeadUpdate -> String -> Api.Request Api.Data.Lead
updateLeadApi leadId_path leadUpdate_body auth_token =
    Api.request
        "PUT"
        "/api/v1/support/leads/{lead_id}"
        [ ( "lead_id", Uuid.toString leadId_path ) ]
        []
        []
        (Maybe.map Http.jsonBody (Just (Api.Data.encodeLeadUpdate leadUpdate_body)))
        Api.Data.leadDecoder
        |> Api.withBearerToken auth_token
