{-
   SimpleBilly API
   Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

   The version of the OpenAPI document: 0.1.0
   Contact: support@simplebilly.com

   NOTE: This file is auto generated by the openapi-generator.
   https://github.com/openapitools/openapi-generator.git

   DO NOT EDIT THIS FILE MANUALLY.

   For more info on generating Elm code, see https://eriktim.github.io/openapi-elm/
-}


module Api.Request.LegalDocument exposing
    ( getLegalDocuments
    , resetLegalDocuments
    , upsertLegalDocuments
    )

import Api
import Api.Data exposing (..)
import Dict
import Http
import Json.Decode
import Json.Encode


{-| List all legal documents of the tenant. Missing documents are seeded from the default texts (with tenant placeholders replaced) on first access.
-}
getLegalDocuments : String -> Api.Request (List Api.Data.LegalDocument)
getLegalDocuments auth_token =
    Api.request
        "GET"
        "/api/v1/legal/documents"
        []
        []
        []
        Nothing
        (Json.Decode.list Api.Data.legalDocumentDecoder)
        |> Api.withBearerToken auth_token

{-| Restore default texts for all documents (or a single doc_type/lang when the optional filter is given). Returns the full tenant list.
-}
resetLegalDocuments : Api.Data.LegalDocumentReset -> String -> Api.Request (List Api.Data.LegalDocument)
resetLegalDocuments legalDocumentReset_body auth_token =
    Api.request
        "POST"
        "/api/v1/legal/documents/reset"
        []
        []
        []
        (Maybe.map Http.jsonBody (Just (Api.Data.encodeLegalDocumentReset legalDocumentReset_body)))
        (Json.Decode.list Api.Data.legalDocumentDecoder)
        |> Api.withBearerToken auth_token

{-| Upsert legal documents per (doc_type, lang). Returns the full tenant list.
-}
upsertLegalDocuments : List Api.Data.LegalDocumentUpsert -> String -> Api.Request (List Api.Data.LegalDocument)
upsertLegalDocuments legalDocumentUpsert_body auth_token =
    Api.request
        "PUT"
        "/api/v1/legal/documents"
        []
        []
        []
        (Maybe.map Http.jsonBody (Just (Json.Encode.list encodeLegalDocumentUpsert legalDocumentUpsert_body)))
        (Json.Decode.list Api.Data.legalDocumentDecoder)
        |> Api.withBearerToken auth_token
