{-
   SimpleBilly API
   Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

   The version of the OpenAPI document: 0.1.0
   Contact: support@simplebilly.com

   NOTE: This file is auto generated by the openapi-generator.
   https://github.com/openapitools/openapi-generator.git

   DO NOT EDIT THIS FILE MANUALLY.

   For more info on generating Elm code, see https://eriktim.github.io/openapi-elm/
-}


module Api.Request.ListOpenItems exposing
    ( listOpenItemsApi
    )

import Api
import Api.Data exposing (..)
import Dict
import Http
import Json.Decode
import Json.Encode


listOpenItemsApi : Maybe Int -> Maybe Int -> Maybe Int -> Maybe String -> String -> Api.Request (List Api.Data.OpenItem)
listOpenItemsApi reminderLevel1Days_query reminderLevel2Days_query reminderLevel3Days_query customerId_query auth_token =
    Api.request
        "GET"
        "/api/v1/bookkeeping/open-items"
        []
        [ ( "reminder_level1_days", Maybe.map String.fromInt reminderLevel1Days_query ), ( "reminder_level2_days", Maybe.map String.fromInt reminderLevel2Days_query ), ( "reminder_level3_days", Maybe.map String.fromInt reminderLevel3Days_query ), ( "customer_id", Maybe.map identity customerId_query ) ]
        []
        Nothing
        (Json.Decode.list Api.Data.openItemDecoder)
        |> Api.withBearerToken auth_token
