{-
   SimpleBilly API
   Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

   The version of the OpenAPI document: 0.1.0
   Contact: support@simplebilly.com

   NOTE: This file is auto generated by the openapi-generator.
   https://github.com/openapitools/openapi-generator.git

   DO NOT EDIT THIS FILE MANUALLY.

   For more info on generating Elm code, see https://eriktim.github.io/openapi-elm/
-}


module Api.Request.MarketplaceApi exposing
    ( createConnectionApi
    , deleteConnectionApi
    , getConnectionApi
    , getSyncDirectionApi
    , getSyncLogsApi
    , listConnectionsApi
    , listPlatformsApi
    , oauthAuthorizeApi
    , oauthCallbackApi
    , triggerSyncApi
    , updateConnectionApi
    , updateSyncDirectionApi
    , webhookReceiverApi
    )

import Api
import Api.Data exposing (..)
import Dict
import Http
import Json.Decode
import Json.Encode


{-| Create a new connection (for API-key based platforms)
-}
createConnectionApi : Api.Data.CreateConnectionRequest -> String -> Api.Request Api.Data.MarketplaceConnection
createConnectionApi createConnectionRequest_body auth_token =
    Api.request
        "POST"
        "/api/v1/marketplace/connections"
        []
        []
        []
        (Maybe.map Http.jsonBody (Just (Api.Data.encodeCreateConnectionRequest createConnectionRequest_body)))
        Api.Data.marketplaceConnectionDecoder
        |> Api.withBearerToken auth_token

{-| Soft-delete a connection
-}
deleteConnectionApi : String -> String -> Api.Request ()
deleteConnectionApi connectionId_path auth_token =
    Api.request
        "DELETE"
        "/api/v1/marketplace/connections/{connection_id}"
        [ ( "connection_id", identity connectionId_path ) ]
        []
        []
        Nothing
        (Json.Decode.succeed ())
        |> Api.withBearerToken auth_token

{-| Get a single connection
-}
getConnectionApi : String -> String -> Api.Request Api.Data.MarketplaceConnection
getConnectionApi connectionId_path auth_token =
    Api.request
        "GET"
        "/api/v1/marketplace/connections/{connection_id}"
        [ ( "connection_id", identity connectionId_path ) ]
        []
        []
        Nothing
        Api.Data.marketplaceConnectionDecoder
        |> Api.withBearerToken auth_token

{-| Get current sync direction configuration for a connection
-}
getSyncDirectionApi : String -> String -> Api.Request ()
getSyncDirectionApi connectionId_path auth_token =
    Api.request
        "GET"
        "/api/v1/marketplace/connections/{connection_id}/directions"
        [ ( "connection_id", identity connectionId_path ) ]
        []
        []
        Nothing
        (Json.Decode.succeed ())
        |> Api.withBearerToken auth_token

{-| Get sync logs for a connection
-}
getSyncLogsApi : String -> String -> Api.Request (List Api.Data.SyncLog)
getSyncLogsApi connectionId_path auth_token =
    Api.request
        "GET"
        "/api/v1/marketplace/connections/{connection_id}/logs"
        [ ( "connection_id", identity connectionId_path ) ]
        []
        []
        Nothing
        (Json.Decode.list Api.Data.syncLogDecoder)
        |> Api.withBearerToken auth_token

{-| List connections for the current tenant
-}
listConnectionsApi : String -> Api.Request (List Api.Data.MarketplaceConnection)
listConnectionsApi auth_token =
    Api.request
        "GET"
        "/api/v1/marketplace/connections"
        []
        []
        []
        Nothing
        (Json.Decode.list Api.Data.marketplaceConnectionDecoder)
        |> Api.withBearerToken auth_token

{-| List all supported platforms
-}
listPlatformsApi : String -> Api.Request (List Api.Data.PlatformInfo)
listPlatformsApi auth_token =
    Api.request
        "GET"
        "/api/v1/marketplace/platforms"
        []
        []
        []
        Nothing
        (Json.Decode.list Api.Data.platformInfoDecoder)
        |> Api.withBearerToken auth_token

{-| OAuth: initiate authorization flow
-}
oauthAuthorizeApi : Api.Data.OAuthAuthorizeRequest -> String -> Api.Request Api.Data.OAuthAuthorizeResponse
oauthAuthorizeApi oAuthAuthorizeRequest_body auth_token =
    Api.request
        "POST"
        "/api/v1/marketplace/oauth/authorize"
        []
        []
        []
        (Maybe.map Http.jsonBody (Just (Api.Data.encodeOAuthAuthorizeRequest oAuthAuthorizeRequest_body)))
        Api.Data.oAuthAuthorizeResponseDecoder
        |> Api.withBearerToken auth_token

{-| OAuth: handle callback after authorization
-}
oauthCallbackApi : Api.Data.OAuthCallbackRequest -> String -> Api.Request Api.Data.MarketplaceConnection
oauthCallbackApi oAuthCallbackRequest_body auth_token =
    Api.request
        "POST"
        "/api/v1/marketplace/oauth/callback"
        []
        []
        []
        (Maybe.map Http.jsonBody (Just (Api.Data.encodeOAuthCallbackRequest oAuthCallbackRequest_body)))
        Api.Data.marketplaceConnectionDecoder
        |> Api.withBearerToken auth_token

{-| Trigger sync for a connection
-}
triggerSyncApi : String -> Maybe String -> Maybe String -> String -> Api.Request Api.Data.SyncSummary
triggerSyncApi connectionId_path syncType_query direction_query auth_token =
    Api.request
        "POST"
        "/api/v1/marketplace/connections/{connection_id}/sync"
        [ ( "connection_id", identity connectionId_path ) ]
        [ ( "sync_type", Maybe.map identity syncType_query ), ( "direction", Maybe.map identity direction_query ) ]
        []
        Nothing
        Api.Data.syncSummaryDecoder
        |> Api.withBearerToken auth_token

{-| Update a connection
-}
updateConnectionApi : String -> Api.Data.UpdateConnectionRequest -> String -> Api.Request Api.Data.MarketplaceConnection
updateConnectionApi connectionId_path updateConnectionRequest_body auth_token =
    Api.request
        "PUT"
        "/api/v1/marketplace/connections/{connection_id}"
        [ ( "connection_id", identity connectionId_path ) ]
        []
        []
        (Maybe.map Http.jsonBody (Just (Api.Data.encodeUpdateConnectionRequest updateConnectionRequest_body)))
        Api.Data.marketplaceConnectionDecoder
        |> Api.withBearerToken auth_token

{-| Update per-entity sync direction configuration for a connection
-}
updateSyncDirectionApi : String -> Api.Data.UpdateSyncDirectionRequest -> String -> Api.Request ()
updateSyncDirectionApi connectionId_path updateSyncDirectionRequest_body auth_token =
    Api.request
        "PUT"
        "/api/v1/marketplace/connections/{connection_id}/directions"
        [ ( "connection_id", identity connectionId_path ) ]
        []
        []
        (Maybe.map Http.jsonBody (Just (Api.Data.encodeUpdateSyncDirectionRequest updateSyncDirectionRequest_body)))
        (Json.Decode.succeed ())
        |> Api.withBearerToken auth_token

{-| Webhook receiver
-}
webhookReceiverApi : String -> String -> String -> Api.Request ()
webhookReceiverApi platform_path connectionId_path auth_token =
    Api.request
        "POST"
        "/api/v1/marketplace/webhook/{platform}/{connection_id}"
        [ ( "platform", identity platform_path ), ( "connection_id", identity connectionId_path ) ]
        []
        []
        Nothing
        (Json.Decode.succeed ())
        |> Api.withBearerToken auth_token
