{-
   SimpleBilly API
   Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

   The version of the OpenAPI document: 0.1.0
   Contact: support@simplebilly.com

   NOTE: This file is auto generated by the openapi-generator.
   https://github.com/openapitools/openapi-generator.git

   DO NOT EDIT THIS FILE MANUALLY.

   For more info on generating Elm code, see https://eriktim.github.io/openapi-elm/
-}


module Api.Request.Notifications exposing
    ( deleteNotification
    , listNotifications
    , markAllRead
    , markAsRead
    , unreadCount
    )

import Api
import Api.Data exposing (..)
import Dict
import Http
import Json.Decode
import Json.Encode
import Uuid exposing (Uuid)


deleteNotification : Uuid -> String -> Api.Request ()
deleteNotification id_path auth_token =
    Api.request
        "DELETE"
        "/api/v1/notifications/{id}"
        [ ( "id", Uuid.toString id_path ) ]
        []
        []
        Nothing
        (Json.Decode.succeed ())
        |> Api.withBearerToken auth_token

listNotifications : String -> Api.Request (List Api.Data.NotificationDto)
listNotifications auth_token =
    Api.request
        "GET"
        "/api/v1/notifications"
        []
        []
        []
        Nothing
        (Json.Decode.list Api.Data.notificationDtoDecoder)
        |> Api.withBearerToken auth_token

markAllRead : String -> Api.Request Int
markAllRead auth_token =
    Api.request
        "PUT"
        "/api/v1/notifications/read-all"
        []
        []
        []
        Nothing
        Json.Decode.int
        |> Api.withBearerToken auth_token

markAsRead : Uuid -> String -> Api.Request ()
markAsRead id_path auth_token =
    Api.request
        "PUT"
        "/api/v1/notifications/{id}/read"
        [ ( "id", Uuid.toString id_path ) ]
        []
        []
        Nothing
        (Json.Decode.succeed ())
        |> Api.withBearerToken auth_token

unreadCount : String -> Api.Request Int
unreadCount auth_token =
    Api.request
        "GET"
        "/api/v1/notifications/unread-count"
        []
        []
        []
        Nothing
        Json.Decode.int
        |> Api.withBearerToken auth_token
