{-
   SimpleBilly API
   Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

   The version of the OpenAPI document: 0.1.0
   Contact: support@simplebilly.com

   NOTE: This file is auto generated by the openapi-generator.
   https://github.com/openapitools/openapi-generator.git

   DO NOT EDIT THIS FILE MANUALLY.

   For more info on generating Elm code, see https://eriktim.github.io/openapi-elm/
-}


module Api.Request.OrderConfirmation exposing
    ( createConfirmation
    , deleteConfirmation
    , downloadConfirmationPdf
    , getConfirmation
    , listConfirmations
    , orderconfirmationRestore
    , pursueConfirmation
    )

import Api
import Api.Data exposing (..)
import Dict
import Http
import Json.Decode
import Json.Encode


createConfirmation : Api.Data.OrderConfirmationCreate -> String -> Api.Request Api.Data.OrderConfirmation
createConfirmation orderConfirmationCreate_body auth_token =
    Api.request
        "POST"
        "/api/v1/order-confirmations"
        []
        []
        []
        (Maybe.map Http.jsonBody (Just (Api.Data.encodeOrderConfirmationCreate orderConfirmationCreate_body)))
        Api.Data.orderConfirmationDecoder
        |> Api.withBearerToken auth_token

deleteConfirmation : String -> String -> Api.Request ()
deleteConfirmation confirmationId_path auth_token =
    Api.request
        "DELETE"
        "/api/v1/order-confirmations/{confirmation_id}"
        [ ( "confirmation_id", identity confirmationId_path ) ]
        []
        []
        Nothing
        (Json.Decode.succeed ())
        |> Api.withBearerToken auth_token

downloadConfirmationPdf : String -> String -> Api.Request ()
downloadConfirmationPdf confirmationId_path auth_token =
    Api.request
        "GET"
        "/api/v1/order-confirmations/{confirmation_id}/pdf"
        [ ( "confirmation_id", identity confirmationId_path ) ]
        []
        []
        Nothing
        (Json.Decode.succeed ())
        |> Api.withBearerToken auth_token

getConfirmation : String -> String -> Api.Request Api.Data.OrderConfirmation
getConfirmation confirmationId_path auth_token =
    Api.request
        "GET"
        "/api/v1/order-confirmations/{confirmation_id}"
        [ ( "confirmation_id", identity confirmationId_path ) ]
        []
        []
        Nothing
        Api.Data.orderConfirmationDecoder
        |> Api.withBearerToken auth_token

listConfirmations : Maybe Int -> Maybe Int -> Maybe String -> Maybe Bool -> String -> Api.Request (List Api.Data.OrderConfirmation)
listConfirmations page_query pageSize_query search_query includeDeleted_query auth_token =
    Api.request
        "GET"
        "/api/v1/order-confirmations/"
        []
        [ ( "page", Maybe.map String.fromInt page_query ), ( "page_size", Maybe.map String.fromInt pageSize_query ), ( "search", Maybe.map identity search_query ), ( "include_deleted", Maybe.map (\val -> if val then "true" else "false") includeDeleted_query ) ]
        []
        Nothing
        (Json.Decode.list Api.Data.orderConfirmationDecoder)
        |> Api.withBearerToken auth_token

orderconfirmationRestore : String -> String -> Api.Request Api.Data.OrderConfirmation
orderconfirmationRestore confirmationId_path auth_token =
    Api.request
        "POST"
        "/api/v1/order-confirmations/{confirmation_id}/restore"
        [ ( "confirmation_id", identity confirmationId_path ) ]
        []
        []
        Nothing
        Api.Data.orderConfirmationDecoder
        |> Api.withBearerToken auth_token

pursueConfirmation : String -> String -> Api.Request Api.Data.DeliveryNote
pursueConfirmation confirmationId_path auth_token =
    Api.request
        "POST"
        "/api/v1/order-confirmations/{confirmation_id}/pursue"
        [ ( "confirmation_id", identity confirmationId_path ) ]
        []
        []
        Nothing
        Api.Data.deliveryNoteDecoder
        |> Api.withBearerToken auth_token
