{-
   SimpleBilly API
   Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

   The version of the OpenAPI document: 0.1.0
   Contact: support@simplebilly.com

   NOTE: This file is auto generated by the openapi-generator.
   https://github.com/openapitools/openapi-generator.git

   DO NOT EDIT THIS FILE MANUALLY.

   For more info on generating Elm code, see https://eriktim.github.io/openapi-elm/
-}


module Api.Request.Order exposing
    ( addOrderTags
    , findOrderByExternalRef
    , getOrder
    , getOrders
    , patchOrder
    , replaceOrderTags
    , updateOrderState
    )

import Api
import Api.Data exposing (..)
import Dict
import Http
import Json.Decode
import Json.Encode


addOrderTags : String -> Api.Data.OrderTagsRequest -> String -> Api.Request Api.Data.Order_
addOrderTags orderId_path orderTagsRequest_body auth_token =
    Api.request
        "POST"
        "/api/v1/orders/{order_id}/tags"
        [ ( "order_id", identity orderId_path ) ]
        []
        []
        (Maybe.map Http.jsonBody (Just (Api.Data.encodeOrderTagsRequest orderTagsRequest_body)))
        Api.Data.orderDecoder
        |> Api.withBearerToken auth_token

findOrderByExternalRef : String -> String -> Api.Request Api.Data.Order_
findOrderByExternalRef extRef_path auth_token =
    Api.request
        "GET"
        "/api/v1/orders/by-ext-ref/{ext_ref}"
        [ ( "ext_ref", identity extRef_path ) ]
        []
        []
        Nothing
        Api.Data.orderDecoder
        |> Api.withBearerToken auth_token

getOrder : String -> String -> Api.Request Api.Data.Order_
getOrder orderNumber_path auth_token =
    Api.request
        "GET"
        "/api/v1/order/{order_number}"
        [ ( "order_number", identity orderNumber_path ) ]
        []
        []
        Nothing
        Api.Data.orderDecoder
        |> Api.withBearerToken auth_token

getOrders : Maybe Int -> Maybe Int -> Maybe String -> Maybe Bool -> String -> Api.Request (List Api.Data.Order_)
getOrders page_query pageSize_query search_query includeDeleted_query auth_token =
    Api.request
        "GET"
        "/api/v1/orders"
        []
        [ ( "page", Maybe.map String.fromInt page_query ), ( "page_size", Maybe.map String.fromInt pageSize_query ), ( "search", Maybe.map identity search_query ), ( "include_deleted", Maybe.map (\val -> if val then "true" else "false") includeDeleted_query ) ]
        []
        Nothing
        (Json.Decode.list Api.Data.orderDecoder)
        |> Api.withBearerToken auth_token

patchOrder : String -> Api.Data.AnyType -> String -> Api.Request Api.Data.Order_
patchOrder orderId_path body_body auth_token =
    Api.request
        "PATCH"
        "/api/v1/orders/{order_id}"
        [ ( "order_id", identity orderId_path ) ]
        []
        []
        (Maybe.map Http.jsonBody (Just (encodeAnyType body_body)))
        Api.Data.orderDecoder
        |> Api.withBearerToken auth_token

replaceOrderTags : String -> Api.Data.OrderTagsRequest -> String -> Api.Request Api.Data.Order_
replaceOrderTags orderId_path orderTagsRequest_body auth_token =
    Api.request
        "PUT"
        "/api/v1/orders/{order_id}/tags"
        [ ( "order_id", identity orderId_path ) ]
        []
        []
        (Maybe.map Http.jsonBody (Just (Api.Data.encodeOrderTagsRequest orderTagsRequest_body)))
        Api.Data.orderDecoder
        |> Api.withBearerToken auth_token

updateOrderState : String -> Api.Data.OrderStateUpdate -> String -> Api.Request Api.Data.Order_
updateOrderState orderId_path orderStateUpdate_body auth_token =
    Api.request
        "PUT"
        "/api/v1/orders/{order_id}/state"
        [ ( "order_id", identity orderId_path ) ]
        []
        []
        (Maybe.map Http.jsonBody (Just (Api.Data.encodeOrderStateUpdate orderStateUpdate_body)))
        Api.Data.orderDecoder
        |> Api.withBearerToken auth_token
