{-
   SimpleBilly API
   Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

   The version of the OpenAPI document: 0.1.0
   Contact: support@simplebilly.com

   NOTE: This file is auto generated by the openapi-generator.
   https://github.com/openapitools/openapi-generator.git

   DO NOT EDIT THIS FILE MANUALLY.

   For more info on generating Elm code, see https://eriktim.github.io/openapi-elm/
-}


module Api.Request.Packing exposing
    ( completePacking
    , getPackingQueue
    , printDeliveryNote
    , printLabel
    , recordPackingVideo
    )

import Api
import Api.Data exposing (..)
import Dict
import Http
import Json.Decode
import Json.Encode


{-| Mark packing as complete and transition order to shipped
-}
completePacking : String -> Api.Data.PackingCompleteRequest -> String -> Api.Request Api.Data.PackingCompleteResponse
completePacking orderNumber_path packingCompleteRequest_body auth_token =
    Api.request
        "POST"
        "/api/v1/packing/{order_number}/complete"
        [ ( "order_number", identity orderNumber_path ) ]
        []
        []
        (Maybe.map Http.jsonBody (Just (Api.Data.encodePackingCompleteRequest packingCompleteRequest_body)))
        Api.Data.packingCompleteResponseDecoder
        |> Api.withBearerToken auth_token

{-| Get the packing queue - orders ready for packing
-}
getPackingQueue : Maybe Int -> Maybe Int -> Maybe String -> String -> Api.Request Api.Data.PackingQueue
getPackingQueue page_query pageSize_query search_query auth_token =
    Api.request
        "GET"
        "/api/v1/packing/queue"
        []
        [ ( "page", Maybe.map String.fromInt page_query ), ( "page_size", Maybe.map String.fromInt pageSize_query ), ( "search", Maybe.map identity search_query ) ]
        []
        Nothing
        Api.Data.packingQueueDecoder
        |> Api.withBearerToken auth_token

{-| Print delivery note (Lieferschein) for an order
-}
printDeliveryNote : String -> String -> Api.Request Api.Data.PrintDeliveryNoteResponse
printDeliveryNote orderNumber_path auth_token =
    Api.request
        "POST"
        "/api/v1/packing/{order_number}/print-delivery-note"
        [ ( "order_number", identity orderNumber_path ) ]
        []
        []
        Nothing
        Api.Data.printDeliveryNoteResponseDecoder
        |> Api.withBearerToken auth_token

{-| Print shipping label for an order
-}
printLabel : String -> String -> Api.Request Api.Data.PrintLabelResponse
printLabel orderNumber_path auth_token =
    Api.request
        "POST"
        "/api/v1/packing/{order_number}/print-label"
        [ ( "order_number", identity orderNumber_path ) ]
        []
        []
        Nothing
        Api.Data.printLabelResponseDecoder
        |> Api.withBearerToken auth_token

{-| Record video of packing process
-}
recordPackingVideo : String -> Api.Data.AnyType -> String -> Api.Request Api.Data.PackingVideoResponse
recordPackingVideo orderNumber_path body_body auth_token =
    Api.request
        "POST"
        "/api/v1/packing/{order_number}/record-video"
        [ ( "order_number", identity orderNumber_path ) ]
        []
        []
        (Maybe.map Http.jsonBody (Just (encodeAnyType body_body)))
        Api.Data.packingVideoResponseDecoder
        |> Api.withBearerToken auth_token
