{-
   SimpleBilly API
   Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

   The version of the OpenAPI document: 0.1.0
   Contact: support@simplebilly.com

   NOTE: This file is auto generated by the openapi-generator.
   https://github.com/openapitools/openapi-generator.git

   DO NOT EDIT THIS FILE MANUALLY.

   For more info on generating Elm code, see https://eriktim.github.io/openapi-elm/
-}


module Api.Request.PaymentGateway exposing
    ( createPaymentGatewayApi
    , deletePaymentGatewayApi
    , listPaymentGatewaysApi
    , oauthAuthorizeApi
    , oauthCallbackApi
    , updatePaymentGatewayApi
    )

import Api
import Api.Data exposing (..)
import Dict
import Http
import Json.Decode
import Json.Encode


createPaymentGatewayApi : Api.Data.AnyType -> String -> Api.Request Api.Data.PaymentGateway
createPaymentGatewayApi body_body auth_token =
    Api.request
        "POST"
        "/api/v1/payment-gateways"
        []
        []
        []
        (Maybe.map Http.jsonBody (Just (encodeAnyType body_body)))
        Api.Data.paymentGatewayDecoder
        |> Api.withBearerToken auth_token

deletePaymentGatewayApi : String -> String -> Api.Request ()
deletePaymentGatewayApi gatewayId_path auth_token =
    Api.request
        "DELETE"
        "/api/v1/payment-gateways/{gateway_id}"
        [ ( "gateway_id", identity gatewayId_path ) ]
        []
        []
        Nothing
        (Json.Decode.succeed ())
        |> Api.withBearerToken auth_token

listPaymentGatewaysApi : String -> Api.Request (List Api.Data.PaymentGateway)
listPaymentGatewaysApi auth_token =
    Api.request
        "GET"
        "/api/v1/payment-gateways/"
        []
        []
        []
        Nothing
        (Json.Decode.list Api.Data.paymentGatewayDecoder)
        |> Api.withBearerToken auth_token

oauthAuthorizeApi : Api.Data.GatewayOAuthAuthorizeRequest -> String -> Api.Request Api.Data.GatewayOAuthAuthorizeResponse
oauthAuthorizeApi gatewayOAuthAuthorizeRequest_body auth_token =
    Api.request
        "POST"
        "/api/v1/payment-gateways/oauth/authorize"
        []
        []
        []
        (Maybe.map Http.jsonBody (Just (Api.Data.encodeGatewayOAuthAuthorizeRequest gatewayOAuthAuthorizeRequest_body)))
        Api.Data.gatewayOAuthAuthorizeResponseDecoder
        |> Api.withBearerToken auth_token

oauthCallbackApi : Api.Data.GatewayOAuthCallbackRequest -> String -> Api.Request Api.Data.PaymentGateway
oauthCallbackApi gatewayOAuthCallbackRequest_body auth_token =
    Api.request
        "POST"
        "/api/v1/payment-gateways/oauth/callback"
        []
        []
        []
        (Maybe.map Http.jsonBody (Just (Api.Data.encodeGatewayOAuthCallbackRequest gatewayOAuthCallbackRequest_body)))
        Api.Data.paymentGatewayDecoder
        |> Api.withBearerToken auth_token

updatePaymentGatewayApi : String -> Api.Data.AnyType -> String -> Api.Request Api.Data.PaymentGateway
updatePaymentGatewayApi gatewayId_path body_body auth_token =
    Api.request
        "PUT"
        "/api/v1/payment-gateways/{gateway_id}"
        [ ( "gateway_id", identity gatewayId_path ) ]
        []
        []
        (Maybe.map Http.jsonBody (Just (encodeAnyType body_body)))
        Api.Data.paymentGatewayDecoder
        |> Api.withBearerToken auth_token
