{-
   SimpleBilly API
   Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

   The version of the OpenAPI document: 0.1.0
   Contact: support@simplebilly.com

   NOTE: This file is auto generated by the openapi-generator.
   https://github.com/openapitools/openapi-generator.git

   DO NOT EDIT THIS FILE MANUALLY.

   For more info on generating Elm code, see https://eriktim.github.io/openapi-elm/
-}


module Api.Request.Payment exposing
    ( createPayment
    , deletePayment
    , getPayment
    , getPayments
    , paymentRestore
    , updatePayment
    )

import Api
import Api.Data exposing (..)
import Dict
import Http
import Json.Decode
import Json.Encode
import Uuid exposing (Uuid)


createPayment : Api.Data.PaymentCreate -> String -> Api.Request Api.Data.Payment
createPayment paymentCreate_body auth_token =
    Api.request
        "POST"
        "/api/v1/payments"
        []
        []
        []
        (Maybe.map Http.jsonBody (Just (Api.Data.encodePaymentCreate paymentCreate_body)))
        Api.Data.paymentDecoder
        |> Api.withBearerToken auth_token

deletePayment : Uuid -> String -> Api.Request ()
deletePayment id_path auth_token =
    Api.request
        "DELETE"
        "/api/v1/payments/{id}"
        [ ( "id", Uuid.toString id_path ) ]
        []
        []
        Nothing
        (Json.Decode.succeed ())
        |> Api.withBearerToken auth_token

getPayment : Uuid -> String -> Api.Request Api.Data.Payment
getPayment id_path auth_token =
    Api.request
        "GET"
        "/api/v1/payments/{id}"
        [ ( "id", Uuid.toString id_path ) ]
        []
        []
        Nothing
        Api.Data.paymentDecoder
        |> Api.withBearerToken auth_token

getPayments : Maybe Int -> Maybe Int -> Maybe String -> Maybe Bool -> String -> Api.Request (List Api.Data.Payment)
getPayments page_query pageSize_query search_query includeDeleted_query auth_token =
    Api.request
        "GET"
        "/api/v1/payments/"
        []
        [ ( "page", Maybe.map String.fromInt page_query ), ( "page_size", Maybe.map String.fromInt pageSize_query ), ( "search", Maybe.map identity search_query ), ( "include_deleted", Maybe.map (\val -> if val then "true" else "false") includeDeleted_query ) ]
        []
        Nothing
        (Json.Decode.list Api.Data.paymentDecoder)
        |> Api.withBearerToken auth_token

paymentRestore : Uuid -> String -> Api.Request Api.Data.Payment
paymentRestore id_path auth_token =
    Api.request
        "POST"
        "/api/v1/payments/{id}/restore"
        [ ( "id", Uuid.toString id_path ) ]
        []
        []
        Nothing
        Api.Data.paymentDecoder
        |> Api.withBearerToken auth_token

updatePayment : Uuid -> Api.Data.AnyType -> String -> Api.Request Api.Data.Payment
updatePayment id_path body_body auth_token =
    Api.request
        "PUT"
        "/api/v1/payments/{id}"
        [ ( "id", Uuid.toString id_path ) ]
        []
        []
        (Maybe.map Http.jsonBody (Just (encodeAnyType body_body)))
        Api.Data.paymentDecoder
        |> Api.withBearerToken auth_token
