{-
   SimpleBilly API
   Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

   The version of the OpenAPI document: 0.1.0
   Contact: support@simplebilly.com

   NOTE: This file is auto generated by the openapi-generator.
   https://github.com/openapitools/openapi-generator.git

   DO NOT EDIT THIS FILE MANUALLY.

   For more info on generating Elm code, see https://eriktim.github.io/openapi-elm/
-}


module Api.Request.Payroll exposing
    ( payrollApprove
    , payrollAutopay
    , payrollCalculate
    , payrollCreate
    , payrollDelete
    , payrollElsterExport
    , payrollEmail
    , payrollEntryPdf
    , payrollGet
    , payrollList
    , payrollPay
    , payrollPdf
    , payrollSummary
    , payrollSvMeldungen
    )

import Api
import Api.Data exposing (..)
import Dict
import Http
import Json.Decode
import Json.Encode
import Uuid exposing (Uuid)


payrollApprove : Uuid -> String -> Api.Request Api.Data.PayrollRunApi
payrollApprove id_path auth_token =
    Api.request
        "POST"
        "/api/v1/payroll/{id}/approve"
        [ ( "id", Uuid.toString id_path ) ]
        []
        []
        Nothing
        Api.Data.payrollRunApiDecoder
        |> Api.withBearerToken auth_token

payrollAutopay : String -> Maybe Api.Data.AnyType -> String -> Api.Request Api.Data.AnyType
payrollAutopay id_path body_body auth_token =
    Api.request
        "POST"
        "/api/v1/payroll/{id}/autopay"
        [ ( "id", identity id_path ) ]
        []
        []
        (Maybe.map Http.jsonBody (Maybe.map encodeAnyType body_body))
        Api.Data.anyTypeDecoder
        |> Api.withBearerToken auth_token

payrollCalculate : Uuid -> String -> Api.Request Api.Data.PayrollRunApi
payrollCalculate id_path auth_token =
    Api.request
        "POST"
        "/api/v1/payroll/{id}/calculate"
        [ ( "id", Uuid.toString id_path ) ]
        []
        []
        Nothing
        Api.Data.payrollRunApiDecoder
        |> Api.withBearerToken auth_token

payrollCreate : Api.Data.PayrollCreatePayload -> String -> Api.Request Api.Data.PayrollRunApi
payrollCreate payrollCreatePayload_body auth_token =
    Api.request
        "POST"
        "/api/v1/payroll"
        []
        []
        []
        (Maybe.map Http.jsonBody (Just (Api.Data.encodePayrollCreatePayload payrollCreatePayload_body)))
        Api.Data.payrollRunApiDecoder
        |> Api.withBearerToken auth_token

payrollDelete : Uuid -> String -> Api.Request ()
payrollDelete id_path auth_token =
    Api.request
        "DELETE"
        "/api/v1/payroll/{id}"
        [ ( "id", Uuid.toString id_path ) ]
        []
        []
        Nothing
        (Json.Decode.succeed ())
        |> Api.withBearerToken auth_token

payrollElsterExport : Uuid -> String -> Api.Request ()
payrollElsterExport id_path auth_token =
    Api.request
        "POST"
        "/api/v1/payroll/{id}/elster-export"
        [ ( "id", Uuid.toString id_path ) ]
        []
        []
        Nothing
        (Json.Decode.succeed ())
        |> Api.withBearerToken auth_token

payrollEmail : String -> String -> Api.Request Api.Data.AnyType
payrollEmail id_path auth_token =
    Api.request
        "POST"
        "/api/v1/payroll/{id}/email"
        [ ( "id", identity id_path ) ]
        []
        []
        Nothing
        Api.Data.anyTypeDecoder
        |> Api.withBearerToken auth_token

payrollEntryPdf : String -> String -> String -> Api.Request ()
payrollEntryPdf id_path entryId_path auth_token =
    Api.request
        "GET"
        "/api/v1/payroll/{id}/entries/{entry_id}/pdf"
        [ ( "id", identity id_path ), ( "entry_id", identity entryId_path ) ]
        []
        []
        Nothing
        (Json.Decode.succeed ())
        |> Api.withBearerToken auth_token

payrollGet : Uuid -> String -> Api.Request Api.Data.PayrollRunApi
payrollGet id_path auth_token =
    Api.request
        "GET"
        "/api/v1/payroll/{id}"
        [ ( "id", Uuid.toString id_path ) ]
        []
        []
        Nothing
        Api.Data.payrollRunApiDecoder
        |> Api.withBearerToken auth_token

payrollList : Maybe Int -> Maybe String -> String -> Api.Request (List Api.Data.PayrollRunApi)
payrollList year_query status_query auth_token =
    Api.request
        "GET"
        "/api/v1/payroll"
        []
        [ ( "year", Maybe.map String.fromInt year_query ), ( "status", Maybe.map identity status_query ) ]
        []
        Nothing
        (Json.Decode.list Api.Data.payrollRunApiDecoder)
        |> Api.withBearerToken auth_token

payrollPay : Uuid -> Api.Data.PayrollPayPayload -> String -> Api.Request Api.Data.PayrollRunApi
payrollPay id_path payrollPayPayload_body auth_token =
    Api.request
        "POST"
        "/api/v1/payroll/{id}/pay"
        [ ( "id", Uuid.toString id_path ) ]
        []
        []
        (Maybe.map Http.jsonBody (Just (Api.Data.encodePayrollPayPayload payrollPayPayload_body)))
        Api.Data.payrollRunApiDecoder
        |> Api.withBearerToken auth_token

payrollPdf : String -> String -> Api.Request ()
payrollPdf id_path auth_token =
    Api.request
        "GET"
        "/api/v1/payroll/{id}/pdf"
        [ ( "id", identity id_path ) ]
        []
        []
        Nothing
        (Json.Decode.succeed ())
        |> Api.withBearerToken auth_token

payrollSummary : Int -> String -> Api.Request Api.Data.YearlyPayrollSummary
payrollSummary year_path auth_token =
    Api.request
        "GET"
        "/api/v1/payroll/summary/{year}"
        [ ( "year", String.fromInt year_path ) ]
        []
        []
        Nothing
        Api.Data.yearlyPayrollSummaryDecoder
        |> Api.withBearerToken auth_token

payrollSvMeldungen : Uuid -> String -> Api.Request Api.Data.AnyType
payrollSvMeldungen id_path auth_token =
    Api.request
        "POST"
        "/api/v1/payroll/{id}/sv-meldungen"
        [ ( "id", Uuid.toString id_path ) ]
        []
        []
        Nothing
        Api.Data.anyTypeDecoder
        |> Api.withBearerToken auth_token
