{-
   SimpleBilly API
   Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

   The version of the OpenAPI document: 0.1.0
   Contact: support@simplebilly.com

   NOTE: This file is auto generated by the openapi-generator.
   https://github.com/openapitools/openapi-generator.git

   DO NOT EDIT THIS FILE MANUALLY.

   For more info on generating Elm code, see https://eriktim.github.io/openapi-elm/
-}


module Api.Request.Pos exposing
    ( posBilling
    , posCreateOrder
    , posCreateRegister
    , posCreateTable
    , posDisableRegister
    , posFreeTable
    , posKasseClosing
    , posKasseEntries
    , posKasseExport
    , posKassePayInOut
    , posListOrders
    , posListProducts
    , posListRegisters
    , posListTables
    , posOrderPrint
    , posOrderReceipt
    , posPayOrder
    , posSumupCheckout
    )

import Api
import Api.Data exposing (..)
import Dict
import Http
import Json.Decode
import Json.Encode
import Uuid exposing (Uuid)


posBilling : String -> Api.Request Api.Data.AnyType
posBilling auth_token =
    Api.request
        "GET"
        "/api/pos/billing"
        []
        []
        []
        Nothing
        Api.Data.anyTypeDecoder
        |> Api.withBearerToken auth_token

posCreateOrder : Api.Data.AnyType -> String -> Api.Request Api.Data.AnyType
posCreateOrder body_body auth_token =
    Api.request
        "POST"
        "/api/pos/orders"
        []
        []
        []
        (Maybe.map Http.jsonBody (Just (encodeAnyType body_body)))
        Api.Data.anyTypeDecoder
        |> Api.withBearerToken auth_token

posCreateRegister : Api.Data.PosRegisterCreate -> String -> Api.Request Api.Data.PosRegister
posCreateRegister posRegisterCreate_body auth_token =
    Api.request
        "POST"
        "/api/pos/registers"
        []
        []
        []
        (Maybe.map Http.jsonBody (Just (Api.Data.encodePosRegisterCreate posRegisterCreate_body)))
        Api.Data.posRegisterDecoder
        |> Api.withBearerToken auth_token

posCreateTable : Api.Data.PosTableCreate -> String -> Api.Request Api.Data.PosTable
posCreateTable posTableCreate_body auth_token =
    Api.request
        "POST"
        "/api/pos/tables"
        []
        []
        []
        (Maybe.map Http.jsonBody (Just (Api.Data.encodePosTableCreate posTableCreate_body)))
        Api.Data.posTableDecoder
        |> Api.withBearerToken auth_token

posDisableRegister : Uuid -> String -> Api.Request Api.Data.PosRegister
posDisableRegister id_path auth_token =
    Api.request
        "POST"
        "/api/pos/registers/{id}/disable"
        [ ( "id", Uuid.toString id_path ) ]
        []
        []
        Nothing
        Api.Data.posRegisterDecoder
        |> Api.withBearerToken auth_token

posFreeTable : Uuid -> String -> Api.Request Api.Data.PosTable
posFreeTable id_path auth_token =
    Api.request
        "POST"
        "/api/pos/tables/{id}/free"
        [ ( "id", Uuid.toString id_path ) ]
        []
        []
        Nothing
        Api.Data.posTableDecoder
        |> Api.withBearerToken auth_token

posKasseClosing : Api.Data.AnyType -> String -> Api.Request Api.Data.AnyType
posKasseClosing body_body auth_token =
    Api.request
        "POST"
        "/api/pos/kasse/closing"
        []
        []
        []
        (Maybe.map Http.jsonBody (Just (encodeAnyType body_body)))
        Api.Data.anyTypeDecoder
        |> Api.withBearerToken auth_token

posKasseEntries : String -> Api.Request Api.Data.AnyType
posKasseEntries auth_token =
    Api.request
        "GET"
        "/api/pos/kasse/entries"
        []
        []
        []
        Nothing
        Api.Data.anyTypeDecoder
        |> Api.withBearerToken auth_token

posKasseExport : String -> Api.Request Api.Data.AnyType
posKasseExport auth_token =
    Api.request
        "GET"
        "/api/pos/kasse/export"
        []
        []
        []
        Nothing
        Api.Data.anyTypeDecoder
        |> Api.withBearerToken auth_token

posKassePayInOut : Api.Data.AnyType -> String -> Api.Request Api.Data.AnyType
posKassePayInOut body_body auth_token =
    Api.request
        "POST"
        "/api/pos/kasse/pay-in-out"
        []
        []
        []
        (Maybe.map Http.jsonBody (Just (encodeAnyType body_body)))
        Api.Data.anyTypeDecoder
        |> Api.withBearerToken auth_token

posListOrders : Maybe String -> String -> Api.Request Api.Data.AnyType
posListOrders status_query auth_token =
    Api.request
        "GET"
        "/api/pos/orders"
        []
        [ ( "status", Maybe.map identity status_query ) ]
        []
        Nothing
        Api.Data.anyTypeDecoder
        |> Api.withBearerToken auth_token

posListProducts : Maybe String -> String -> Api.Request Api.Data.AnyType
posListProducts q_query auth_token =
    Api.request
        "GET"
        "/api/pos/products"
        []
        [ ( "q", Maybe.map identity q_query ) ]
        []
        Nothing
        Api.Data.anyTypeDecoder
        |> Api.withBearerToken auth_token

posListRegisters : String -> Api.Request (List Api.Data.PosRegister)
posListRegisters auth_token =
    Api.request
        "GET"
        "/api/pos/registers"
        []
        []
        []
        Nothing
        (Json.Decode.list Api.Data.posRegisterDecoder)
        |> Api.withBearerToken auth_token

posListTables : String -> Api.Request (List Api.Data.PosTable)
posListTables auth_token =
    Api.request
        "GET"
        "/api/pos/tables"
        []
        []
        []
        Nothing
        (Json.Decode.list Api.Data.posTableDecoder)
        |> Api.withBearerToken auth_token

posOrderPrint : String -> String -> Api.Request Api.Data.AnyType
posOrderPrint orderNumber_path auth_token =
    Api.request
        "GET"
        "/api/pos/orders/{order_number}/print"
        [ ( "order_number", identity orderNumber_path ) ]
        []
        []
        Nothing
        Api.Data.anyTypeDecoder
        |> Api.withBearerToken auth_token

posOrderReceipt : String -> String -> Api.Request Api.Data.AnyType
posOrderReceipt orderNumber_path auth_token =
    Api.request
        "GET"
        "/api/pos/orders/{order_number}/receipt"
        [ ( "order_number", identity orderNumber_path ) ]
        []
        []
        Nothing
        Api.Data.anyTypeDecoder
        |> Api.withBearerToken auth_token

posPayOrder : String -> Api.Data.AnyType -> String -> Api.Request Api.Data.AnyType
posPayOrder orderNumber_path body_body auth_token =
    Api.request
        "POST"
        "/api/pos/orders/{order_number}/pay"
        [ ( "order_number", identity orderNumber_path ) ]
        []
        []
        (Maybe.map Http.jsonBody (Just (encodeAnyType body_body)))
        Api.Data.anyTypeDecoder
        |> Api.withBearerToken auth_token

posSumupCheckout : Api.Data.AnyType -> String -> Api.Request Api.Data.AnyType
posSumupCheckout body_body auth_token =
    Api.request
        "POST"
        "/api/pos/sumup/checkout"
        []
        []
        []
        (Maybe.map Http.jsonBody (Just (encodeAnyType body_body)))
        Api.Data.anyTypeDecoder
        |> Api.withBearerToken auth_token
