{-
   SimpleBilly API
   Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

   The version of the OpenAPI document: 0.1.0
   Contact: support@simplebilly.com

   NOTE: This file is auto generated by the openapi-generator.
   https://github.com/openapitools/openapi-generator.git

   DO NOT EDIT THIS FILE MANUALLY.

   For more info on generating Elm code, see https://eriktim.github.io/openapi-elm/
-}


module Api.Request.PostingCategory exposing
    ( createPostingCategory
    , deletePostingCategory
    , listPostingCategories
    , seedPostingCategories
    , updatePostingCategory
    )

import Api
import Api.Data exposing (..)
import Dict
import Http
import Json.Decode
import Json.Encode


createPostingCategory : Api.Data.AnyType -> String -> Api.Request Api.Data.PostingCategory
createPostingCategory body_body auth_token =
    Api.request
        "POST"
        "/api/v1/posting-categories"
        []
        []
        []
        (Maybe.map Http.jsonBody (Just (encodeAnyType body_body)))
        Api.Data.postingCategoryDecoder
        |> Api.withBearerToken auth_token

deletePostingCategory : String -> String -> Api.Request ()
deletePostingCategory categoryId_path auth_token =
    Api.request
        "DELETE"
        "/api/v1/posting-categories/{category_id}"
        [ ( "category_id", identity categoryId_path ) ]
        []
        []
        Nothing
        (Json.Decode.succeed ())
        |> Api.withBearerToken auth_token

listPostingCategories : String -> Api.Request (List Api.Data.PostingCategory)
listPostingCategories auth_token =
    Api.request
        "GET"
        "/api/v1/posting-categories"
        []
        []
        []
        Nothing
        (Json.Decode.list Api.Data.postingCategoryDecoder)
        |> Api.withBearerToken auth_token

seedPostingCategories : String -> String -> Api.Request ()
seedPostingCategories skrVersion_path auth_token =
    Api.request
        "POST"
        "/api/v1/posting-categories/seed/{skr_version}"
        [ ( "skr_version", identity skrVersion_path ) ]
        []
        []
        Nothing
        (Json.Decode.succeed ())
        |> Api.withBearerToken auth_token

updatePostingCategory : String -> Api.Data.AnyType -> String -> Api.Request Api.Data.PostingCategory
updatePostingCategory categoryId_path body_body auth_token =
    Api.request
        "PUT"
        "/api/v1/posting-categories/{category_id}"
        [ ( "category_id", identity categoryId_path ) ]
        []
        []
        (Maybe.map Http.jsonBody (Just (encodeAnyType body_body)))
        Api.Data.postingCategoryDecoder
        |> Api.withBearerToken auth_token
