{-
   SimpleBilly API
   Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

   The version of the OpenAPI document: 0.1.0
   Contact: support@simplebilly.com

   NOTE: This file is auto generated by the openapi-generator.
   https://github.com/openapitools/openapi-generator.git

   DO NOT EDIT THIS FILE MANUALLY.

   For more info on generating Elm code, see https://eriktim.github.io/openapi-elm/
-}


module Api.Request.PriceTier exposing
    ( createPriceTier
    , deletePriceTier
    , getPriceTier
    , getResolvedPrice
    , listPriceTiers
    , updatePriceTier
    )

import Api
import Api.Data exposing (..)
import Dict
import Http
import Json.Decode
import Json.Encode
import Uuid exposing (Uuid)


createPriceTier : Api.Data.PriceTierCreate -> String -> Api.Request Api.Data.PriceTier
createPriceTier priceTierCreate_body auth_token =
    Api.request
        "POST"
        "/api/v1/price-tiers"
        []
        []
        []
        (Maybe.map Http.jsonBody (Just (Api.Data.encodePriceTierCreate priceTierCreate_body)))
        Api.Data.priceTierDecoder
        |> Api.withBearerToken auth_token

deletePriceTier : String -> String -> Api.Request ()
deletePriceTier priceTierId_path auth_token =
    Api.request
        "DELETE"
        "/api/v1/price-tiers/{price_tier_id}"
        [ ( "price_tier_id", identity priceTierId_path ) ]
        []
        []
        Nothing
        (Json.Decode.succeed ())
        |> Api.withBearerToken auth_token

getPriceTier : String -> String -> Api.Request Api.Data.PriceTier
getPriceTier priceTierId_path auth_token =
    Api.request
        "GET"
        "/api/v1/price-tiers/{price_tier_id}"
        [ ( "price_tier_id", identity priceTierId_path ) ]
        []
        []
        Nothing
        Api.Data.priceTierDecoder
        |> Api.withBearerToken auth_token

getResolvedPrice : Uuid -> Maybe Int -> Maybe String -> String -> Api.Request Api.Data.ResolvedPriceResponse
getResolvedPrice productId_query quantity_query contactId_query auth_token =
    Api.request
        "GET"
        "/api/v1/price-tiers/resolved"
        []
        [ ( "productId", Just <| Uuid.toString productId_query ), ( "quantity", Maybe.map String.fromInt quantity_query ), ( "contactId", Maybe.map identity contactId_query ) ]
        []
        Nothing
        Api.Data.resolvedPriceResponseDecoder
        |> Api.withBearerToken auth_token

listPriceTiers : Maybe Int -> Maybe Int -> Maybe Uuid -> Maybe String -> String -> Api.Request (List Api.Data.PriceTier)
listPriceTiers page_query pageSize_query productId_query customerGroupId_query auth_token =
    Api.request
        "GET"
        "/api/v1/price-tiers/"
        []
        [ ( "page", Maybe.map String.fromInt page_query ), ( "page_size", Maybe.map String.fromInt pageSize_query ), ( "product_id", Maybe.map Uuid.toString productId_query ), ( "customer_group_id", Maybe.map identity customerGroupId_query ) ]
        []
        Nothing
        (Json.Decode.list Api.Data.priceTierDecoder)
        |> Api.withBearerToken auth_token

updatePriceTier : String -> Api.Data.PriceTierUpdate -> String -> Api.Request Api.Data.PriceTier
updatePriceTier priceTierId_path priceTierUpdate_body auth_token =
    Api.request
        "PUT"
        "/api/v1/price-tiers/{price_tier_id}"
        [ ( "price_tier_id", identity priceTierId_path ) ]
        []
        []
        (Maybe.map Http.jsonBody (Just (Api.Data.encodePriceTierUpdate priceTierUpdate_body)))
        Api.Data.priceTierDecoder
        |> Api.withBearerToken auth_token
