{-
   SimpleBilly API
   Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

   The version of the OpenAPI document: 0.1.0
   Contact: support@simplebilly.com

   NOTE: This file is auto generated by the openapi-generator.
   https://github.com/openapitools/openapi-generator.git

   DO NOT EDIT THIS FILE MANUALLY.

   For more info on generating Elm code, see https://eriktim.github.io/openapi-elm/
-}


module Api.Request.ProductionOrder exposing
    ( createProductionOrder
    , deleteProductionOrder
    , getProductionOrder
    , listProductionOrders
    , productionOrderCosting
    , updateProductionOrder
    , updateProductionOrderStatus
    )

import Api
import Api.Data exposing (..)
import Dict
import Http
import Json.Decode
import Json.Encode
import Uuid exposing (Uuid)


createProductionOrder : Api.Data.ProductionOrder -> String -> Api.Request Api.Data.ProductionOrder
createProductionOrder productionOrder_body auth_token =
    Api.request
        "POST"
        "/api/v1/production-orders"
        []
        []
        []
        (Maybe.map Http.jsonBody (Just (Api.Data.encodeProductionOrder productionOrder_body)))
        Api.Data.productionOrderDecoder
        |> Api.withBearerToken auth_token

deleteProductionOrder : Uuid -> String -> Api.Request ()
deleteProductionOrder productionOrderId_path auth_token =
    Api.request
        "DELETE"
        "/api/v1/production-orders/{production_order_id}"
        [ ( "production_order_id", Uuid.toString productionOrderId_path ) ]
        []
        []
        Nothing
        (Json.Decode.succeed ())
        |> Api.withBearerToken auth_token

getProductionOrder : Uuid -> String -> Api.Request Api.Data.ProductionOrder
getProductionOrder productionOrderId_path auth_token =
    Api.request
        "GET"
        "/api/v1/production-orders/{production_order_id}"
        [ ( "production_order_id", Uuid.toString productionOrderId_path ) ]
        []
        []
        Nothing
        Api.Data.productionOrderDecoder
        |> Api.withBearerToken auth_token

listProductionOrders : Maybe Int -> Maybe Int -> Maybe String -> Maybe String -> String -> Api.Request (List Api.Data.ProductionOrder)
listProductionOrders page_query pageSize_query search_query status_query auth_token =
    Api.request
        "GET"
        "/api/v1/production-orders/"
        []
        [ ( "page", Maybe.map String.fromInt page_query ), ( "pageSize", Maybe.map String.fromInt pageSize_query ), ( "search", Maybe.map identity search_query ), ( "status", Maybe.map identity status_query ) ]
        []
        Nothing
        (Json.Decode.list Api.Data.productionOrderDecoder)
        |> Api.withBearerToken auth_token

{-| Actual-costing report (Nachkalkulation) — material costs from BOM components at their purchase price plus the resulting per-unit cost and margin against the finished product's sale price.
-}
productionOrderCosting : Uuid -> String -> Api.Request Api.Data.ProductionOrderCosting
productionOrderCosting productionOrderId_path auth_token =
    Api.request
        "GET"
        "/api/v1/production-orders/{production_order_id}/costing"
        [ ( "production_order_id", Uuid.toString productionOrderId_path ) ]
        []
        []
        Nothing
        Api.Data.productionOrderCostingDecoder
        |> Api.withBearerToken auth_token

updateProductionOrder : Uuid -> Api.Data.ProductionOrder -> String -> Api.Request Api.Data.ProductionOrder
updateProductionOrder productionOrderId_path productionOrder_body auth_token =
    Api.request
        "PUT"
        "/api/v1/production-orders/{production_order_id}"
        [ ( "production_order_id", Uuid.toString productionOrderId_path ) ]
        []
        []
        (Maybe.map Http.jsonBody (Just (Api.Data.encodeProductionOrder productionOrder_body)))
        Api.Data.productionOrderDecoder
        |> Api.withBearerToken auth_token

updateProductionOrderStatus : Uuid -> Api.Data.ProductionOrderStatusUpdate -> String -> Api.Request Api.Data.ProductionOrder
updateProductionOrderStatus productionOrderId_path productionOrderStatusUpdate_body auth_token =
    Api.request
        "PUT"
        "/api/v1/production-orders/{production_order_id}/status"
        [ ( "production_order_id", Uuid.toString productionOrderId_path ) ]
        []
        []
        (Maybe.map Http.jsonBody (Just (Api.Data.encodeProductionOrderStatusUpdate productionOrderStatusUpdate_body)))
        Api.Data.productionOrderDecoder
        |> Api.withBearerToken auth_token
