{-
   SimpleBilly API
   Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

   The version of the OpenAPI document: 0.1.0
   Contact: support@simplebilly.com

   NOTE: This file is auto generated by the openapi-generator.
   https://github.com/openapitools/openapi-generator.git

   DO NOT EDIT THIS FILE MANUALLY.

   For more info on generating Elm code, see https://eriktim.github.io/openapi-elm/
-}


module Api.Request.ProductVariant exposing
    ( createProductVariant
    , deleteProductVariant
    , generateProductVariants
    , getProductVariant
    , listProductVariants
    , updateProductVariant
    )

import Api
import Api.Data exposing (..)
import Dict
import Http
import Json.Decode
import Json.Encode
import Uuid exposing (Uuid)


createProductVariant : Api.Data.ProductVariant -> String -> Api.Request Api.Data.ProductVariant
createProductVariant productVariant_body auth_token =
    Api.request
        "POST"
        "/api/v1/product-variants"
        []
        []
        []
        (Maybe.map Http.jsonBody (Just (Api.Data.encodeProductVariant productVariant_body)))
        Api.Data.productVariantDecoder
        |> Api.withBearerToken auth_token

deleteProductVariant : String -> String -> Api.Request ()
deleteProductVariant variantId_path auth_token =
    Api.request
        "DELETE"
        "/api/v1/product-variants/{variant_id}"
        [ ( "variant_id", identity variantId_path ) ]
        []
        []
        Nothing
        (Json.Decode.succeed ())
        |> Api.withBearerToken auth_token

generateProductVariants : Api.Data.GenerateVariantsRequest -> String -> Api.Request (List Api.Data.ProductVariant)
generateProductVariants generateVariantsRequest_body auth_token =
    Api.request
        "POST"
        "/api/v1/product-variants/generate"
        []
        []
        []
        (Maybe.map Http.jsonBody (Just (Api.Data.encodeGenerateVariantsRequest generateVariantsRequest_body)))
        (Json.Decode.list Api.Data.productVariantDecoder)
        |> Api.withBearerToken auth_token

getProductVariant : String -> String -> Api.Request Api.Data.ProductVariant
getProductVariant variantId_path auth_token =
    Api.request
        "GET"
        "/api/v1/product-variants/{variant_id}"
        [ ( "variant_id", identity variantId_path ) ]
        []
        []
        Nothing
        Api.Data.productVariantDecoder
        |> Api.withBearerToken auth_token

listProductVariants : Maybe Int -> Maybe Int -> Maybe Uuid -> Maybe Bool -> String -> Api.Request (List Api.Data.ProductVariant)
listProductVariants page_query pageSize_query productId_query isActive_query auth_token =
    Api.request
        "GET"
        "/api/v1/product-variants/"
        []
        [ ( "page", Maybe.map String.fromInt page_query ), ( "page_size", Maybe.map String.fromInt pageSize_query ), ( "product_id", Maybe.map Uuid.toString productId_query ), ( "is_active", Maybe.map (\val -> if val then "true" else "false") isActive_query ) ]
        []
        Nothing
        (Json.Decode.list Api.Data.productVariantDecoder)
        |> Api.withBearerToken auth_token

updateProductVariant : String -> Api.Data.AnyType -> String -> Api.Request Api.Data.ProductVariant
updateProductVariant variantId_path body_body auth_token =
    Api.request
        "PUT"
        "/api/v1/product-variants/{variant_id}"
        [ ( "variant_id", identity variantId_path ) ]
        []
        []
        (Maybe.map Http.jsonBody (Just (encodeAnyType body_body)))
        Api.Data.productVariantDecoder
        |> Api.withBearerToken auth_token
