{-
   SimpleBilly API
   Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

   The version of the OpenAPI document: 0.1.0
   Contact: support@simplebilly.com

   NOTE: This file is auto generated by the openapi-generator.
   https://github.com/openapitools/openapi-generator.git

   DO NOT EDIT THIS FILE MANUALLY.

   For more info on generating Elm code, see https://eriktim.github.io/openapi-elm/
-}


module Api.Request.ProductAttribute exposing
    ( createProductAttribute
    , deleteProductAttribute
    , getProductAttribute
    , listProductAttributes
    , updateProductAttribute
    )

import Api
import Api.Data exposing (..)
import Dict
import Http
import Json.Decode
import Json.Encode
import Uuid exposing (Uuid)


createProductAttribute : Api.Data.ProductAttributeCreate -> String -> Api.Request Api.Data.ProductAttribute
createProductAttribute productAttributeCreate_body auth_token =
    Api.request
        "POST"
        "/api/v1/product-attributes"
        []
        []
        []
        (Maybe.map Http.jsonBody (Just (Api.Data.encodeProductAttributeCreate productAttributeCreate_body)))
        Api.Data.productAttributeDecoder
        |> Api.withBearerToken auth_token

deleteProductAttribute : String -> String -> Api.Request ()
deleteProductAttribute attributeId_path auth_token =
    Api.request
        "DELETE"
        "/api/v1/product-attributes/{attribute_id}"
        [ ( "attribute_id", identity attributeId_path ) ]
        []
        []
        Nothing
        (Json.Decode.succeed ())
        |> Api.withBearerToken auth_token

getProductAttribute : String -> String -> Api.Request Api.Data.ProductAttribute
getProductAttribute attributeId_path auth_token =
    Api.request
        "GET"
        "/api/v1/product-attributes/{attribute_id}"
        [ ( "attribute_id", identity attributeId_path ) ]
        []
        []
        Nothing
        Api.Data.productAttributeDecoder
        |> Api.withBearerToken auth_token

listProductAttributes : Maybe Int -> Maybe Int -> Maybe Uuid -> Maybe Bool -> Maybe String -> String -> Api.Request (List Api.Data.ProductAttribute)
listProductAttributes page_query pageSize_query productId_query isFilterable_query search_query auth_token =
    Api.request
        "GET"
        "/api/v1/product-attributes/"
        []
        [ ( "page", Maybe.map String.fromInt page_query ), ( "page_size", Maybe.map String.fromInt pageSize_query ), ( "product_id", Maybe.map Uuid.toString productId_query ), ( "is_filterable", Maybe.map (\val -> if val then "true" else "false") isFilterable_query ), ( "search", Maybe.map identity search_query ) ]
        []
        Nothing
        (Json.Decode.list Api.Data.productAttributeDecoder)
        |> Api.withBearerToken auth_token

updateProductAttribute : String -> Api.Data.ProductAttributeUpdate -> String -> Api.Request Api.Data.ProductAttribute
updateProductAttribute attributeId_path productAttributeUpdate_body auth_token =
    Api.request
        "PUT"
        "/api/v1/product-attributes/{attribute_id}"
        [ ( "attribute_id", identity attributeId_path ) ]
        []
        []
        (Maybe.map Http.jsonBody (Just (Api.Data.encodeProductAttributeUpdate productAttributeUpdate_body)))
        Api.Data.productAttributeDecoder
        |> Api.withBearerToken auth_token
