{-
   SimpleBilly API
   Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

   The version of the OpenAPI document: 0.1.0
   Contact: support@simplebilly.com

   NOTE: This file is auto generated by the openapi-generator.
   https://github.com/openapitools/openapi-generator.git

   DO NOT EDIT THIS FILE MANUALLY.

   For more info on generating Elm code, see https://eriktim.github.io/openapi-elm/
-}


module Api.Request.Product exposing
    ( createProductApi
    , deleteProductApi
    , getProductApi
    , getProductStockApi
    , getProductsApi
    , listLowStockProductsApi
    , productRestore
    , updateProductApi
    , updateProductStockApi
    )

import Api
import Api.Data exposing (..)
import Dict
import Http
import Json.Decode
import Json.Encode
import Uuid exposing (Uuid)


createProductApi : Api.Data.ProductCreate -> String -> Api.Request Api.Data.Product
createProductApi productCreate_body auth_token =
    Api.request
        "POST"
        "/api/v1/products"
        []
        []
        []
        (Maybe.map Http.jsonBody (Just (Api.Data.encodeProductCreate productCreate_body)))
        Api.Data.productDecoder
        |> Api.withBearerToken auth_token

deleteProductApi : Uuid -> String -> Api.Request ()
deleteProductApi productId_path auth_token =
    Api.request
        "DELETE"
        "/api/v1/products/{product_id}"
        [ ( "product_id", Uuid.toString productId_path ) ]
        []
        []
        Nothing
        (Json.Decode.succeed ())
        |> Api.withBearerToken auth_token

getProductApi : Uuid -> String -> Api.Request Api.Data.Product
getProductApi productId_path auth_token =
    Api.request
        "GET"
        "/api/v1/products/{product_id}"
        [ ( "product_id", Uuid.toString productId_path ) ]
        []
        []
        Nothing
        Api.Data.productDecoder
        |> Api.withBearerToken auth_token

getProductStockApi : Uuid -> String -> Api.Request Api.Data.ProductStock
getProductStockApi productId_path auth_token =
    Api.request
        "GET"
        "/api/v1/products/{product_id}/stock"
        [ ( "product_id", Uuid.toString productId_path ) ]
        []
        []
        Nothing
        Api.Data.productStockDecoder
        |> Api.withBearerToken auth_token

getProductsApi : Maybe Int -> Maybe Int -> Maybe String -> Maybe Bool -> String -> Api.Request (List Api.Data.Product)
getProductsApi page_query pageSize_query search_query includeDeleted_query auth_token =
    Api.request
        "GET"
        "/api/v1/products/"
        []
        [ ( "page", Maybe.map String.fromInt page_query ), ( "page_size", Maybe.map String.fromInt pageSize_query ), ( "search", Maybe.map identity search_query ), ( "include_deleted", Maybe.map (\val -> if val then "true" else "false") includeDeleted_query ) ]
        []
        Nothing
        (Json.Decode.list Api.Data.productDecoder)
        |> Api.withBearerToken auth_token

listLowStockProductsApi : Maybe Int -> String -> Api.Request (List Api.Data.ProductStock)
listLowStockProductsApi threshold_query auth_token =
    Api.request
        "GET"
        "/api/v1/products/low-stock"
        []
        [ ( "threshold", Maybe.map String.fromInt threshold_query ) ]
        []
        Nothing
        (Json.Decode.list Api.Data.productStockDecoder)
        |> Api.withBearerToken auth_token

productRestore : Uuid -> String -> Api.Request Api.Data.Product
productRestore productId_path auth_token =
    Api.request
        "POST"
        "/api/v1/products/{product_id}/restore"
        [ ( "product_id", Uuid.toString productId_path ) ]
        []
        []
        Nothing
        Api.Data.productDecoder
        |> Api.withBearerToken auth_token

updateProductApi : Uuid -> Api.Data.ProductUpdate -> String -> Api.Request Api.Data.Product
updateProductApi productId_path productUpdate_body auth_token =
    Api.request
        "PUT"
        "/api/v1/products/{product_id}"
        [ ( "product_id", Uuid.toString productId_path ) ]
        []
        []
        (Maybe.map Http.jsonBody (Just (Api.Data.encodeProductUpdate productUpdate_body)))
        Api.Data.productDecoder
        |> Api.withBearerToken auth_token

updateProductStockApi : Uuid -> Api.Data.StockUpdateRequest -> String -> Api.Request Api.Data.ProductStock
updateProductStockApi productId_path stockUpdateRequest_body auth_token =
    Api.request
        "PUT"
        "/api/v1/products/{product_id}/stock"
        [ ( "product_id", Uuid.toString productId_path ) ]
        []
        []
        (Maybe.map Http.jsonBody (Just (Api.Data.encodeStockUpdateRequest stockUpdateRequest_body)))
        Api.Data.productStockDecoder
        |> Api.withBearerToken auth_token
