{-
   SimpleBilly API
   Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

   The version of the OpenAPI document: 0.1.0
   Contact: support@simplebilly.com

   NOTE: This file is auto generated by the openapi-generator.
   https://github.com/openapitools/openapi-generator.git

   DO NOT EDIT THIS FILE MANUALLY.

   For more info on generating Elm code, see https://eriktim.github.io/openapi-elm/
-}


module Api.Request.ProductCategory exposing
    ( createProductCategory
    , deleteProductCategory
    , getProductCategory
    , listProductCategories
    , updateProductCategory
    )

import Api
import Api.Data exposing (..)
import Dict
import Http
import Json.Decode
import Json.Encode


createProductCategory : Api.Data.ProductCategory -> String -> Api.Request Api.Data.ProductCategory
createProductCategory productCategory_body auth_token =
    Api.request
        "POST"
        "/api/v1/product-categories"
        []
        []
        []
        (Maybe.map Http.jsonBody (Just (Api.Data.encodeProductCategory productCategory_body)))
        Api.Data.productCategoryDecoder
        |> Api.withBearerToken auth_token

deleteProductCategory : String -> String -> Api.Request ()
deleteProductCategory categoryId_path auth_token =
    Api.request
        "DELETE"
        "/api/v1/product-categories/{category_id}"
        [ ( "category_id", identity categoryId_path ) ]
        []
        []
        Nothing
        (Json.Decode.succeed ())
        |> Api.withBearerToken auth_token

getProductCategory : String -> String -> Api.Request Api.Data.ProductCategory
getProductCategory categoryId_path auth_token =
    Api.request
        "GET"
        "/api/v1/product-categories/{category_id}"
        [ ( "category_id", identity categoryId_path ) ]
        []
        []
        Nothing
        Api.Data.productCategoryDecoder
        |> Api.withBearerToken auth_token

listProductCategories : String -> Api.Request (List Api.Data.ProductCategory)
listProductCategories auth_token =
    Api.request
        "GET"
        "/api/v1/product-categories"
        []
        []
        []
        Nothing
        (Json.Decode.list Api.Data.productCategoryDecoder)
        |> Api.withBearerToken auth_token

updateProductCategory : String -> Api.Data.AnyType -> String -> Api.Request Api.Data.ProductCategory
updateProductCategory categoryId_path body_body auth_token =
    Api.request
        "PUT"
        "/api/v1/product-categories/{category_id}"
        [ ( "category_id", identity categoryId_path ) ]
        []
        []
        (Maybe.map Http.jsonBody (Just (encodeAnyType body_body)))
        Api.Data.productCategoryDecoder
        |> Api.withBearerToken auth_token
