{-
   SimpleBilly API
   Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

   The version of the OpenAPI document: 0.1.0
   Contact: support@simplebilly.com

   NOTE: This file is auto generated by the openapi-generator.
   https://github.com/openapitools/openapi-generator.git

   DO NOT EDIT THIS FILE MANUALLY.

   For more info on generating Elm code, see https://eriktim.github.io/openapi-elm/
-}


module Api.Request.ProformaInvoice exposing
    ( convertProformaToInvoice
    , createProformaInvoice
    , deleteProformaInvoice
    , getProformaInvoice
    , listProformaInvoices
    , updateProformaInvoice
    )

import Api
import Api.Data exposing (..)
import Dict
import Http
import Json.Decode
import Json.Encode


convertProformaToInvoice : String -> String -> Api.Request Api.Data.ConvertResponse
convertProformaToInvoice proformaId_path auth_token =
    Api.request
        "POST"
        "/api/v1/proforma-invoices/{proforma_id}/convert"
        [ ( "proforma_id", identity proformaId_path ) ]
        []
        []
        Nothing
        Api.Data.convertResponseDecoder
        |> Api.withBearerToken auth_token

createProformaInvoice : Api.Data.ProformaInvoice -> String -> Api.Request Api.Data.ProformaInvoice
createProformaInvoice proformaInvoice_body auth_token =
    Api.request
        "POST"
        "/api/v1/proforma-invoices"
        []
        []
        []
        (Maybe.map Http.jsonBody (Just (Api.Data.encodeProformaInvoice proformaInvoice_body)))
        Api.Data.proformaInvoiceDecoder
        |> Api.withBearerToken auth_token

deleteProformaInvoice : String -> String -> Api.Request ()
deleteProformaInvoice proformaId_path auth_token =
    Api.request
        "DELETE"
        "/api/v1/proforma-invoices/{proforma_id}"
        [ ( "proforma_id", identity proformaId_path ) ]
        []
        []
        Nothing
        (Json.Decode.succeed ())
        |> Api.withBearerToken auth_token

getProformaInvoice : String -> String -> Api.Request Api.Data.ProformaInvoice
getProformaInvoice proformaId_path auth_token =
    Api.request
        "GET"
        "/api/v1/proforma-invoices/{proforma_id}"
        [ ( "proforma_id", identity proformaId_path ) ]
        []
        []
        Nothing
        Api.Data.proformaInvoiceDecoder
        |> Api.withBearerToken auth_token

listProformaInvoices : Maybe Int -> Maybe Int -> Maybe String -> Maybe String -> Maybe String -> String -> Api.Request (List Api.Data.ProformaInvoice)
listProformaInvoices page_query pageSize_query status_query customerId_query orderNumber_query auth_token =
    Api.request
        "GET"
        "/api/v1/proforma-invoices/"
        []
        [ ( "page", Maybe.map String.fromInt page_query ), ( "page_size", Maybe.map String.fromInt pageSize_query ), ( "status", Maybe.map identity status_query ), ( "customer_id", Maybe.map identity customerId_query ), ( "order_number", Maybe.map identity orderNumber_query ) ]
        []
        Nothing
        (Json.Decode.list Api.Data.proformaInvoiceDecoder)
        |> Api.withBearerToken auth_token

updateProformaInvoice : String -> Api.Data.AnyType -> String -> Api.Request Api.Data.ProformaInvoice
updateProformaInvoice proformaId_path body_body auth_token =
    Api.request
        "PUT"
        "/api/v1/proforma-invoices/{proforma_id}"
        [ ( "proforma_id", identity proformaId_path ) ]
        []
        []
        (Maybe.map Http.jsonBody (Just (encodeAnyType body_body)))
        Api.Data.proformaInvoiceDecoder
        |> Api.withBearerToken auth_token
