{-
   SimpleBilly API
   Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

   The version of the OpenAPI document: 0.1.0
   Contact: support@simplebilly.com

   NOTE: This file is auto generated by the openapi-generator.
   https://github.com/openapitools/openapi-generator.git

   DO NOT EDIT THIS FILE MANUALLY.

   For more info on generating Elm code, see https://eriktim.github.io/openapi-elm/
-}


module Api.Request.PublicReturns exposing
    ( getPublicReturnStatus
    , listPublicReturns
    , requestPublicReturn
    )

import Api
import Api.Data exposing (..)
import Dict
import Http
import Json.Decode
import Json.Encode


{-| Customer checks the status of a return (public, no auth). The return is only revealed when its linked order's email matches.
-}
getPublicReturnStatus : String -> Maybe String -> Maybe String -> Maybe String -> String -> Api.Request Api.Data.PublicReturnStatusResponse
getPublicReturnStatus email_query returnNumber_query returnOrderId_query orderNumber_query auth_token =
    Api.request
        "GET"
        "/api/v1/public/returns/status"
        []
        [ ( "returnNumber", Maybe.map identity returnNumber_query ), ( "returnOrderId", Maybe.map identity returnOrderId_query ), ( "email", Just <| identity email_query ), ( "orderNumber", Maybe.map identity orderNumber_query ) ]
        []
        Nothing
        Api.Data.publicReturnStatusResponseDecoder
        |> Api.withBearerToken auth_token

{-| List all returns for an order (public, no auth).
-}
listPublicReturns : String -> String -> String -> Api.Request (List Api.Data.PublicReturnStatusResponse)
listPublicReturns orderNumber_query email_query auth_token =
    Api.request
        "GET"
        "/api/v1/public/returns/list"
        []
        [ ( "orderNumber", Just <| identity orderNumber_query ), ( "email", Just <| identity email_query ) ]
        []
        Nothing
        (Json.Decode.list Api.Data.publicReturnStatusResponseDecoder)
        |> Api.withBearerToken auth_token

{-| Customer requests a return for an order (public, no auth).
-}
requestPublicReturn : Api.Data.PublicReturnRequest -> String -> Api.Request Api.Data.PublicReturnResponse
requestPublicReturn publicReturnRequest_body auth_token =
    Api.request
        "POST"
        "/api/v1/public/returns/request"
        []
        []
        []
        (Maybe.map Http.jsonBody (Just (Api.Data.encodePublicReturnRequest publicReturnRequest_body)))
        Api.Data.publicReturnResponseDecoder
        |> Api.withBearerToken auth_token
