{-
   SimpleBilly API
   Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

   The version of the OpenAPI document: 0.1.0
   Contact: support@simplebilly.com

   NOTE: This file is auto generated by the openapi-generator.
   https://github.com/openapitools/openapi-generator.git

   DO NOT EDIT THIS FILE MANUALLY.

   For more info on generating Elm code, see https://eriktim.github.io/openapi-elm/
-}


module Api.Request.PurchaseOrder exposing
    ( createPurchaseOrder
    , deletePurchaseOrder
    , getPurchaseOrder
    , listPurchaseOrders
    , matchInvoice
    , updatePurchaseOrder
    , updatePurchaseOrderStatus
    )

import Api
import Api.Data exposing (..)
import Dict
import Http
import Json.Decode
import Json.Encode


createPurchaseOrder : Api.Data.PurchaseOrder -> String -> Api.Request Api.Data.PurchaseOrder
createPurchaseOrder purchaseOrder_body auth_token =
    Api.request
        "POST"
        "/api/v1/purchase-orders"
        []
        []
        []
        (Maybe.map Http.jsonBody (Just (Api.Data.encodePurchaseOrder purchaseOrder_body)))
        Api.Data.purchaseOrderDecoder
        |> Api.withBearerToken auth_token

deletePurchaseOrder : String -> String -> Api.Request ()
deletePurchaseOrder purchaseOrderId_path auth_token =
    Api.request
        "DELETE"
        "/api/v1/purchase-orders/{purchase_order_id}"
        [ ( "purchase_order_id", identity purchaseOrderId_path ) ]
        []
        []
        Nothing
        (Json.Decode.succeed ())
        |> Api.withBearerToken auth_token

getPurchaseOrder : String -> String -> Api.Request Api.Data.PurchaseOrder
getPurchaseOrder purchaseOrderId_path auth_token =
    Api.request
        "GET"
        "/api/v1/purchase-orders/{purchase_order_id}"
        [ ( "purchase_order_id", identity purchaseOrderId_path ) ]
        []
        []
        Nothing
        Api.Data.purchaseOrderDecoder
        |> Api.withBearerToken auth_token

listPurchaseOrders : Maybe Int -> Maybe Int -> Maybe String -> Maybe String -> Maybe String -> String -> Api.Request (List Api.Data.PurchaseOrder)
listPurchaseOrders page_query pageSize_query status_query supplierName_query search_query auth_token =
    Api.request
        "GET"
        "/api/v1/purchase-orders/"
        []
        [ ( "page", Maybe.map String.fromInt page_query ), ( "page_size", Maybe.map String.fromInt pageSize_query ), ( "status", Maybe.map identity status_query ), ( "supplier_name", Maybe.map identity supplierName_query ), ( "search", Maybe.map identity search_query ) ]
        []
        Nothing
        (Json.Decode.list Api.Data.purchaseOrderDecoder)
        |> Api.withBearerToken auth_token

{-| 3-way invoice check (Rechnungsprüfung): compares the purchase order line items, the quantities received via goods receipts, and the supplier invoice line items, reporting quantity and price variances per product.
-}
matchInvoice : String -> Api.Data.InvoiceMatchRequest -> String -> Api.Request Api.Data.AnyType
matchInvoice purchaseOrderId_path invoiceMatchRequest_body auth_token =
    Api.request
        "POST"
        "/api/v1/purchase-orders/{purchase_order_id}/match-invoice"
        [ ( "purchase_order_id", identity purchaseOrderId_path ) ]
        []
        []
        (Maybe.map Http.jsonBody (Just (Api.Data.encodeInvoiceMatchRequest invoiceMatchRequest_body)))
        Api.Data.anyTypeDecoder
        |> Api.withBearerToken auth_token

updatePurchaseOrder : String -> Api.Data.AnyType -> String -> Api.Request Api.Data.PurchaseOrder
updatePurchaseOrder purchaseOrderId_path body_body auth_token =
    Api.request
        "PUT"
        "/api/v1/purchase-orders/{purchase_order_id}"
        [ ( "purchase_order_id", identity purchaseOrderId_path ) ]
        []
        []
        (Maybe.map Http.jsonBody (Just (encodeAnyType body_body)))
        Api.Data.purchaseOrderDecoder
        |> Api.withBearerToken auth_token

updatePurchaseOrderStatus : String -> Api.Data.PurchaseOrderStatusUpdate -> String -> Api.Request Api.Data.PurchaseOrder
updatePurchaseOrderStatus purchaseOrderId_path purchaseOrderStatusUpdate_body auth_token =
    Api.request
        "PUT"
        "/api/v1/purchase-orders/{purchase_order_id}/status"
        [ ( "purchase_order_id", identity purchaseOrderId_path ) ]
        []
        []
        (Maybe.map Http.jsonBody (Just (Api.Data.encodePurchaseOrderStatusUpdate purchaseOrderStatusUpdate_body)))
        Api.Data.purchaseOrderDecoder
        |> Api.withBearerToken auth_token
