{-
   SimpleBilly API
   Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

   The version of the OpenAPI document: 0.1.0
   Contact: support@simplebilly.com

   NOTE: This file is auto generated by the openapi-generator.
   https://github.com/openapitools/openapi-generator.git

   DO NOT EDIT THIS FILE MANUALLY.

   For more info on generating Elm code, see https://eriktim.github.io/openapi-elm/
-}


module Api.Request.Quotation exposing
    ( createQuotation
    , deleteQuotation
    , downloadQuotationPdf
    , getQuotation
    , listQuotations
    , pursueQuotation
    , quotationRestore
    , updateQuotation
    )

import Api
import Api.Data exposing (..)
import Dict
import Http
import Json.Decode
import Json.Encode


createQuotation : Api.Data.QuotationCreate -> String -> Api.Request Api.Data.Quotation
createQuotation quotationCreate_body auth_token =
    Api.request
        "POST"
        "/api/v1/quotations"
        []
        []
        []
        (Maybe.map Http.jsonBody (Just (Api.Data.encodeQuotationCreate quotationCreate_body)))
        Api.Data.quotationDecoder
        |> Api.withBearerToken auth_token

deleteQuotation : String -> String -> Api.Request ()
deleteQuotation quotationId_path auth_token =
    Api.request
        "DELETE"
        "/api/v1/quotations/{quotation_id}"
        [ ( "quotation_id", identity quotationId_path ) ]
        []
        []
        Nothing
        (Json.Decode.succeed ())
        |> Api.withBearerToken auth_token

downloadQuotationPdf : String -> String -> Api.Request ()
downloadQuotationPdf quotationId_path auth_token =
    Api.request
        "GET"
        "/api/v1/quotations/{quotation_id}/pdf"
        [ ( "quotation_id", identity quotationId_path ) ]
        []
        []
        Nothing
        (Json.Decode.succeed ())
        |> Api.withBearerToken auth_token

getQuotation : String -> String -> Api.Request Api.Data.Quotation
getQuotation quotationId_path auth_token =
    Api.request
        "GET"
        "/api/v1/quotations/{quotation_id}"
        [ ( "quotation_id", identity quotationId_path ) ]
        []
        []
        Nothing
        Api.Data.quotationDecoder
        |> Api.withBearerToken auth_token

listQuotations : Maybe Int -> Maybe Int -> Maybe String -> Maybe Bool -> String -> Api.Request (List Api.Data.Quotation)
listQuotations page_query pageSize_query search_query includeDeleted_query auth_token =
    Api.request
        "GET"
        "/api/v1/quotations/"
        []
        [ ( "page", Maybe.map String.fromInt page_query ), ( "page_size", Maybe.map String.fromInt pageSize_query ), ( "search", Maybe.map identity search_query ), ( "include_deleted", Maybe.map (\val -> if val then "true" else "false") includeDeleted_query ) ]
        []
        Nothing
        (Json.Decode.list Api.Data.quotationDecoder)
        |> Api.withBearerToken auth_token

pursueQuotation : String -> String -> Api.Request Api.Data.OrderConfirmation
pursueQuotation quotationId_path auth_token =
    Api.request
        "POST"
        "/api/v1/quotations/{quotation_id}/pursue"
        [ ( "quotation_id", identity quotationId_path ) ]
        []
        []
        Nothing
        Api.Data.orderConfirmationDecoder
        |> Api.withBearerToken auth_token

quotationRestore : String -> String -> Api.Request Api.Data.Quotation
quotationRestore quotationId_path auth_token =
    Api.request
        "POST"
        "/api/v1/quotations/{quotation_id}/restore"
        [ ( "quotation_id", identity quotationId_path ) ]
        []
        []
        Nothing
        Api.Data.quotationDecoder
        |> Api.withBearerToken auth_token

updateQuotation : String -> Api.Data.AnyType -> String -> Api.Request Api.Data.Quotation
updateQuotation quotationId_path body_body auth_token =
    Api.request
        "PUT"
        "/api/v1/quotations/{quotation_id}"
        [ ( "quotation_id", identity quotationId_path ) ]
        []
        []
        (Maybe.map Http.jsonBody (Just (encodeAnyType body_body)))
        Api.Data.quotationDecoder
        |> Api.withBearerToken auth_token
