{-
   SimpleBilly API
   Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

   The version of the OpenAPI document: 0.1.0
   Contact: support@simplebilly.com

   NOTE: This file is auto generated by the openapi-generator.
   https://github.com/openapitools/openapi-generator.git

   DO NOT EDIT THIS FILE MANUALLY.

   For more info on generating Elm code, see https://eriktim.github.io/openapi-elm/
-}


module Api.Request.RecurringTemplate exposing
    ( createRecurringTemplate
    , deleteRecurringTemplate
    , getRecurringTemplate
    , listRecurringTemplates
    )

import Api
import Api.Data exposing (..)
import Dict
import Http
import Json.Decode
import Json.Encode


createRecurringTemplate : Api.Data.AnyType -> String -> Api.Request Api.Data.RecurringTemplate
createRecurringTemplate body_body auth_token =
    Api.request
        "POST"
        "/api/v1/recurring-templates"
        []
        []
        []
        (Maybe.map Http.jsonBody (Just (encodeAnyType body_body)))
        Api.Data.recurringTemplateDecoder
        |> Api.withBearerToken auth_token

deleteRecurringTemplate : String -> String -> Api.Request ()
deleteRecurringTemplate templateId_path auth_token =
    Api.request
        "DELETE"
        "/api/v1/recurring-templates/{template_id}"
        [ ( "template_id", identity templateId_path ) ]
        []
        []
        Nothing
        (Json.Decode.succeed ())
        |> Api.withBearerToken auth_token

getRecurringTemplate : String -> String -> Api.Request Api.Data.RecurringTemplate
getRecurringTemplate templateId_path auth_token =
    Api.request
        "GET"
        "/api/v1/recurring-templates/{template_id}"
        [ ( "template_id", identity templateId_path ) ]
        []
        []
        Nothing
        Api.Data.recurringTemplateDecoder
        |> Api.withBearerToken auth_token

listRecurringTemplates : String -> Api.Request (List Api.Data.RecurringTemplate)
listRecurringTemplates auth_token =
    Api.request
        "GET"
        "/api/v1/recurring-templates/"
        []
        []
        []
        Nothing
        (Json.Decode.list Api.Data.recurringTemplateDecoder)
        |> Api.withBearerToken auth_token
