{-
   SimpleBilly API
   Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

   The version of the OpenAPI document: 0.1.0
   Contact: support@simplebilly.com

   NOTE: This file is auto generated by the openapi-generator.
   https://github.com/openapitools/openapi-generator.git

   DO NOT EDIT THIS FILE MANUALLY.

   For more info on generating Elm code, see https://eriktim.github.io/openapi-elm/
-}


module Api.Request.ReorderProposal exposing
    ( applyReorderProposal
    , getReorderProposal
    )

import Api
import Api.Data exposing (..)
import Dict
import Http
import Json.Decode
import Json.Encode


{-| Convert a reorder proposal into a draft purchase order.

Returns the created purchase order id. Suggested line items are generated with the current reorder quantity per product.

-}
applyReorderProposal : Maybe Bool -> Maybe String -> String -> Api.Request Api.Data.AnyType
applyReorderProposal configuredOnly_query warehouseId_query auth_token =
    Api.request
        "POST"
        "/api/v1/reorder-proposals/apply"
        []
        [ ( "configuredOnly", Maybe.map (\val -> if val then "true" else "false") configuredOnly_query ), ( "warehouseId", Maybe.map identity warehouseId_query ) ]
        []
        Nothing
        Api.Data.anyTypeDecoder
        |> Api.withBearerToken auth_token

getReorderProposal : Maybe Bool -> Maybe String -> String -> Api.Request Api.Data.ReorderProposalResponse
getReorderProposal configuredOnly_query warehouseId_query auth_token =
    Api.request
        "GET"
        "/api/v1/reorder-proposals"
        []
        [ ( "configuredOnly", Maybe.map (\val -> if val then "true" else "false") configuredOnly_query ), ( "warehouseId", Maybe.map identity warehouseId_query ) ]
        []
        Nothing
        Api.Data.reorderProposalResponseDecoder
        |> Api.withBearerToken auth_token
