{-
   SimpleBilly API
   Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

   The version of the OpenAPI document: 0.1.0
   Contact: support@simplebilly.com

   NOTE: This file is auto generated by the openapi-generator.
   https://github.com/openapitools/openapi-generator.git

   DO NOT EDIT THIS FILE MANUALLY.

   For more info on generating Elm code, see https://eriktim.github.io/openapi-elm/
-}


module Api.Request.Reports exposing
    ( bilanzReportApi
    , guvReportApi
    , kontenansichtReportApi
    , umsatzsteuerReportApi
    )

import Api
import Api.Data exposing (..)
import Dict
import Http
import Json.Decode
import Json.Encode


{-| Bilanz (Balance Sheet)
-}
bilanzReportApi : Maybe Int -> Maybe Int -> Maybe String -> Maybe String -> Maybe Int -> Maybe Int -> String -> Api.Request Api.Data.BilanzReport
bilanzReportApi year_query month_query dateFrom_query dateTo_query page_query pageSize_query auth_token =
    Api.request
        "GET"
        "/api/v1/bookkeeping/reports/bilanz"
        []
        [ ( "year", Maybe.map String.fromInt year_query ), ( "month", Maybe.map String.fromInt month_query ), ( "date_from", Maybe.map identity dateFrom_query ), ( "date_to", Maybe.map identity dateTo_query ), ( "page", Maybe.map String.fromInt page_query ), ( "page_size", Maybe.map String.fromInt pageSize_query ) ]
        []
        Nothing
        Api.Data.bilanzReportDecoder
        |> Api.withBearerToken auth_token

{-| Gewinn- und Verlustrechnung (P&L statement)
-}
guvReportApi : Maybe Int -> Maybe Int -> Maybe String -> Maybe String -> Maybe Int -> Maybe Int -> String -> Api.Request Api.Data.GuVReport
guvReportApi year_query month_query dateFrom_query dateTo_query page_query pageSize_query auth_token =
    Api.request
        "GET"
        "/api/v1/bookkeeping/reports/guv"
        []
        [ ( "year", Maybe.map String.fromInt year_query ), ( "month", Maybe.map String.fromInt month_query ), ( "date_from", Maybe.map identity dateFrom_query ), ( "date_to", Maybe.map identity dateTo_query ), ( "page", Maybe.map String.fromInt page_query ), ( "page_size", Maybe.map String.fromInt pageSize_query ) ]
        []
        Nothing
        Api.Data.guVReportDecoder
        |> Api.withBearerToken auth_token

{-| Kontenansicht (Account Overview)
-}
kontenansichtReportApi : Maybe Int -> Maybe Int -> Maybe String -> Maybe String -> Maybe Int -> Maybe Int -> String -> Api.Request Api.Data.KontoReport
kontenansichtReportApi year_query month_query dateFrom_query dateTo_query page_query pageSize_query auth_token =
    Api.request
        "GET"
        "/api/v1/bookkeeping/reports/kontenansicht"
        []
        [ ( "year", Maybe.map String.fromInt year_query ), ( "month", Maybe.map String.fromInt month_query ), ( "date_from", Maybe.map identity dateFrom_query ), ( "date_to", Maybe.map identity dateTo_query ), ( "page", Maybe.map String.fromInt page_query ), ( "page_size", Maybe.map String.fromInt pageSize_query ) ]
        []
        Nothing
        Api.Data.kontoReportDecoder
        |> Api.withBearerToken auth_token

{-| Umsatzsteuer-Voranmeldung (VAT report)
-}
umsatzsteuerReportApi : Maybe Int -> Maybe Int -> Maybe String -> Maybe String -> Maybe Int -> Maybe Int -> String -> Api.Request Api.Data.UmsatzsteuerReport
umsatzsteuerReportApi year_query month_query dateFrom_query dateTo_query page_query pageSize_query auth_token =
    Api.request
        "GET"
        "/api/v1/bookkeeping/reports/umsatzsteuer"
        []
        [ ( "year", Maybe.map String.fromInt year_query ), ( "month", Maybe.map String.fromInt month_query ), ( "date_from", Maybe.map identity dateFrom_query ), ( "date_to", Maybe.map identity dateTo_query ), ( "page", Maybe.map String.fromInt page_query ), ( "page_size", Maybe.map String.fromInt pageSize_query ) ]
        []
        Nothing
        Api.Data.umsatzsteuerReportDecoder
        |> Api.withBearerToken auth_token
