{-
   SimpleBilly API
   Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

   The version of the OpenAPI document: 0.1.0
   Contact: support@simplebilly.com

   NOTE: This file is auto generated by the openapi-generator.
   https://github.com/openapitools/openapi-generator.git

   DO NOT EDIT THIS FILE MANUALLY.

   For more info on generating Elm code, see https://eriktim.github.io/openapi-elm/
-}


module Api.Request.ReturnOrder exposing
    ( createReturnOrder
    , deleteReturnOrder
    , getReturnOrder
    , listReturnOrders
    , returnLogisticsQueue
    , returnLogisticsSummary
    , updateReturnOrder
    , updateReturnOrderStatus
    )

import Api
import Api.Data exposing (..)
import Dict
import Http
import Json.Decode
import Json.Encode


createReturnOrder : Api.Data.ReturnOrder -> String -> Api.Request Api.Data.ReturnOrder
createReturnOrder returnOrder_body auth_token =
    Api.request
        "POST"
        "/api/v1/returns"
        []
        []
        []
        (Maybe.map Http.jsonBody (Just (Api.Data.encodeReturnOrder returnOrder_body)))
        Api.Data.returnOrderDecoder
        |> Api.withBearerToken auth_token

deleteReturnOrder : String -> String -> Api.Request ()
deleteReturnOrder returnOrderId_path auth_token =
    Api.request
        "DELETE"
        "/api/v1/returns/{return_order_id}"
        [ ( "return_order_id", identity returnOrderId_path ) ]
        []
        []
        Nothing
        (Json.Decode.succeed ())
        |> Api.withBearerToken auth_token

getReturnOrder : String -> String -> Api.Request Api.Data.ReturnOrder
getReturnOrder returnOrderId_path auth_token =
    Api.request
        "GET"
        "/api/v1/returns/{return_order_id}"
        [ ( "return_order_id", identity returnOrderId_path ) ]
        []
        []
        Nothing
        Api.Data.returnOrderDecoder
        |> Api.withBearerToken auth_token

listReturnOrders : Maybe Int -> Maybe Int -> Maybe String -> Maybe String -> Maybe String -> String -> Api.Request (List Api.Data.ReturnOrder)
listReturnOrders page_query pageSize_query status_query customerName_query orderNumber_query auth_token =
    Api.request
        "GET"
        "/api/v1/returns/"
        []
        [ ( "page", Maybe.map String.fromInt page_query ), ( "page_size", Maybe.map String.fromInt pageSize_query ), ( "status", Maybe.map identity status_query ), ( "customer_name", Maybe.map identity customerName_query ), ( "order_number", Maybe.map identity orderNumber_query ) ]
        []
        Nothing
        (Json.Decode.list Api.Data.returnOrderDecoder)
        |> Api.withBearerToken auth_token

returnLogisticsQueue : String -> Api.Request (List Api.Data.ReturnLogisticsQueueItem)
returnLogisticsQueue auth_token =
    Api.request
        "GET"
        "/api/v1/returns/logistics-queue"
        []
        []
        []
        Nothing
        (Json.Decode.list Api.Data.returnLogisticsQueueItemDecoder)
        |> Api.withBearerToken auth_token

{-| Returns-logistics aggregation for the dashboard: quantities received, restocked and scrapped per warehouse.
-}
returnLogisticsSummary : String -> Api.Request Api.Data.ReturnLogisticsSummary
returnLogisticsSummary auth_token =
    Api.request
        "GET"
        "/api/v1/returns/logistics-summary"
        []
        []
        []
        Nothing
        Api.Data.returnLogisticsSummaryDecoder
        |> Api.withBearerToken auth_token

updateReturnOrder : String -> Api.Data.AnyType -> String -> Api.Request Api.Data.ReturnOrder
updateReturnOrder returnOrderId_path body_body auth_token =
    Api.request
        "PUT"
        "/api/v1/returns/{return_order_id}"
        [ ( "return_order_id", identity returnOrderId_path ) ]
        []
        []
        (Maybe.map Http.jsonBody (Just (encodeAnyType body_body)))
        Api.Data.returnOrderDecoder
        |> Api.withBearerToken auth_token

updateReturnOrderStatus : String -> Api.Data.ReturnOrderStatusUpdate -> String -> Api.Request Api.Data.ReturnOrder
updateReturnOrderStatus returnOrderId_path returnOrderStatusUpdate_body auth_token =
    Api.request
        "PUT"
        "/api/v1/returns/{return_order_id}/status"
        [ ( "return_order_id", identity returnOrderId_path ) ]
        []
        []
        (Maybe.map Http.jsonBody (Just (Api.Data.encodeReturnOrderStatusUpdate returnOrderStatusUpdate_body)))
        Api.Data.returnOrderDecoder
        |> Api.withBearerToken auth_token
