{-
   SimpleBilly API
   Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

   The version of the OpenAPI document: 0.1.0
   Contact: support@simplebilly.com

   NOTE: This file is auto generated by the openapi-generator.
   https://github.com/openapitools/openapi-generator.git

   DO NOT EDIT THIS FILE MANUALLY.

   For more info on generating Elm code, see https://eriktim.github.io/openapi-elm/
-}


module Api.Request.Rfq exposing
    ( convertRfq
    , createRfq
    , deleteRfq
    , getRfq
    , listRfqs
    , updateRfq
    , updateRfqStatus
    )

import Api
import Api.Data exposing (..)
import Dict
import Http
import Json.Decode
import Json.Encode


{-| Convert an RFQ into a draft purchase order using the quoted unit prices (falling back to the requested prices, then leaving them blank). Marks the RFQ as `converted`.
-}
convertRfq : String -> String -> Api.Request Api.Data.AnyType
convertRfq rfqId_path auth_token =
    Api.request
        "POST"
        "/api/v1/rfqs/{rfq_id}/convert"
        [ ( "rfq_id", identity rfqId_path ) ]
        []
        []
        Nothing
        Api.Data.anyTypeDecoder
        |> Api.withBearerToken auth_token

createRfq : Api.Data.Rfq -> String -> Api.Request Api.Data.Rfq
createRfq rfq_body auth_token =
    Api.request
        "POST"
        "/api/v1/rfqs"
        []
        []
        []
        (Maybe.map Http.jsonBody (Just (Api.Data.encodeRfq rfq_body)))
        Api.Data.rfqDecoder
        |> Api.withBearerToken auth_token

deleteRfq : String -> String -> Api.Request ()
deleteRfq rfqId_path auth_token =
    Api.request
        "DELETE"
        "/api/v1/rfqs/{rfq_id}"
        [ ( "rfq_id", identity rfqId_path ) ]
        []
        []
        Nothing
        (Json.Decode.succeed ())
        |> Api.withBearerToken auth_token

getRfq : String -> String -> Api.Request Api.Data.Rfq
getRfq rfqId_path auth_token =
    Api.request
        "GET"
        "/api/v1/rfqs/{rfq_id}"
        [ ( "rfq_id", identity rfqId_path ) ]
        []
        []
        Nothing
        Api.Data.rfqDecoder
        |> Api.withBearerToken auth_token

listRfqs : Maybe Int -> Maybe Int -> Maybe String -> Maybe String -> String -> Api.Request (List Api.Data.Rfq)
listRfqs page_query pageSize_query status_query supplierName_query auth_token =
    Api.request
        "GET"
        "/api/v1/rfqs/"
        []
        [ ( "page", Maybe.map String.fromInt page_query ), ( "page_size", Maybe.map String.fromInt pageSize_query ), ( "status", Maybe.map identity status_query ), ( "supplier_name", Maybe.map identity supplierName_query ) ]
        []
        Nothing
        (Json.Decode.list Api.Data.rfqDecoder)
        |> Api.withBearerToken auth_token

updateRfq : String -> Api.Data.AnyType -> String -> Api.Request Api.Data.Rfq
updateRfq rfqId_path body_body auth_token =
    Api.request
        "PUT"
        "/api/v1/rfqs/{rfq_id}"
        [ ( "rfq_id", identity rfqId_path ) ]
        []
        []
        (Maybe.map Http.jsonBody (Just (encodeAnyType body_body)))
        Api.Data.rfqDecoder
        |> Api.withBearerToken auth_token

updateRfqStatus : String -> Api.Data.RfqStatusUpdate -> String -> Api.Request Api.Data.Rfq
updateRfqStatus rfqId_path rfqStatusUpdate_body auth_token =
    Api.request
        "PUT"
        "/api/v1/rfqs/{rfq_id}/status"
        [ ( "rfq_id", identity rfqId_path ) ]
        []
        []
        (Maybe.map Http.jsonBody (Just (Api.Data.encodeRfqStatusUpdate rfqStatusUpdate_body)))
        Api.Data.rfqDecoder
        |> Api.withBearerToken auth_token
