{-
   SimpleBilly API
   Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

   The version of the OpenAPI document: 0.1.0
   Contact: support@simplebilly.com

   NOTE: This file is auto generated by the openapi-generator.
   https://github.com/openapitools/openapi-generator.git

   DO NOT EDIT THIS FILE MANUALLY.

   For more info on generating Elm code, see https://eriktim.github.io/openapi-elm/
-}


module Api.Request.Search exposing
    ( globalSearch
    , myPermissions
    )

import Api
import Api.Data exposing (..)
import Dict
import Http
import Json.Decode
import Json.Encode


{-| GET /api/v1/search?q=...
-}
globalSearch : String -> String -> Api.Request Api.Data.AnyType
globalSearch q_query auth_token =
    Api.request
        "GET"
        "/api/v1/search"
        []
        [ ( "q", Just <| identity q_query ) ]
        []
        Nothing
        Api.Data.anyTypeDecoder
        |> Api.withBearerToken auth_token

{-| GET /api/v1/me/permissions — resolved permissions from the auth token, used by the frontend to show/hide admin navigation.
-}
myPermissions : String -> Api.Request Api.Data.AnyType
myPermissions auth_token =
    Api.request
        "GET"
        "/api/v1/me/permissions"
        []
        []
        []
        Nothing
        Api.Data.anyTypeDecoder
        |> Api.withBearerToken auth_token
