{-
   SimpleBilly API
   Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

   The version of the OpenAPI document: 0.1.0
   Contact: support@simplebilly.com

   NOTE: This file is auto generated by the openapi-generator.
   https://github.com/openapitools/openapi-generator.git

   DO NOT EDIT THIS FILE MANUALLY.

   For more info on generating Elm code, see https://eriktim.github.io/openapi-elm/
-}


module Api.Request.Shipment exposing
    ( createShipment
    , createShipmentFromOrder
    , deleteShipment
    , getShipment
    , listShipments
    , trackOrderPublic
    , trackShipmentApi
    , updateShipmentStatus
    )

import Api
import Api.Data exposing (..)
import Dict
import Http
import Json.Decode
import Json.Encode


createShipment : Api.Data.Shipment -> String -> Api.Request Api.Data.Shipment
createShipment shipment_body auth_token =
    Api.request
        "POST"
        "/api/v1/shipments"
        []
        []
        []
        (Maybe.map Http.jsonBody (Just (Api.Data.encodeShipment shipment_body)))
        Api.Data.shipmentDecoder
        |> Api.withBearerToken auth_token

{-| Create a real shipment for an order: calls the configured carrier's label API, stores the returned tracking/label on a new shipment row, and marks the order as shipped.
-}
createShipmentFromOrder : String -> Api.Data.CreateShipmentRequest -> String -> Api.Request Api.Data.Shipment
createShipmentFromOrder orderNumber_path createShipmentRequest_body auth_token =
    Api.request
        "POST"
        "/api/v1/orders/{order_number}/shipments"
        [ ( "order_number", identity orderNumber_path ) ]
        []
        []
        (Maybe.map Http.jsonBody (Just (Api.Data.encodeCreateShipmentRequest createShipmentRequest_body)))
        Api.Data.shipmentDecoder
        |> Api.withBearerToken auth_token

deleteShipment : String -> String -> Api.Request ()
deleteShipment shipmentId_path auth_token =
    Api.request
        "DELETE"
        "/api/v1/shipments/{shipment_id}"
        [ ( "shipment_id", identity shipmentId_path ) ]
        []
        []
        Nothing
        (Json.Decode.succeed ())
        |> Api.withBearerToken auth_token

getShipment : String -> String -> Api.Request Api.Data.Shipment
getShipment shipmentId_path auth_token =
    Api.request
        "GET"
        "/api/v1/shipments/{shipment_id}"
        [ ( "shipment_id", identity shipmentId_path ) ]
        []
        []
        Nothing
        Api.Data.shipmentDecoder
        |> Api.withBearerToken auth_token

listShipments : Maybe Int -> Maybe Int -> Maybe String -> Maybe Bool -> String -> Api.Request (List Api.Data.Shipment)
listShipments page_query pageSize_query search_query includeDeleted_query auth_token =
    Api.request
        "GET"
        "/api/v1/shipments"
        []
        [ ( "page", Maybe.map String.fromInt page_query ), ( "page_size", Maybe.map String.fromInt pageSize_query ), ( "search", Maybe.map identity search_query ), ( "include_deleted", Maybe.map (\val -> if val then "true" else "false") includeDeleted_query ) ]
        []
        Nothing
        (Json.Decode.list Api.Data.shipmentDecoder)
        |> Api.withBearerToken auth_token

{-| Customer-facing tracking lookup: order number + email → shipment status and live carrier events. No auth (public storefront API).
-}
trackOrderPublic : Api.Data.TrackOrderRequest -> String -> Api.Request Api.Data.TrackOrderResponse
trackOrderPublic trackOrderRequest_body auth_token =
    Api.request
        "POST"
        "/api/v1/public/track"
        []
        []
        []
        (Maybe.map Http.jsonBody (Just (Api.Data.encodeTrackOrderRequest trackOrderRequest_body)))
        Api.Data.trackOrderResponseDecoder
        |> Api.withBearerToken auth_token

trackShipmentApi : String -> String -> Api.Request Api.Data.TrackingInfo
trackShipmentApi shipmentId_path auth_token =
    Api.request
        "GET"
        "/api/v1/shipments/{shipment_id}/tracking"
        [ ( "shipment_id", identity shipmentId_path ) ]
        []
        []
        Nothing
        Api.Data.trackingInfoDecoder
        |> Api.withBearerToken auth_token

updateShipmentStatus : String -> Api.Data.ShipmentStatusUpdate -> String -> Api.Request Api.Data.Shipment
updateShipmentStatus shipmentId_path shipmentStatusUpdate_body auth_token =
    Api.request
        "PUT"
        "/api/v1/shipments/{shipment_id}/status"
        [ ( "shipment_id", identity shipmentId_path ) ]
        []
        []
        (Maybe.map Http.jsonBody (Just (Api.Data.encodeShipmentStatusUpdate shipmentStatusUpdate_body)))
        Api.Data.shipmentDecoder
        |> Api.withBearerToken auth_token
