{-
   SimpleBilly API
   Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

   The version of the OpenAPI document: 0.1.0
   Contact: support@simplebilly.com

   NOTE: This file is auto generated by the openapi-generator.
   https://github.com/openapitools/openapi-generator.git

   DO NOT EDIT THIS FILE MANUALLY.

   For more info on generating Elm code, see https://eriktim.github.io/openapi-elm/
-}


module Api.Request.ShippingThreshold exposing
    ( createShippingThreshold
    , deleteShippingThreshold
    , getDeliverable
    , getShippingThreshold
    , listShippingThresholds
    , updateShippingThreshold
    )

import Api
import Api.Data exposing (..)
import Dict
import Http
import Json.Decode
import Json.Encode
import Uuid exposing (Uuid)


createShippingThreshold : Api.Data.ShippingThresholdCreate -> String -> Api.Request Api.Data.ShippingThreshold
createShippingThreshold shippingThresholdCreate_body auth_token =
    Api.request
        "POST"
        "/api/v1/shipping-thresholds"
        []
        []
        []
        (Maybe.map Http.jsonBody (Just (Api.Data.encodeShippingThresholdCreate shippingThresholdCreate_body)))
        Api.Data.shippingThresholdDecoder
        |> Api.withBearerToken auth_token

deleteShippingThreshold : String -> String -> Api.Request ()
deleteShippingThreshold thresholdId_path auth_token =
    Api.request
        "DELETE"
        "/api/v1/shipping-thresholds/{threshold_id}"
        [ ( "threshold_id", identity thresholdId_path ) ]
        []
        []
        Nothing
        (Json.Decode.succeed ())
        |> Api.withBearerToken auth_token

getDeliverable : Uuid -> Maybe String -> String -> Api.Request Api.Data.DeliverableResponse
getDeliverable productId_query warehouseId_query auth_token =
    Api.request
        "GET"
        "/api/v1/shipping-thresholds/deliverable"
        []
        [ ( "productId", Just <| Uuid.toString productId_query ), ( "warehouseId", Maybe.map identity warehouseId_query ) ]
        []
        Nothing
        Api.Data.deliverableResponseDecoder
        |> Api.withBearerToken auth_token

getShippingThreshold : String -> String -> Api.Request Api.Data.ShippingThreshold
getShippingThreshold thresholdId_path auth_token =
    Api.request
        "GET"
        "/api/v1/shipping-thresholds/{threshold_id}"
        [ ( "threshold_id", identity thresholdId_path ) ]
        []
        []
        Nothing
        Api.Data.shippingThresholdDecoder
        |> Api.withBearerToken auth_token

listShippingThresholds : Maybe Int -> Maybe Int -> Maybe Uuid -> Maybe String -> Maybe Bool -> String -> Api.Request (List Api.Data.ShippingThreshold)
listShippingThresholds page_query pageSize_query productId_query warehouseId_query isActive_query auth_token =
    Api.request
        "GET"
        "/api/v1/shipping-thresholds/"
        []
        [ ( "page", Maybe.map String.fromInt page_query ), ( "page_size", Maybe.map String.fromInt pageSize_query ), ( "product_id", Maybe.map Uuid.toString productId_query ), ( "warehouse_id", Maybe.map identity warehouseId_query ), ( "is_active", Maybe.map (\val -> if val then "true" else "false") isActive_query ) ]
        []
        Nothing
        (Json.Decode.list Api.Data.shippingThresholdDecoder)
        |> Api.withBearerToken auth_token

updateShippingThreshold : String -> Api.Data.ShippingThresholdUpdate -> String -> Api.Request Api.Data.ShippingThreshold
updateShippingThreshold thresholdId_path shippingThresholdUpdate_body auth_token =
    Api.request
        "PUT"
        "/api/v1/shipping-thresholds/{threshold_id}"
        [ ( "threshold_id", identity thresholdId_path ) ]
        []
        []
        (Maybe.map Http.jsonBody (Just (Api.Data.encodeShippingThresholdUpdate shippingThresholdUpdate_body)))
        Api.Data.shippingThresholdDecoder
        |> Api.withBearerToken auth_token
