{-
   SimpleBilly API
   Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

   The version of the OpenAPI document: 0.1.0
   Contact: support@simplebilly.com

   NOTE: This file is auto generated by the openapi-generator.
   https://github.com/openapitools/openapi-generator.git

   DO NOT EDIT THIS FILE MANUALLY.

   For more info on generating Elm code, see https://eriktim.github.io/openapi-elm/
-}


module Api.Request.Shipping exposing
    ( getCredentialsApi
    , getRatesApi
    , listProvidersApi
    , saveCredentialsApi
    )

import Api
import Api.Data exposing (..)
import Dict
import Http
import Json.Decode
import Json.Encode


getCredentialsApi : String -> Api.Request Api.Data.ShippingCredentials
getCredentialsApi auth_token =
    Api.request
        "GET"
        "/api/v1/shipping/credentials"
        []
        []
        []
        Nothing
        Api.Data.shippingCredentialsDecoder
        |> Api.withBearerToken auth_token

getRatesApi : Api.Data.RateRequest -> String -> Api.Request Api.Data.RateResponse
getRatesApi rateRequest_body auth_token =
    Api.request
        "POST"
        "/api/v1/shipping/rates"
        []
        []
        []
        (Maybe.map Http.jsonBody (Just (Api.Data.encodeRateRequest rateRequest_body)))
        Api.Data.rateResponseDecoder
        |> Api.withBearerToken auth_token

listProvidersApi : String -> Api.Request (List Api.Data.ProviderInfo)
listProvidersApi auth_token =
    Api.request
        "GET"
        "/api/v1/shipping/providers"
        []
        []
        []
        Nothing
        (Json.Decode.list Api.Data.providerInfoDecoder)
        |> Api.withBearerToken auth_token

saveCredentialsApi : Api.Data.ShippingCredentials -> String -> Api.Request Api.Data.ShippingCredentials
saveCredentialsApi shippingCredentials_body auth_token =
    Api.request
        "PUT"
        "/api/v1/shipping/credentials"
        []
        []
        []
        (Maybe.map Http.jsonBody (Just (Api.Data.encodeShippingCredentials shippingCredentials_body)))
        Api.Data.shippingCredentialsDecoder
        |> Api.withBearerToken auth_token
