{-
   SimpleBilly API
   Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

   The version of the OpenAPI document: 0.1.0
   Contact: support@simplebilly.com

   NOTE: This file is auto generated by the openapi-generator.
   https://github.com/openapitools/openapi-generator.git

   DO NOT EDIT THIS FILE MANUALLY.

   For more info on generating Elm code, see https://eriktim.github.io/openapi-elm/
-}


module Api.Request.ShippingRule exposing
    ( createShippingRule
    , deleteShippingRule
    , getShippingRule
    , listShippingRules
    , updateShippingRule
    )

import Api
import Api.Data exposing (..)
import Dict
import Http
import Json.Decode
import Json.Encode


createShippingRule : Api.Data.ShippingRuleCreate -> String -> Api.Request Api.Data.ShippingRule
createShippingRule shippingRuleCreate_body auth_token =
    Api.request
        "POST"
        "/api/v1/shipping-rules"
        []
        []
        []
        (Maybe.map Http.jsonBody (Just (Api.Data.encodeShippingRuleCreate shippingRuleCreate_body)))
        Api.Data.shippingRuleDecoder
        |> Api.withBearerToken auth_token

deleteShippingRule : String -> String -> Api.Request ()
deleteShippingRule ruleId_path auth_token =
    Api.request
        "DELETE"
        "/api/v1/shipping-rules/{rule_id}"
        [ ( "rule_id", identity ruleId_path ) ]
        []
        []
        Nothing
        (Json.Decode.succeed ())
        |> Api.withBearerToken auth_token

getShippingRule : String -> String -> Api.Request Api.Data.ShippingRule
getShippingRule ruleId_path auth_token =
    Api.request
        "GET"
        "/api/v1/shipping-rules/{rule_id}"
        [ ( "rule_id", identity ruleId_path ) ]
        []
        []
        Nothing
        Api.Data.shippingRuleDecoder
        |> Api.withBearerToken auth_token

listShippingRules : Maybe Int -> Maybe Int -> Maybe String -> String -> Api.Request (List Api.Data.ShippingRule)
listShippingRules page_query pageSize_query country_query auth_token =
    Api.request
        "GET"
        "/api/v1/shipping-rules/"
        []
        [ ( "page", Maybe.map String.fromInt page_query ), ( "page_size", Maybe.map String.fromInt pageSize_query ), ( "country", Maybe.map identity country_query ) ]
        []
        Nothing
        (Json.Decode.list Api.Data.shippingRuleDecoder)
        |> Api.withBearerToken auth_token

updateShippingRule : String -> Api.Data.ShippingRuleUpdate -> String -> Api.Request Api.Data.ShippingRule
updateShippingRule ruleId_path shippingRuleUpdate_body auth_token =
    Api.request
        "PUT"
        "/api/v1/shipping-rules/{rule_id}"
        [ ( "rule_id", identity ruleId_path ) ]
        []
        []
        (Maybe.map Http.jsonBody (Just (Api.Data.encodeShippingRuleUpdate shippingRuleUpdate_body)))
        Api.Data.shippingRuleDecoder
        |> Api.withBearerToken auth_token
