{-
   SimpleBilly API
   Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

   The version of the OpenAPI document: 0.1.0
   Contact: support@simplebilly.com

   NOTE: This file is auto generated by the openapi-generator.
   https://github.com/openapitools/openapi-generator.git

   DO NOT EDIT THIS FILE MANUALLY.

   For more info on generating Elm code, see https://eriktim.github.io/openapi-elm/
-}


module Api.Request.SilentPartner exposing
    ( createSilentPartner
    , deleteSilentPartner
    , getSilentPartner
    , getSilentPartners
    , updateSilentPartner
    )

import Api
import Api.Data exposing (..)
import Dict
import Http
import Json.Decode
import Json.Encode
import Uuid exposing (Uuid)


createSilentPartner : Api.Data.SilentPartnerCreate -> String -> Api.Request Api.Data.SilentPartner
createSilentPartner silentPartnerCreate_body auth_token =
    Api.request
        "POST"
        "/api/v1/silent-partners"
        []
        []
        []
        (Maybe.map Http.jsonBody (Just (Api.Data.encodeSilentPartnerCreate silentPartnerCreate_body)))
        Api.Data.silentPartnerDecoder
        |> Api.withBearerToken auth_token

deleteSilentPartner : Uuid -> String -> Api.Request ()
deleteSilentPartner id_path auth_token =
    Api.request
        "DELETE"
        "/api/v1/silent-partners/{id}"
        [ ( "id", Uuid.toString id_path ) ]
        []
        []
        Nothing
        (Json.Decode.succeed ())
        |> Api.withBearerToken auth_token

getSilentPartner : Uuid -> String -> Api.Request Api.Data.SilentPartner
getSilentPartner id_path auth_token =
    Api.request
        "GET"
        "/api/v1/silent-partners/{id}"
        [ ( "id", Uuid.toString id_path ) ]
        []
        []
        Nothing
        Api.Data.silentPartnerDecoder
        |> Api.withBearerToken auth_token

getSilentPartners : Maybe Int -> Maybe Int -> Maybe String -> Maybe Bool -> String -> Api.Request (List Api.Data.SilentPartner)
getSilentPartners page_query pageSize_query search_query includeDeleted_query auth_token =
    Api.request
        "GET"
        "/api/v1/silent-partners/"
        []
        [ ( "page", Maybe.map String.fromInt page_query ), ( "page_size", Maybe.map String.fromInt pageSize_query ), ( "search", Maybe.map identity search_query ), ( "include_deleted", Maybe.map (\val -> if val then "true" else "false") includeDeleted_query ) ]
        []
        Nothing
        (Json.Decode.list Api.Data.silentPartnerDecoder)
        |> Api.withBearerToken auth_token

updateSilentPartner : Uuid -> Api.Data.SilentPartnerUpdate -> String -> Api.Request Api.Data.SilentPartner
updateSilentPartner id_path silentPartnerUpdate_body auth_token =
    Api.request
        "PUT"
        "/api/v1/silent-partners/{id}"
        [ ( "id", Uuid.toString id_path ) ]
        []
        []
        (Maybe.map Http.jsonBody (Just (Api.Data.encodeSilentPartnerUpdate silentPartnerUpdate_body)))
        Api.Data.silentPartnerDecoder
        |> Api.withBearerToken auth_token
