{-
   SimpleBilly API
   Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

   The version of the OpenAPI document: 0.1.0
   Contact: support@simplebilly.com

   NOTE: This file is auto generated by the openapi-generator.
   https://github.com/openapitools/openapi-generator.git

   DO NOT EDIT THIS FILE MANUALLY.

   For more info on generating Elm code, see https://eriktim.github.io/openapi-elm/
-}


module Api.Request.StockTransfer exposing
    ( createStockTransfer
    , deleteStockTransfer
    , getStockTransfer
    , listStockTransfers
    , updateStockTransferStatus
    )

import Api
import Api.Data exposing (..)
import Dict
import Http
import Json.Decode
import Json.Encode


createStockTransfer : Api.Data.StockTransfer -> String -> Api.Request Api.Data.StockTransfer
createStockTransfer stockTransfer_body auth_token =
    Api.request
        "POST"
        "/api/v1/stock-transfers"
        []
        []
        []
        (Maybe.map Http.jsonBody (Just (Api.Data.encodeStockTransfer stockTransfer_body)))
        Api.Data.stockTransferDecoder
        |> Api.withBearerToken auth_token

deleteStockTransfer : String -> String -> Api.Request ()
deleteStockTransfer stockTransferId_path auth_token =
    Api.request
        "DELETE"
        "/api/v1/stock-transfers/{stock_transfer_id}"
        [ ( "stock_transfer_id", identity stockTransferId_path ) ]
        []
        []
        Nothing
        (Json.Decode.succeed ())
        |> Api.withBearerToken auth_token

getStockTransfer : String -> String -> Api.Request Api.Data.StockTransfer
getStockTransfer stockTransferId_path auth_token =
    Api.request
        "GET"
        "/api/v1/stock-transfers/{stock_transfer_id}"
        [ ( "stock_transfer_id", identity stockTransferId_path ) ]
        []
        []
        Nothing
        Api.Data.stockTransferDecoder
        |> Api.withBearerToken auth_token

listStockTransfers : Maybe Int -> Maybe Int -> Maybe String -> Maybe String -> String -> Api.Request (List Api.Data.StockTransfer)
listStockTransfers page_query pageSize_query status_query warehouseId_query auth_token =
    Api.request
        "GET"
        "/api/v1/stock-transfers/"
        []
        [ ( "page", Maybe.map String.fromInt page_query ), ( "page_size", Maybe.map String.fromInt pageSize_query ), ( "status", Maybe.map identity status_query ), ( "warehouse_id", Maybe.map identity warehouseId_query ) ]
        []
        Nothing
        (Json.Decode.list Api.Data.stockTransferDecoder)
        |> Api.withBearerToken auth_token

updateStockTransferStatus : String -> Api.Data.StockTransferStatusUpdate -> String -> Api.Request Api.Data.StockTransfer
updateStockTransferStatus stockTransferId_path stockTransferStatusUpdate_body auth_token =
    Api.request
        "PUT"
        "/api/v1/stock-transfers/{stock_transfer_id}/status"
        [ ( "stock_transfer_id", identity stockTransferId_path ) ]
        []
        []
        (Maybe.map Http.jsonBody (Just (Api.Data.encodeStockTransferStatusUpdate stockTransferStatusUpdate_body)))
        Api.Data.stockTransferDecoder
        |> Api.withBearerToken auth_token
