{-
   SimpleBilly API
   Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

   The version of the OpenAPI document: 0.1.0
   Contact: support@simplebilly.com

   NOTE: This file is auto generated by the openapi-generator.
   https://github.com/openapitools/openapi-generator.git

   DO NOT EDIT THIS FILE MANUALLY.

   For more info on generating Elm code, see https://eriktim.github.io/openapi-elm/
-}


module Api.Request.StockMovement exposing
    ( getStockMovement
    , listStockMovements
    )

import Api
import Api.Data exposing (..)
import Api.Time exposing (Posix)
import Dict
import Http
import Json.Decode
import Json.Encode
import Uuid exposing (Uuid)


getStockMovement : String -> String -> Api.Request Api.Data.StockMovement
getStockMovement movementId_path auth_token =
    Api.request
        "GET"
        "/api/v1/stock-movements/{movement_id}"
        [ ( "movement_id", identity movementId_path ) ]
        []
        []
        Nothing
        Api.Data.stockMovementDecoder
        |> Api.withBearerToken auth_token

listStockMovements : Maybe Int -> Maybe Int -> Maybe Uuid -> Maybe String -> Maybe String -> Maybe Posix -> Maybe Posix -> String -> Api.Request (List Api.Data.StockMovement)
listStockMovements page_query pageSize_query productId_query warehouseId_query movementType_query from_query to_query auth_token =
    Api.request
        "GET"
        "/api/v1/stock-movements/"
        []
        [ ( "page", Maybe.map String.fromInt page_query ), ( "pageSize", Maybe.map String.fromInt pageSize_query ), ( "productId", Maybe.map Uuid.toString productId_query ), ( "warehouseId", Maybe.map identity warehouseId_query ), ( "movementType", Maybe.map identity movementType_query ), ( "from", Maybe.map Api.Time.dateToString from_query ), ( "to", Maybe.map Api.Time.dateToString to_query ) ]
        []
        Nothing
        (Json.Decode.list Api.Data.stockMovementDecoder)
        |> Api.withBearerToken auth_token
