{-
   SimpleBilly API
   Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

   The version of the OpenAPI document: 0.1.0
   Contact: support@simplebilly.com

   NOTE: This file is auto generated by the openapi-generator.
   https://github.com/openapitools/openapi-generator.git

   DO NOT EDIT THIS FILE MANUALLY.

   For more info on generating Elm code, see https://eriktim.github.io/openapi-elm/
-}


module Api.Request.SupportTicket exposing
    ( createTicketApi
    , deleteTicketApi
    , getTicketApi
    , listTicketsApi
    , updateTicketApi
    )

import Api
import Api.Data exposing (..)
import Dict
import Http
import Json.Decode
import Json.Encode
import Uuid exposing (Uuid)


createTicketApi : Api.Data.CreateTicketRequest -> String -> Api.Request Api.Data.SupportTicket
createTicketApi createTicketRequest_body auth_token =
    Api.request
        "POST"
        "/api/v1/support/tickets"
        []
        []
        []
        (Maybe.map Http.jsonBody (Just (Api.Data.encodeCreateTicketRequest createTicketRequest_body)))
        Api.Data.supportTicketDecoder
        |> Api.withBearerToken auth_token

deleteTicketApi : Uuid -> String -> Api.Request ()
deleteTicketApi ticketId_path auth_token =
    Api.request
        "DELETE"
        "/api/v1/support/tickets/{ticket_id}"
        [ ( "ticket_id", Uuid.toString ticketId_path ) ]
        []
        []
        Nothing
        (Json.Decode.succeed ())
        |> Api.withBearerToken auth_token

getTicketApi : Uuid -> String -> Api.Request Api.Data.SupportTicket
getTicketApi ticketId_path auth_token =
    Api.request
        "GET"
        "/api/v1/support/tickets/{ticket_id}"
        [ ( "ticket_id", Uuid.toString ticketId_path ) ]
        []
        []
        Nothing
        Api.Data.supportTicketDecoder
        |> Api.withBearerToken auth_token

listTicketsApi : Maybe String -> Maybe String -> Maybe Uuid -> Maybe String -> Maybe String -> Maybe String -> Maybe Int -> Maybe Int -> String -> Api.Request (List Api.Data.SupportTicket)
listTicketsApi status_query priority_query assignedTo_query channelType_query customerId_query search_query page_query pageSize_query auth_token =
    Api.request
        "GET"
        "/api/v1/support/tickets"
        []
        [ ( "status", Maybe.map identity status_query ), ( "priority", Maybe.map identity priority_query ), ( "assigned_to", Maybe.map Uuid.toString assignedTo_query ), ( "channel_type", Maybe.map identity channelType_query ), ( "customer_id", Maybe.map identity customerId_query ), ( "search", Maybe.map identity search_query ), ( "page", Maybe.map String.fromInt page_query ), ( "page_size", Maybe.map String.fromInt pageSize_query ) ]
        []
        Nothing
        (Json.Decode.list Api.Data.supportTicketDecoder)
        |> Api.withBearerToken auth_token

updateTicketApi : Uuid -> Api.Data.SupportTicketUpdate -> String -> Api.Request Api.Data.SupportTicket
updateTicketApi ticketId_path supportTicketUpdate_body auth_token =
    Api.request
        "PUT"
        "/api/v1/support/tickets/{ticket_id}"
        [ ( "ticket_id", Uuid.toString ticketId_path ) ]
        []
        []
        (Maybe.map Http.jsonBody (Just (Api.Data.encodeSupportTicketUpdate supportTicketUpdate_body)))
        Api.Data.supportTicketDecoder
        |> Api.withBearerToken auth_token
