{-
   SimpleBilly API
   Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

   The version of the OpenAPI document: 0.1.0
   Contact: support@simplebilly.com

   NOTE: This file is auto generated by the openapi-generator.
   https://github.com/openapitools/openapi-generator.git

   DO NOT EDIT THIS FILE MANUALLY.

   For more info on generating Elm code, see https://eriktim.github.io/openapi-elm/
-}


module Api.Request.SupportChannel exposing
    ( createChannelApi
    , deleteChannelApi
    , listChannelsApi
    , updateChannelApi
    )

import Api
import Api.Data exposing (..)
import Dict
import Http
import Json.Decode
import Json.Encode
import Uuid exposing (Uuid)


createChannelApi : Api.Data.CreateChannelDto -> String -> Api.Request Api.Data.SupportChannel
createChannelApi createChannelDto_body auth_token =
    Api.request
        "POST"
        "/api/v1/support/channels"
        []
        []
        []
        (Maybe.map Http.jsonBody (Just (Api.Data.encodeCreateChannelDto createChannelDto_body)))
        Api.Data.supportChannelDecoder
        |> Api.withBearerToken auth_token

deleteChannelApi : Uuid -> String -> Api.Request ()
deleteChannelApi channelId_path auth_token =
    Api.request
        "DELETE"
        "/api/v1/support/channels/{channel_id}"
        [ ( "channel_id", Uuid.toString channelId_path ) ]
        []
        []
        Nothing
        (Json.Decode.succeed ())
        |> Api.withBearerToken auth_token

listChannelsApi : String -> Api.Request (List Api.Data.SupportChannel)
listChannelsApi auth_token =
    Api.request
        "GET"
        "/api/v1/support/channels"
        []
        []
        []
        Nothing
        (Json.Decode.list Api.Data.supportChannelDecoder)
        |> Api.withBearerToken auth_token

updateChannelApi : Uuid -> Api.Data.UpdateChannelDto -> String -> Api.Request Api.Data.SupportChannel
updateChannelApi channelId_path updateChannelDto_body auth_token =
    Api.request
        "PUT"
        "/api/v1/support/channels/{channel_id}"
        [ ( "channel_id", Uuid.toString channelId_path ) ]
        []
        []
        (Maybe.map Http.jsonBody (Just (Api.Data.encodeUpdateChannelDto updateChannelDto_body)))
        Api.Data.supportChannelDecoder
        |> Api.withBearerToken auth_token
