{-
   SimpleBilly API
   Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

   The version of the OpenAPI document: 0.1.0
   Contact: support@simplebilly.com

   NOTE: This file is auto generated by the openapi-generator.
   https://github.com/openapitools/openapi-generator.git

   DO NOT EDIT THIS FILE MANUALLY.

   For more info on generating Elm code, see https://eriktim.github.io/openapi-elm/
-}


module Api.Request.SupplierInvoice exposing
    ( createSupplierInvoice
    , deleteSupplierInvoice
    , getSupplierInvoice
    , listSupplierInvoices
    , updateSupplierInvoice
    , updateSupplierInvoiceStatus
    )

import Api
import Api.Data exposing (..)
import Dict
import Http
import Json.Decode
import Json.Encode


createSupplierInvoice : Api.Data.SupplierInvoice -> String -> Api.Request Api.Data.SupplierInvoice
createSupplierInvoice supplierInvoice_body auth_token =
    Api.request
        "POST"
        "/api/v1/supplier-invoices"
        []
        []
        []
        (Maybe.map Http.jsonBody (Just (Api.Data.encodeSupplierInvoice supplierInvoice_body)))
        Api.Data.supplierInvoiceDecoder
        |> Api.withBearerToken auth_token

deleteSupplierInvoice : String -> String -> Api.Request ()
deleteSupplierInvoice supplierInvoiceId_path auth_token =
    Api.request
        "DELETE"
        "/api/v1/supplier-invoices/{supplier_invoice_id}"
        [ ( "supplier_invoice_id", identity supplierInvoiceId_path ) ]
        []
        []
        Nothing
        (Json.Decode.succeed ())
        |> Api.withBearerToken auth_token

getSupplierInvoice : String -> String -> Api.Request Api.Data.SupplierInvoice
getSupplierInvoice supplierInvoiceId_path auth_token =
    Api.request
        "GET"
        "/api/v1/supplier-invoices/{supplier_invoice_id}"
        [ ( "supplier_invoice_id", identity supplierInvoiceId_path ) ]
        []
        []
        Nothing
        Api.Data.supplierInvoiceDecoder
        |> Api.withBearerToken auth_token

listSupplierInvoices : Maybe Int -> Maybe Int -> Maybe String -> Maybe String -> Maybe String -> String -> Api.Request (List Api.Data.SupplierInvoice)
listSupplierInvoices page_query pageSize_query status_query purchaseOrderId_query supplierName_query auth_token =
    Api.request
        "GET"
        "/api/v1/supplier-invoices/"
        []
        [ ( "page", Maybe.map String.fromInt page_query ), ( "page_size", Maybe.map String.fromInt pageSize_query ), ( "status", Maybe.map identity status_query ), ( "purchase_order_id", Maybe.map identity purchaseOrderId_query ), ( "supplier_name", Maybe.map identity supplierName_query ) ]
        []
        Nothing
        (Json.Decode.list Api.Data.supplierInvoiceDecoder)
        |> Api.withBearerToken auth_token

updateSupplierInvoice : String -> Api.Data.AnyType -> String -> Api.Request Api.Data.SupplierInvoice
updateSupplierInvoice supplierInvoiceId_path body_body auth_token =
    Api.request
        "PUT"
        "/api/v1/supplier-invoices/{supplier_invoice_id}"
        [ ( "supplier_invoice_id", identity supplierInvoiceId_path ) ]
        []
        []
        (Maybe.map Http.jsonBody (Just (encodeAnyType body_body)))
        Api.Data.supplierInvoiceDecoder
        |> Api.withBearerToken auth_token

updateSupplierInvoiceStatus : String -> Api.Data.SupplierInvoiceStatusUpdate -> String -> Api.Request Api.Data.SupplierInvoice
updateSupplierInvoiceStatus supplierInvoiceId_path supplierInvoiceStatusUpdate_body auth_token =
    Api.request
        "PUT"
        "/api/v1/supplier-invoices/{supplier_invoice_id}/status"
        [ ( "supplier_invoice_id", identity supplierInvoiceId_path ) ]
        []
        []
        (Maybe.map Http.jsonBody (Just (Api.Data.encodeSupplierInvoiceStatusUpdate supplierInvoiceStatusUpdate_body)))
        Api.Data.supplierInvoiceDecoder
        |> Api.withBearerToken auth_token
