{-
   SimpleBilly API
   Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

   The version of the OpenAPI document: 0.1.0
   Contact: support@simplebilly.com

   NOTE: This file is auto generated by the openapi-generator.
   https://github.com/openapitools/openapi-generator.git

   DO NOT EDIT THIS FILE MANUALLY.

   For more info on generating Elm code, see https://eriktim.github.io/openapi-elm/
-}


module Api.Request.SupplierCondition exposing
    ( createSupplierCondition
    , deleteSupplierCondition
    , getSupplierCondition
    , listSupplierConditions
    , updateSupplierCondition
    )

import Api
import Api.Data exposing (..)
import Dict
import Http
import Json.Decode
import Json.Encode


createSupplierCondition : Api.Data.SupplierConditionCreate -> String -> Api.Request Api.Data.SupplierCondition
createSupplierCondition supplierConditionCreate_body auth_token =
    Api.request
        "POST"
        "/api/v1/supplier-conditions"
        []
        []
        []
        (Maybe.map Http.jsonBody (Just (Api.Data.encodeSupplierConditionCreate supplierConditionCreate_body)))
        Api.Data.supplierConditionDecoder
        |> Api.withBearerToken auth_token

deleteSupplierCondition : String -> String -> Api.Request ()
deleteSupplierCondition supplierConditionId_path auth_token =
    Api.request
        "DELETE"
        "/api/v1/supplier-conditions/{supplier_condition_id}"
        [ ( "supplier_condition_id", identity supplierConditionId_path ) ]
        []
        []
        Nothing
        (Json.Decode.succeed ())
        |> Api.withBearerToken auth_token

getSupplierCondition : String -> String -> Api.Request Api.Data.SupplierCondition
getSupplierCondition supplierConditionId_path auth_token =
    Api.request
        "GET"
        "/api/v1/supplier-conditions/{supplier_condition_id}"
        [ ( "supplier_condition_id", identity supplierConditionId_path ) ]
        []
        []
        Nothing
        Api.Data.supplierConditionDecoder
        |> Api.withBearerToken auth_token

listSupplierConditions : Maybe Int -> Maybe Int -> Maybe String -> Maybe String -> String -> Api.Request (List Api.Data.SupplierCondition)
listSupplierConditions page_query pageSize_query supplierContactId_query search_query auth_token =
    Api.request
        "GET"
        "/api/v1/supplier-conditions/"
        []
        [ ( "page", Maybe.map String.fromInt page_query ), ( "page_size", Maybe.map String.fromInt pageSize_query ), ( "supplier_contact_id", Maybe.map identity supplierContactId_query ), ( "search", Maybe.map identity search_query ) ]
        []
        Nothing
        (Json.Decode.list Api.Data.supplierConditionDecoder)
        |> Api.withBearerToken auth_token

updateSupplierCondition : String -> Api.Data.SupplierConditionUpdate -> String -> Api.Request Api.Data.SupplierCondition
updateSupplierCondition supplierConditionId_path supplierConditionUpdate_body auth_token =
    Api.request
        "PUT"
        "/api/v1/supplier-conditions/{supplier_condition_id}"
        [ ( "supplier_condition_id", identity supplierConditionId_path ) ]
        []
        []
        (Maybe.map Http.jsonBody (Just (Api.Data.encodeSupplierConditionUpdate supplierConditionUpdate_body)))
        Api.Data.supplierConditionDecoder
        |> Api.withBearerToken auth_token
