{-
   SimpleBilly API
   Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

   The version of the OpenAPI document: 0.1.0
   Contact: support@simplebilly.com

   NOTE: This file is auto generated by the openapi-generator.
   https://github.com/openapitools/openapi-generator.git

   DO NOT EDIT THIS FILE MANUALLY.

   For more info on generating Elm code, see https://eriktim.github.io/openapi-elm/
-}


module Api.Request.Tax exposing
    ( createTaxRate
    , deleteTaxRate
    , listTaxRates
    , updateTaxRate
    )

import Api
import Api.Data exposing (..)
import Dict
import Http
import Json.Decode
import Json.Encode
import Uuid exposing (Uuid)


{-| Create a tax rate (`admin:settings`).
-}
createTaxRate : Api.Data.TaxRateCreate -> String -> Api.Request ()
createTaxRate taxRateCreate_body auth_token =
    Api.request
        "POST"
        "/api/v1/tax-rates"
        []
        []
        []
        (Maybe.map Http.jsonBody (Just (Api.Data.encodeTaxRateCreate taxRateCreate_body)))
        (Json.Decode.succeed ())
        |> Api.withBearerToken auth_token

{-| Delete a tax rate by id (`admin:settings`).
-}
deleteTaxRate : Uuid -> String -> Api.Request ()
deleteTaxRate id_path auth_token =
    Api.request
        "DELETE"
        "/api/v1/tax-rates/{id}"
        [ ( "id", Uuid.toString id_path ) ]
        []
        []
        Nothing
        (Json.Decode.succeed ())
        |> Api.withBearerToken auth_token

{-| List the calling tenant's tax rates.
-}
listTaxRates : String -> Api.Request ()
listTaxRates auth_token =
    Api.request
        "GET"
        "/api/v1/tax-rates"
        []
        []
        []
        Nothing
        (Json.Decode.succeed ())
        |> Api.withBearerToken auth_token

{-| Update a tax rate by id (`admin:settings`). Replaces all body fields.
-}
updateTaxRate : Uuid -> Api.Data.TaxRateCreate -> String -> Api.Request ()
updateTaxRate id_path taxRateCreate_body auth_token =
    Api.request
        "PUT"
        "/api/v1/tax-rates/{id}"
        [ ( "id", Uuid.toString id_path ) ]
        []
        []
        (Maybe.map Http.jsonBody (Just (Api.Data.encodeTaxRateCreate taxRateCreate_body)))
        (Json.Decode.succeed ())
        |> Api.withBearerToken auth_token
