{-
   SimpleBilly API
   Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

   The version of the OpenAPI document: 0.1.0
   Contact: support@simplebilly.com

   NOTE: This file is auto generated by the openapi-generator.
   https://github.com/openapitools/openapi-generator.git

   DO NOT EDIT THIS FILE MANUALLY.

   For more info on generating Elm code, see https://eriktim.github.io/openapi-elm/
-}


module Api.Request.TenantSettings exposing
    ( getTenantSettings
    , updateTenantSettings
    )

import Api
import Api.Data exposing (..)
import Dict
import Http
import Json.Decode
import Json.Encode


getTenantSettings : String -> Api.Request Api.Data.TenantSettings
getTenantSettings auth_token =
    Api.request
        "GET"
        "/api/v1/settings/tenant"
        []
        []
        []
        Nothing
        Api.Data.tenantSettingsDecoder
        |> Api.withBearerToken auth_token

updateTenantSettings : Api.Data.UpdateTenantSettings -> String -> Api.Request Api.Data.TenantSettings
updateTenantSettings updateTenantSettings_body auth_token =
    Api.request
        "PUT"
        "/api/v1/settings/tenant"
        []
        []
        []
        (Maybe.map Http.jsonBody (Just (Api.Data.encodeUpdateTenantSettings updateTenantSettings_body)))
        Api.Data.tenantSettingsDecoder
        |> Api.withBearerToken auth_token
