{-
   SimpleBilly API
   Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

   The version of the OpenAPI document: 0.1.0
   Contact: support@simplebilly.com

   NOTE: This file is auto generated by the openapi-generator.
   https://github.com/openapitools/openapi-generator.git

   DO NOT EDIT THIS FILE MANUALLY.

   For more info on generating Elm code, see https://eriktim.github.io/openapi-elm/
-}


module Api.Request.TicketMessage exposing
    ( listMessagesApi
    , sendMessageApi
    )

import Api
import Api.Data exposing (..)
import Dict
import Http
import Json.Decode
import Json.Encode
import Uuid exposing (Uuid)


listMessagesApi : Uuid -> String -> Api.Request (List Api.Data.TicketMessage)
listMessagesApi ticketId_path auth_token =
    Api.request
        "GET"
        "/api/v1/support/tickets/{ticket_id}/messages"
        [ ( "ticket_id", Uuid.toString ticketId_path ) ]
        []
        []
        Nothing
        (Json.Decode.list Api.Data.ticketMessageDecoder)
        |> Api.withBearerToken auth_token

sendMessageApi : Uuid -> Api.Data.SendMessageDto -> String -> Api.Request Api.Data.TicketMessage
sendMessageApi ticketId_path sendMessageDto_body auth_token =
    Api.request
        "POST"
        "/api/v1/support/tickets/{ticket_id}/messages"
        [ ( "ticket_id", Uuid.toString ticketId_path ) ]
        []
        []
        (Maybe.map Http.jsonBody (Just (Api.Data.encodeSendMessageDto sendMessageDto_body)))
        Api.Data.ticketMessageDecoder
        |> Api.withBearerToken auth_token
