{-
   SimpleBilly API
   Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

   The version of the OpenAPI document: 0.1.0
   Contact: support@simplebilly.com

   NOTE: This file is auto generated by the openapi-generator.
   https://github.com/openapitools/openapi-generator.git

   DO NOT EDIT THIS FILE MANUALLY.

   For more info on generating Elm code, see https://eriktim.github.io/openapi-elm/
-}


module Api.Request.TimeEntries exposing
    ( clockInTimeEntry
    , clockOutTimeEntry
    , getLaborCosts
    , listTimeEntries
    )

import Api
import Api.Data exposing (..)
import Api.Time exposing (Posix)
import Dict
import Http
import Json.Decode
import Json.Encode
import Uuid exposing (Uuid)


{-| Clock in for the authenticated user (resolved via their employee profile).
-}
clockInTimeEntry : Api.Data.TimeEntryClockIn -> String -> Api.Request Api.Data.TimeEntryDto
clockInTimeEntry timeEntryClockIn_body auth_token =
    Api.request
        "POST"
        "/api/v1/time-entries"
        []
        []
        []
        (Maybe.map Http.jsonBody (Just (Api.Data.encodeTimeEntryClockIn timeEntryClockIn_body)))
        Api.Data.timeEntryDtoDecoder
        |> Api.withBearerToken auth_token

{-| Clock out an entry: the entry's owner, or anyone with `time_entries:write`.
-}
clockOutTimeEntry : Uuid -> Api.Data.TimeEntryClockOut -> String -> Api.Request Api.Data.TimeEntryDto
clockOutTimeEntry id_path timeEntryClockOut_body auth_token =
    Api.request
        "PATCH"
        "/api/v1/time-entries/{id}"
        [ ( "id", Uuid.toString id_path ) ]
        []
        []
        (Maybe.map Http.jsonBody (Just (Api.Data.encodeTimeEntryClockOut timeEntryClockOut_body)))
        Api.Data.timeEntryDtoDecoder
        |> Api.withBearerToken auth_token

{-| Labor-cost report: worked hours aggregated per employee / order / day, valued at the employee's hourly cost rate.
-}
getLaborCosts : Posix -> Posix -> String -> String -> Api.Request (List Api.Data.LaborCostRow)
getLaborCosts from_query to_query groupBy_query auth_token =
    Api.request
        "GET"
        "/api/v1/labor-costs"
        []
        [ ( "from", Just <| Api.Time.dateToString from_query ), ( "to", Just <| Api.Time.dateToString to_query ), ( "group_by", Just <| identity groupBy_query ) ]
        []
        Nothing
        (Json.Decode.list Api.Data.laborCostRowDecoder)
        |> Api.withBearerToken auth_token

{-| List time entries with optional date-range / active / employee filters.
-}
listTimeEntries : Maybe Posix -> Maybe Posix -> Maybe Bool -> Maybe Uuid -> String -> Api.Request (List Api.Data.TimeEntryDto)
listTimeEntries from_query to_query active_query employeeId_query auth_token =
    Api.request
        "GET"
        "/api/v1/time-entries"
        []
        [ ( "from", Maybe.map Api.Time.dateToString from_query ), ( "to", Maybe.map Api.Time.dateToString to_query ), ( "active", Maybe.map (\val -> if val then "true" else "false") active_query ), ( "employee_id", Maybe.map Uuid.toString employeeId_query ) ]
        []
        Nothing
        (Json.Decode.list Api.Data.timeEntryDtoDecoder)
        |> Api.withBearerToken auth_token
