{-
   SimpleBilly API
   Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

   The version of the OpenAPI document: 0.1.0
   Contact: support@simplebilly.com

   NOTE: This file is auto generated by the openapi-generator.
   https://github.com/openapitools/openapi-generator.git

   DO NOT EDIT THIS FILE MANUALLY.

   For more info on generating Elm code, see https://eriktim.github.io/openapi-elm/
-}


module Api.Request.Trainings exposing
    ( getMyTrainings
    , getTrainingContent
    , getTrainingOverview
    , submitTrainingResult
    )

import Api
import Api.Data exposing (..)
import Dict
import Http
import Json.Decode
import Json.Encode


getMyTrainings : String -> Api.Request (List Api.Data.MyTrainingItem)
getMyTrainings auth_token =
    Api.request
        "GET"
        "/api/v1/trainings/me"
        []
        []
        []
        Nothing
        (Json.Decode.list Api.Data.myTrainingItemDecoder)
        |> Api.withBearerToken auth_token

getTrainingContent : String -> String -> Api.Request Api.Data.TrainingContent
getTrainingContent code_path auth_token =
    Api.request
        "GET"
        "/api/v1/trainings/content/{code}"
        [ ( "code", identity code_path ) ]
        []
        []
        Nothing
        Api.Data.trainingContentDecoder
        |> Api.withBearerToken auth_token

getTrainingOverview : String -> Api.Request (List Api.Data.HrTrainingOverview)
getTrainingOverview auth_token =
    Api.request
        "GET"
        "/api/v1/trainings/overview"
        []
        []
        []
        Nothing
        (Json.Decode.list Api.Data.hrTrainingOverviewDecoder)
        |> Api.withBearerToken auth_token

submitTrainingResult : Api.Data.SubmitResultDto -> String -> Api.Request Api.Data.SubmitResultResponse
submitTrainingResult submitResultDto_body auth_token =
    Api.request
        "POST"
        "/api/v1/trainings/submit-result"
        []
        []
        []
        (Maybe.map Http.jsonBody (Just (Api.Data.encodeSubmitResultDto submitResultDto_body)))
        Api.Data.submitResultResponseDecoder
        |> Api.withBearerToken auth_token
