{-
   SimpleBilly API
   Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

   The version of the OpenAPI document: 0.1.0
   Contact: support@simplebilly.com

   NOTE: This file is auto generated by the openapi-generator.
   https://github.com/openapitools/openapi-generator.git

   DO NOT EDIT THIS FILE MANUALLY.

   For more info on generating Elm code, see https://eriktim.github.io/openapi-elm/
-}


module Api.Request.User exposing
    ( changePassword
    , createTeam
    , generateApiKey
    , inviteUser
    , listTeams
    , removeUserFromOrg
    , updateProfile
    , userProfile
    , userTenants
    )

import Api
import Api.Data exposing (..)
import Dict
import Http
import Json.Decode
import Json.Encode


{-| Change the current user's password (requires the current password).
-}
changePassword : Api.Data.ChangePasswordRequest -> String -> Api.Request ()
changePassword changePasswordRequest_body auth_token =
    Api.request
        "POST"
        "/user/change-password"
        []
        []
        []
        (Maybe.map Http.jsonBody (Just (Api.Data.encodeChangePasswordRequest changePasswordRequest_body)))
        (Json.Decode.succeed ())
        |> Api.withBearerToken auth_token

{-| Create a new team within the current tenant
-}
createTeam : Api.Data.TeamCreate -> String -> Api.Request Api.Data.ApiResponseTeam
createTeam teamCreate_body auth_token =
    Api.request
        "POST"
        "/user/teams"
        []
        []
        []
        (Maybe.map Http.jsonBody (Just (Api.Data.encodeTeamCreate teamCreate_body)))
        Api.Data.apiResponseTeamDecoder
        |> Api.withBearerToken auth_token

{-| Generate a new API key for the current user
-}
generateApiKey : String -> Api.Request Api.Data.ApiResponseString
generateApiKey auth_token =
    Api.request
        "POST"
        "/user/api-key"
        []
        []
        []
        Nothing
        Api.Data.apiResponseStringDecoder
        |> Api.withBearerToken auth_token

{-| Invite a user to the current tenant/organization
-}
inviteUser : Api.Data.InviteRequest -> String -> Api.Request ()
inviteUser inviteRequest_body auth_token =
    Api.request
        "POST"
        "/user/invite"
        []
        []
        []
        (Maybe.map Http.jsonBody (Just (Api.Data.encodeInviteRequest inviteRequest_body)))
        (Json.Decode.succeed ())
        |> Api.withBearerToken auth_token

{-| List all teams in the current tenant
-}
listTeams : String -> Api.Request Api.Data.ApiResponseVecTeam
listTeams auth_token =
    Api.request
        "GET"
        "/user/teams"
        []
        []
        []
        Nothing
        Api.Data.apiResponseVecTeamDecoder
        |> Api.withBearerToken auth_token

{-| Remove a user from the current organization
-}
removeUserFromOrg : Api.Data.RemoveUserRequest -> String -> Api.Request ()
removeUserFromOrg removeUserRequest_body auth_token =
    Api.request
        "DELETE"
        "/user/remove"
        []
        []
        []
        (Maybe.map Http.jsonBody (Just (Api.Data.encodeRemoveUserRequest removeUserRequest_body)))
        (Json.Decode.succeed ())
        |> Api.withBearerToken auth_token

{-| Update the current user's profile
-}
updateProfile : Api.Data.UpdateProfileRequest -> String -> Api.Request ()
updateProfile updateProfileRequest_body auth_token =
    Api.request
        "PUT"
        "/user/profile"
        []
        []
        []
        (Maybe.map Http.jsonBody (Just (Api.Data.encodeUpdateProfileRequest updateProfileRequest_body)))
        (Json.Decode.succeed ())
        |> Api.withBearerToken auth_token

{-| Get the current user's profile
-}
userProfile : String -> Api.Request Api.Data.ApiResponseUserProfile
userProfile auth_token =
    Api.request
        "GET"
        "/user/profile"
        []
        []
        []
        Nothing
        Api.Data.apiResponseUserProfileDecoder
        |> Api.withBearerToken auth_token

{-| List all tenants (organizations) the current user belongs to
-}
userTenants : String -> Api.Request Api.Data.ApiResponseVecUserTenantInfo
userTenants auth_token =
    Api.request
        "GET"
        "/user/tenants"
        []
        []
        []
        Nothing
        Api.Data.apiResponseVecUserTenantInfoDecoder
        |> Api.withBearerToken auth_token
