{-
   SimpleBilly API
   Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

   The version of the OpenAPI document: 0.1.0
   Contact: support@simplebilly.com

   NOTE: This file is auto generated by the openapi-generator.
   https://github.com/openapitools/openapi-generator.git

   DO NOT EDIT THIS FILE MANUALLY.

   For more info on generating Elm code, see https://eriktim.github.io/openapi-elm/
-}


module Api.Request.UserManagement exposing
    ( getUser
    , listUsers
    , removeUser
    , updateUserPermissions
    , updateUserRole
    )

import Api
import Api.Data exposing (..)
import Dict
import Http
import Json.Decode
import Json.Encode
import Uuid exposing (Uuid)


getUser : Uuid -> String -> Api.Request Api.Data.TenantUser
getUser userId_path auth_token =
    Api.request
        "GET"
        "/api/v1/users/{user_id}"
        [ ( "user_id", Uuid.toString userId_path ) ]
        []
        []
        Nothing
        Api.Data.tenantUserDecoder
        |> Api.withBearerToken auth_token

listUsers : String -> Api.Request (List Api.Data.TenantUser)
listUsers auth_token =
    Api.request
        "GET"
        "/api/v1/users"
        []
        []
        []
        Nothing
        (Json.Decode.list Api.Data.tenantUserDecoder)
        |> Api.withBearerToken auth_token

removeUser : Uuid -> String -> Api.Request ()
removeUser userId_path auth_token =
    Api.request
        "DELETE"
        "/api/v1/users/{user_id}"
        [ ( "user_id", Uuid.toString userId_path ) ]
        []
        []
        Nothing
        (Json.Decode.succeed ())
        |> Api.withBearerToken auth_token

updateUserPermissions : Uuid -> Api.Data.UpdatePermissionsPayload -> String -> Api.Request ()
updateUserPermissions userId_path updatePermissionsPayload_body auth_token =
    Api.request
        "PUT"
        "/api/v1/users/{user_id}/permissions"
        [ ( "user_id", Uuid.toString userId_path ) ]
        []
        []
        (Maybe.map Http.jsonBody (Just (Api.Data.encodeUpdatePermissionsPayload updatePermissionsPayload_body)))
        (Json.Decode.succeed ())
        |> Api.withBearerToken auth_token

updateUserRole : Uuid -> Api.Data.UpdateRolePayload -> String -> Api.Request ()
updateUserRole userId_path updateRolePayload_body auth_token =
    Api.request
        "PUT"
        "/api/v1/users/{user_id}/role"
        [ ( "user_id", Uuid.toString userId_path ) ]
        []
        []
        (Maybe.map Http.jsonBody (Just (Api.Data.encodeUpdateRolePayload updateRolePayload_body)))
        (Json.Decode.succeed ())
        |> Api.withBearerToken auth_token
