{-
   SimpleBilly API
   Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

   The version of the OpenAPI document: 0.1.0
   Contact: support@simplebilly.com

   NOTE: This file is auto generated by the openapi-generator.
   https://github.com/openapitools/openapi-generator.git

   DO NOT EDIT THIS FILE MANUALLY.

   For more info on generating Elm code, see https://eriktim.github.io/openapi-elm/
-}


module Api.Request.Voucher exposing
    ( createVoucher
    , deleteVoucher
    , getVoucher
    , listVouchers
    , updateVoucher
    , voucherRestore
    )

import Api
import Api.Data exposing (..)
import Api.Time exposing (Posix)
import Dict
import Http
import Json.Decode
import Json.Encode


createVoucher : Api.Data.VoucherCreate -> String -> Api.Request Api.Data.Voucher
createVoucher voucherCreate_body auth_token =
    Api.request
        "POST"
        "/api/v1/vouchers"
        []
        []
        []
        (Maybe.map Http.jsonBody (Just (Api.Data.encodeVoucherCreate voucherCreate_body)))
        Api.Data.voucherDecoder
        |> Api.withBearerToken auth_token

deleteVoucher : String -> String -> Api.Request ()
deleteVoucher voucherId_path auth_token =
    Api.request
        "DELETE"
        "/api/v1/vouchers/{voucher_id}"
        [ ( "voucher_id", identity voucherId_path ) ]
        []
        []
        Nothing
        (Json.Decode.succeed ())
        |> Api.withBearerToken auth_token

getVoucher : String -> String -> Api.Request Api.Data.Voucher
getVoucher voucherId_path auth_token =
    Api.request
        "GET"
        "/api/v1/vouchers/{voucher_id}"
        [ ( "voucher_id", identity voucherId_path ) ]
        []
        []
        Nothing
        Api.Data.voucherDecoder
        |> Api.withBearerToken auth_token

listVouchers : Maybe Int -> Maybe Int -> Maybe String -> Maybe String -> Maybe String -> Maybe Posix -> Maybe Posix -> String -> Api.Request (List Api.Data.Voucher)
listVouchers page_query pageSize_query voucherType_query voucherStatus_query contactName_query dateFrom_query dateTo_query auth_token =
    Api.request
        "GET"
        "/api/v1/vouchers/"
        []
        [ ( "page", Maybe.map String.fromInt page_query ), ( "page_size", Maybe.map String.fromInt pageSize_query ), ( "voucher_type", Maybe.map identity voucherType_query ), ( "voucher_status", Maybe.map identity voucherStatus_query ), ( "contact_name", Maybe.map identity contactName_query ), ( "date_from", Maybe.map Api.Time.dateToString dateFrom_query ), ( "date_to", Maybe.map Api.Time.dateToString dateTo_query ) ]
        []
        Nothing
        (Json.Decode.list Api.Data.voucherDecoder)
        |> Api.withBearerToken auth_token

updateVoucher : String -> Api.Data.AnyType -> String -> Api.Request Api.Data.Voucher
updateVoucher voucherId_path body_body auth_token =
    Api.request
        "PUT"
        "/api/v1/vouchers/{voucher_id}"
        [ ( "voucher_id", identity voucherId_path ) ]
        []
        []
        (Maybe.map Http.jsonBody (Just (encodeAnyType body_body)))
        Api.Data.voucherDecoder
        |> Api.withBearerToken auth_token

voucherRestore : String -> String -> Api.Request Api.Data.Voucher
voucherRestore voucherId_path auth_token =
    Api.request
        "POST"
        "/api/v1/vouchers/{voucher_id}/restore"
        [ ( "voucher_id", identity voucherId_path ) ]
        []
        []
        Nothing
        Api.Data.voucherDecoder
        |> Api.withBearerToken auth_token
