{-
   SimpleBilly API
   Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

   The version of the OpenAPI document: 0.1.0
   Contact: support@simplebilly.com

   NOTE: This file is auto generated by the openapi-generator.
   https://github.com/openapitools/openapi-generator.git

   DO NOT EDIT THIS FILE MANUALLY.

   For more info on generating Elm code, see https://eriktim.github.io/openapi-elm/
-}


module Api.Request.WarehouseStock exposing
    ( createWarehouseStock
    , deleteWarehouseStock
    , listWarehouseStock
    , updateWarehouseStock
    )

import Api
import Api.Data exposing (..)
import Dict
import Http
import Json.Decode
import Json.Encode
import Uuid exposing (Uuid)


createWarehouseStock : String -> Api.Data.StockAdjustment -> String -> Api.Request Api.Data.WarehouseStock
createWarehouseStock warehouseId_path stockAdjustment_body auth_token =
    Api.request
        "POST"
        "/api/v1/warehouses/{warehouse_id}/stock"
        [ ( "warehouse_id", identity warehouseId_path ) ]
        []
        []
        (Maybe.map Http.jsonBody (Just (Api.Data.encodeStockAdjustment stockAdjustment_body)))
        Api.Data.warehouseStockDecoder
        |> Api.withBearerToken auth_token

deleteWarehouseStock : String -> Uuid -> String -> Api.Request ()
deleteWarehouseStock warehouseId_path productId_path auth_token =
    Api.request
        "DELETE"
        "/api/v1/warehouses/{warehouse_id}/stock/{product_id}"
        [ ( "warehouse_id", identity warehouseId_path ), ( "product_id", Uuid.toString productId_path ) ]
        []
        []
        Nothing
        (Json.Decode.succeed ())
        |> Api.withBearerToken auth_token

listWarehouseStock : String -> String -> Api.Request (List Api.Data.WarehouseStock)
listWarehouseStock warehouseId_path auth_token =
    Api.request
        "GET"
        "/api/v1/warehouses/{warehouse_id}/stock"
        [ ( "warehouse_id", identity warehouseId_path ) ]
        []
        []
        Nothing
        (Json.Decode.list Api.Data.warehouseStockDecoder)
        |> Api.withBearerToken auth_token

updateWarehouseStock : String -> Uuid -> Api.Data.StockAdjustment -> String -> Api.Request Api.Data.WarehouseStock
updateWarehouseStock warehouseId_path productId_path stockAdjustment_body auth_token =
    Api.request
        "PUT"
        "/api/v1/warehouses/{warehouse_id}/stock/{product_id}"
        [ ( "warehouse_id", identity warehouseId_path ), ( "product_id", Uuid.toString productId_path ) ]
        []
        []
        (Maybe.map Http.jsonBody (Just (Api.Data.encodeStockAdjustment stockAdjustment_body)))
        Api.Data.warehouseStockDecoder
        |> Api.withBearerToken auth_token
