{-
   SimpleBilly API
   Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

   The version of the OpenAPI document: 0.1.0
   Contact: support@simplebilly.com

   NOTE: This file is auto generated by the openapi-generator.
   https://github.com/openapitools/openapi-generator.git

   DO NOT EDIT THIS FILE MANUALLY.

   For more info on generating Elm code, see https://eriktim.github.io/openapi-elm/
-}


module Api.Request.Warehouse exposing
    ( createWarehouse
    , deleteWarehouse
    , getWarehouse
    , listWarehouses
    , updateWarehouse
    )

import Api
import Api.Data exposing (..)
import Dict
import Http
import Json.Decode
import Json.Encode


createWarehouse : Api.Data.Warehouse -> String -> Api.Request Api.Data.Warehouse
createWarehouse warehouse_body auth_token =
    Api.request
        "POST"
        "/api/v1/warehouses"
        []
        []
        []
        (Maybe.map Http.jsonBody (Just (Api.Data.encodeWarehouse warehouse_body)))
        Api.Data.warehouseDecoder
        |> Api.withBearerToken auth_token

deleteWarehouse : String -> String -> Api.Request ()
deleteWarehouse warehouseId_path auth_token =
    Api.request
        "DELETE"
        "/api/v1/warehouses/{warehouse_id}"
        [ ( "warehouse_id", identity warehouseId_path ) ]
        []
        []
        Nothing
        (Json.Decode.succeed ())
        |> Api.withBearerToken auth_token

getWarehouse : String -> String -> Api.Request Api.Data.Warehouse
getWarehouse warehouseId_path auth_token =
    Api.request
        "GET"
        "/api/v1/warehouses/{warehouse_id}"
        [ ( "warehouse_id", identity warehouseId_path ) ]
        []
        []
        Nothing
        Api.Data.warehouseDecoder
        |> Api.withBearerToken auth_token

listWarehouses : Maybe Int -> Maybe Int -> Maybe String -> Maybe Bool -> String -> Api.Request (List Api.Data.Warehouse)
listWarehouses page_query pageSize_query search_query isActive_query auth_token =
    Api.request
        "GET"
        "/api/v1/warehouses/"
        []
        [ ( "page", Maybe.map String.fromInt page_query ), ( "page_size", Maybe.map String.fromInt pageSize_query ), ( "search", Maybe.map identity search_query ), ( "is_active", Maybe.map (\val -> if val then "true" else "false") isActive_query ) ]
        []
        Nothing
        (Json.Decode.list Api.Data.warehouseDecoder)
        |> Api.withBearerToken auth_token

updateWarehouse : String -> Api.Data.AnyType -> String -> Api.Request Api.Data.Warehouse
updateWarehouse warehouseId_path body_body auth_token =
    Api.request
        "PUT"
        "/api/v1/warehouses/{warehouse_id}"
        [ ( "warehouse_id", identity warehouseId_path ) ]
        []
        []
        (Maybe.map Http.jsonBody (Just (encodeAnyType body_body)))
        Api.Data.warehouseDecoder
        |> Api.withBearerToken auth_token
