{-
   SimpleBilly API
   Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

   The version of the OpenAPI document: 0.1.0
   Contact: support@simplebilly.com

   NOTE: This file is auto generated by the openapi-generator.
   https://github.com/openapitools/openapi-generator.git

   DO NOT EDIT THIS FILE MANUALLY.

   For more info on generating Elm code, see https://eriktim.github.io/openapi-elm/
-}


module Api.Request.Webhooks exposing
    ( createSubscription
    , deleteSubscription
    , emitApi
    , listEvent
    , listSubscriptions
    , updateSubscription
    )

import Api
import Api.Data exposing (..)
import Dict
import Http
import Json.Decode
import Json.Encode


{-| Create a webhook subscription (outbound hook).
-}
createSubscription : Api.Data.CreateSubscriptionRequest -> String -> Api.Request Api.Data.WebhookSubscription
createSubscription createSubscriptionRequest_body auth_token =
    Api.request
        "POST"
        "/api/v1/webhook-subscriptions"
        []
        []
        []
        (Maybe.map Http.jsonBody (Just (Api.Data.encodeCreateSubscriptionRequest createSubscriptionRequest_body)))
        Api.Data.webhookSubscriptionDecoder
        |> Api.withBearerToken auth_token

{-| Delete a webhook subscription.
-}
deleteSubscription : String -> String -> Api.Request ()
deleteSubscription subscriptionId_path auth_token =
    Api.request
        "DELETE"
        "/api/v1/webhook-subscriptions/{subscription_id}"
        [ ( "subscription_id", identity subscriptionId_path ) ]
        []
        []
        Nothing
        (Json.Decode.succeed ())
        |> Api.withBearerToken auth_token

{-| Manually fire an event against matching hooks (for testing/flows).
-}
emitApi : Api.Data.EmitEventRequest -> String -> Api.Request ()
emitApi emitEventRequest_body auth_token =
    Api.request
        "POST"
        "/api/v1/webhooks/emit"
        []
        []
        []
        (Maybe.map Http.jsonBody (Just (Api.Data.encodeEmitEventRequest emitEventRequest_body)))
        (Json.Decode.succeed ())
        |> Api.withBearerToken auth_token

{-| List webhook events (inbound + outbound log).
-}
listEvent : String -> Api.Request (List Api.Data.WebhookEvent)
listEvent auth_token =
    Api.request
        "GET"
        "/api/v1/webhook-events"
        []
        []
        []
        Nothing
        (Json.Decode.list Api.Data.webhookEventDecoder)
        |> Api.withBearerToken auth_token

{-| List webhook subscriptions for the tenant.
-}
listSubscriptions : String -> Api.Request (List Api.Data.WebhookSubscription)
listSubscriptions auth_token =
    Api.request
        "GET"
        "/api/v1/webhook-subscriptions"
        []
        []
        []
        Nothing
        (Json.Decode.list Api.Data.webhookSubscriptionDecoder)
        |> Api.withBearerToken auth_token

{-| Update a webhook subscription.
-}
updateSubscription : String -> Api.Data.UpdateSubscriptionRequest -> String -> Api.Request Api.Data.WebhookSubscription
updateSubscription subscriptionId_path updateSubscriptionRequest_body auth_token =
    Api.request
        "PUT"
        "/api/v1/webhook-subscriptions/{subscription_id}"
        [ ( "subscription_id", identity subscriptionId_path ) ]
        []
        []
        (Maybe.map Http.jsonBody (Just (Api.Data.encodeUpdateSubscriptionRequest updateSubscriptionRequest_body)))
        Api.Data.webhookSubscriptionDecoder
        |> Api.withBearerToken auth_token
