{-
   SimpleBilly API
   Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

   The version of the OpenAPI document: 0.1.0
   Contact: support@simplebilly.com

   NOTE: This file is auto generated by the openapi-generator.
   https://github.com/openapitools/openapi-generator.git

   DO NOT EDIT THIS FILE MANUALLY.

   For more info on generating Elm code, see https://eriktim.github.io/openapi-elm/
-}


module Api.Request.Workflows exposing
    ( listWorkflowsApi
    , setWorkflowEnabledApi
    )

import Api
import Api.Data exposing (..)
import Dict
import Http
import Json.Decode
import Json.Encode


listWorkflowsApi : String -> Api.Request (List Api.Data.Workflow)
listWorkflowsApi auth_token =
    Api.request
        "GET"
        "/api/v1/workflows"
        []
        []
        []
        Nothing
        (Json.Decode.list Api.Data.workflowDecoder)
        |> Api.withBearerToken auth_token

setWorkflowEnabledApi : String -> Api.Data.WorkflowEnabledUpdate -> String -> Api.Request Api.Data.Workflow
setWorkflowEnabledApi workflowId_path workflowEnabledUpdate_body auth_token =
    Api.request
        "PUT"
        "/api/v1/workflows/{workflow_id}/enabled"
        [ ( "workflow_id", identity workflowId_path ) ]
        []
        []
        (Maybe.map Http.jsonBody (Just (Api.Data.encodeWorkflowEnabledUpdate workflowEnabledUpdate_body)))
        Api.Data.workflowDecoder
        |> Api.withBearerToken auth_token
